mozilla-services/merino-py

- .circleci/config.yml
Just some low hanging fruit. I noticed:
which lead me [here](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034)
> chore: switch deprecated circleci img

- merino/remotesettings.py
Noticed this oops while working on other things. It will hang the initilize method of the adm provider.
> fix: Provide an init value for attachment_host

- merino/config.py
- merino/configs/default.toml
- merino/providers/adm.py
This adds a background job to resync data from Remote Settings for the adm provider. The implementation is identical to the Rust version. Also, we should add some test coverage to this module as it gets more stuff in there. 
This fixes [CONSVC-1902](https://mozilla-hub.atlassian.net/browse/CONSVC-1902).
> feat(provider): Periodically resync data from Remote Setting

- CONTRIBUTING.md
- merino/main.py
Added simple CORS configurations to mernio-py as defined in the [FastAPI CORS docs](https://fastapi.tiangolo.com/tutorial/cors).
Looking at our current Merino-rs config, see [here in actix docs](https://docs.rs/actix-cors/latest/actix_cors/struct.Cors.html#method.permissive) and [here in source](https://docs.rs/actix-cors/latest/src/actix_cors/builder.rs.html#81) it was using the `permissive` setting, which for production is of course not desirable. While in the local testing phases, a permissible CORS configuration is desirable, but we will want to adjust it as time goes on. However, I did implement a few restrictions:
- Only permit GET, POST, OPTIONS, and HEAD requests (simple requests, excl OPTIONS)
- Did not permit credentials and cookies to be supported in cross-origin requests. …
> feat: enable cors CONSVC-1906

- Makefile
This adds documentation for the various `make` targets and makes it so that running `make` or `make help` produces the following outout:
```text
dev                   Run merino locally and reload automatically
format                Sort imports and reformat code
install               Install dependencies with poetry
lint                  Run various linters
run                   Run merino locally
test                  Run unit tests
```
Resolve #29
> [CONSVC-1952] Refactor Makefile to be self-documenting

- merino/config.py
- merino/config_logging.py
- merino/configs/ci.toml
- merino/configs/default.toml
- merino/configs/development.toml
- poetry.lock
- pyproject.toml
- tests/test_config_logging.py
This adds:
* An error log handler to capture/log exceptions
* A pretty log formatter (based on [rich](https://github.com/Textualize/rich)) for development. Note that this is meant to be used only for development. In production, we will stick to the vanilla MozLog. Hence the package `rich` was included as a dev dependency.
This fixes [CONSVC-1964](https://mozilla-hub.atlassian.net/browse/CONSVC-1964).
> [CONSVC-1964] feat(logging): Add an exception log hander and pretty formatter

- merino/providers/__init__.py
- merino/providers/adm.py
- merino/providers/base.py
- merino/remotesettings.py
- tests/providers/test_adm.py
Following the theme of #33, this pull request refactors the adm provider to improve testability.
It updates the provider to explicitly define the interfaces/protocols it depends on. This allows us to set up a fake remote settings client that implements that interface and use that in automated tests. It returns fake data that we can use to verify the provider implementation.
Outside of tests, we pass the live remote settings client to the provider (see `merino/providers/__init__.py`).
This pull request increases the test coverage for `merino/providers/adm.py` from 37% to 91%. I recommend adding unit tests for the `query()` method in a separate pull request. 🤖 
[CONSVC-1932](https://mozilla-hub.atlassian.net/browse/CONSVC-1932)
> [CONSVC-1932] Refactor provider to depend on RS backend protocol

- .pre-commit-config.yaml
I was unable to create new commits after rebasing to the latest `main` branch with pre-commit installed and enabled.
This pull request resolves the indentation issue with the `pydocstyle` object. I also ran the config through a YAML autoformatter for consistent formatting.
> fix: resolve formatting issues in pre-commit config file

- merino/providers/adm.py
As we're getting more keywords and suggestions from adM, this should save us some allocations and dict lookups while building indices for adM suggestions.
> refactor: Simplify suggestion index building for adM provider

- merino/config.py
- merino/configs/default.toml
- merino/configs/development.toml
- merino/configs/testing.toml
- merino/main.py
- merino/metrics.py
- merino/middleware/metrics.py
- merino/providers/__init__.py
- merino/web/api_v1.py
- poetry.lock
- pyproject.toml
- tests/test_config_logging.py
- tests/web/test_metrics.py
- tests/web/test_wiki_fruit.py
- tests/web/util.py
Adding metrics for merino. Currently the following are instrumented:
* Total provider initialization timing
* Individual provider initialization timing
* Total request timing (including middleware)
* Count of request status codes (per url path)
* Total provider query timing 
* Individual provider timing
Novel thing here is monkeypatching a local logger for dev that does not send messages across the upd socket and insteads logs the metrics. I like the visibility in development so if there's a better way please let me know.
> feat: Metrics - initial implementation

- merino/main.py
- merino/middleware/logging.py
- merino/middleware/user_agent.py
- merino/util/__init__.py
- merino/util/user_agent_parsing.py
- poetry.lock
- pyproject.toml
- tests/middleware/test_user_agent.py
- tests/test_user_agent.py
- tests/web/test_api_v1.py
- tests/web/test_dockerflow.py
- tests/web/test_geolocation.py
- tests/web/test_user_agent.py
- tests/web/util.py
This adds the user agent parsing & logging feature to merino-py.
Have tried a couple of UA parsing libs: [python-user-agents](https://github.com/selwin/python-user-agents), [woothee-python](https://github.com/woothee/woothee-python), and [uap-python](https://github.com/ua-parser/uap-python). Picking uap-python as it's the fastest one (10x faster than the other two) and it's actively developed & maintained compared to others.
This fixes [CONSVC-1935](https://mozilla-hub.atlassian.net/browse/CONSVC-1935).
> [CONSVC-1935] feat: Parse & log user agent

- CONTRIBUTING.md
- test-engineering/contract-tests/volumes/client/scenarios.yml
- test-engineering/contract-tests/volumes/kinto/data-03.json
- test-engineering/contract-tests/volumes/kinto/data-04.json
* Suggestions from Remote Settings are made available in testing though a call to Kinto to upload new suggestions. 
* Added new data json files to test and verify different impression and click url for same search term.
* Made additions to scenarios file to check same search term and verify result differs between both results.
* Matching search term is verified by a call to merino.
* Local suggestions removed if their counterpart is removed or updated in Remote Settings.
[CONSVC-1866](https://mozilla-hub.atlassian.net/browse/CONSVC-1866)
> Test/add contract tests for setting refresh consvc 1866 [do not deploy]

- merino/middleware/geolocation.py
- poetry.lock
- pyproject.toml
- tests/web/test_geolocation.py
Whe i was looking at some mypy errors i noticed that the maxminddb library we were using hasn't been updated in a year and doesn't have a nice of type definitions for the results of a geoip database lookup. This switches them and makes the test mypy compliant
> refactor: Switch to geoip2 library from maxminddb

- merino/providers/adm.py
- tests/unit/providers/test_adm.py
This adds an exception handler to the `adm` provider for the initial fetch to Remote Settings. Also added some unit tests to make `adm.py` 100% covered. 
This fixes [CONSVC-1965](https://mozilla-hub.atlassian.net/browse/CONSVC-1965).
> [CONSVC-1965] fix: add exception handling to adm provider for the init fetch

- merino/config_logging.py
The default stream of log handlers is `stderr` in Python, which confuses Cloud Logging as it treats all log records from stderr as `ERROR`.
Note that `console-pretty` is used in dev environments only, and it has its own stream implicitly set, so we don't need to configure it separately.
> chore: specify streams for log handlers

- docs/ops.md
- merino/providers/adm.py
Notice this while profiling merino-py. Turns out that the Dynaconf setting lookups can be expensive if the target setting is deeply nested in the hierarchy. The profiling result suggests that repeatedly referencing those nested settings such as in middlewares or route handlers would incur a significant overhead. To mitigate that, we can cache those settings whenever possible in those scenarios.
I've checked that this is the only case we have had so far. Will add a note to the relevant document for future reference.
> refactor: cache score from settings to avoid loading overhead

- merino/middleware/logging.py
- tests/unit/web/test_api_v1.py
This fixes [CONSVC-2017](https://mozilla-hub.atlassian.net/browse/CONSVC-2017).
> [CONSVC-2017] fix: use comma separated strings for request_providers and client_variants

- poetry.lock
- pyproject.toml
This allows us to override settings by `MERINO_PROVIDERS__ACCUWEATHER__API_KEY=foo` rather than `MERINO_PROVIDERS__accuweather__API_KEY=foo`.
> chore: upgrade dynaconf to 3.1.11

- docs/ops.md
- merino/config.py
- merino/configs/default.toml
- merino/providers/adm.py
- tests/unit/providers/test_adm.py
- tests/unit/providers/test_adm_wikipedia.py
This enforces the ranking criteria of "Sponsored Suggestions (0.3)" > "Top Picks (0.25)" > "Wikipedia (0.2)" >= "Local Remote Settings (0.2)". It's a bit messy to juggle those many scores, but we will clean those up once more sophisticated ranking gets added to Merino.
This fixes [CONSVC-2015](https://mozilla-hub.atlassian.net/browse/CONSVC-2015).
> [CONSVC-2015] feat: lower down score for adm wikipedia suggestions

- dev/top_picks_for_ci.json
- merino/configs/ci.toml
- merino/configs/default.toml
- tests/contract/client/tests/models.py
- tests/contract/volumes/client/scenarios.yml
Added scenarios for top pick provider to test exact match, varied character length, and secondary index 'similar' if mis-spelled.
Enabled top pick as default provider in `ci.toml` with a specific `top_picks_for_ci.json` file to allow contract test Docker to pick up provider and build suggestions.  Otherwise, Top Picks were not showing, since the provider won't be enabled in prod until we have our full domain list to index.  
Added `is_top_pick` to model and made keyword and advertiser optional fields to pass validation for Top Pick result.
Closes #101
> [CONSVC-2016] test: added contract tests for top pick provider [do not deploy]

- tests/integration/api/v1/fake_providers.py
- tests/integration/api/v1/providers/test_providers.py
Add integration test coverage to the `providers` endpoint
[CONSVC-2064](https://mozilla-hub.atlassian.net/browse/CONSVC-2064)
> [CONSVC-2064] test: add integration tests for the providers endpoint

- .circleci/config.yml
The `docs-publish-github-pages` job is broken on `main`, I guess CircleCI might've changed how the `- checkout` step works and `repo` is now needed for `gh-pages`.
> fix(ci): specify repo when publishing gh-pages [do not deploy]

- .circleci/config.yml
Sigh~, this is the actual fix to the `docs-publish-to-prod` bustage. As verified in #119 .
> chore: pin node to LTS to avoid bustages

- .circleci/config.yml
- .dockerignore
- .gitignore
- Makefile
- docs/dev/index.md
- pyproject.toml
- Add a minimum combined unit and integration test coverage check for 95%
- In the case of failure, Circle CI reports as follows:
- Output test results to file format compatible with CircleCI in order to take advantage of test insights
- ref: [Collecting test data](https://circleci.com/docs/collect-test-data/)
- Add `test-results` directory to `.gitignore`
- Update documentation
#87 | [CONSVC-2065](https://mozilla-hub.atlassian.net/browse/CONSVC-2065)
> [CONSVC-2065] Set minimum coverage for combined unit and integration tests

- merino/configs/flags/default.toml
- merino/configs/flags/testing.toml
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest.py
This is adding a feature flag decision to the API, so we can learn about using StatsD tags as query filters in our Grafana dashboard, while we don't use any actual feature flags in the suggest API.
Note: I enabled `dynaconf_merge` for feature flags the dynaconf `testing` environment, so that we can use the feature flag both in a deployed environment and in tests.
[CONSVC-1603](https://mozilla-hub.atlassian.net/browse/CONSVC-1603)
> [CONSVC-1603] feat: add example feature flag decision

- docs/dev/index.md
- docs/ops.md
- tests/contract/client/README.md
There were some typos that I noticed while going through the documentation. 
Again, [do not deploy] this change, as it's only documentation changes.
> Fix some typos in documentation [do not deploy]

- merino/middleware/geolocation.py
This fixes [CONSVC-2124](https://mozilla-hub.atlassian.net/browse/CONSVC-2124).
> [CONSVC-2124] fix: handle empty city names for geolocation parsing

- docs/dev/feature_flags.md
- merino/configs/flags/default.toml
- merino/configs/flags/testing.toml
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest.py
Our experiment was successful and showed that tags for feature flag decisions are indeed available in InfluxDB/Grafana. This means we can remove the `test_flight_01` feature flag, which I added in #123.
This pull request also adds a brief explanation on how to use feature flag tags in Grafana to our developer documentation. 
[CONSVC-1603](https://mozilla-hub.atlassian.net/browse/CONSVC-1603)
> [CONSVC-1603] chore: remove example feature flag decision

- docs/dev/release-process.md
We want to be more explicit about rolling back changes when things go wrong. I'm putting this first as it's probably the scenario we would prefer developers go to, rather than finding the fix itself (might be more impactful if it takes too long).
Also fixed a documentation link.
[do not deploy]
> Update release documentation [do not deploy]

- docs/dev/feature_flags.md
Sorry, my fault... I keep adding random `g` everywhere. This should remove it and fix the title on this. [do not deploy]
> chore: Remove extra character in title [do not deploy]

- merino/middleware/logging.py
- merino/utils/log_data_creators.py
- tests/integration/api/conftest.py
- tests/integration/api/test_error.py
- tests/integration/api/test_heartbeat.py
- tests/integration/api/test_version.py
- tests/integration/api/types.py
- tests/integration/api/v1/providers/test_providers.py
- tests/integration/api/v1/suggest/test_suggest.py
- tests/integration/api/v1/test_unsupported.py
- tests/unit/utils/test_log_data_creator.py
This will make it easier to do data validation on fields we send to logger and also encapsulates the logging metadata into extendable objects.
Fixes DISCO-2044
> [DISCO-2044] Put the log metadata fields into their own objects

- merino/configs/default.toml
A followup of [DISCO-2139](https://mozilla-hub.atlassian.net/browse/DISCO-2139?focusedCommentId=627176).
> chore: set accuweather query timeout to 5 seconds

- merino/utils/log_data_creators.py
- tests/unit/utils/test_log_data_creator.py
We could have requests where `seq` is not a valid integer string. These requests will most likely be sent from non-Firefox user agents but we should still handle the conversion exceptions in Merino to avoid errors.
> [DISCO-2138] fix: guard against malformed seq no

- merino/utils/log_data_creators.py
- tests/integration/api/v1/suggest/test_suggest.py
- tests/unit/utils/test_log_data_creator.py
As discussed over Slack with @hackebrot , I think it's worth being explicit about having separate fields for `datetime` object and `str` representation. This will make it clearer in the `dict()` export that we care about the `str` object, but also preserves the implicit validation of the `datetime` Pydantic object.
> Logging Object to use Separate `datetime` and `str` fields for timestamps

- tests/integration/api/v1/fake_providers.py
- tests/integration/api/v1/providers/test_providers.py
- tests/integration/api/v1/suggest/test_suggest.py
- tests/integration/api/v1/suggest/test_timeout_handling.py
This pull request refactors the fake providers we use in integration tests to use composition instead of inheritance. This architecture is optimized for comprehensibility and long-term maintainability.
For additional context, please see https://github.com/mozilla-services/merino-py/pull/140#discussion_r1046977863.
[DISCO-2147](https://mozilla-hub.atlassian.net/browse/DISCO-2147)
> [DISCO-2147] refactor: use composition for fake providers in int tests

- .circleci/config.yml
- Makefile
- docs/dev/index.md
- tests/contract/README.md
- tests/contract/docker-compose.yml
This allows the built artifact to be reused in various downstream steps.
> [DISCO-2141] Build merinopy in separate CI step

- .circleci/config.yml
This ensures that the `version.json` file exists so that it can be available during the build process.
> Write the version.json file before building image

- .circleci/config.yml
- Makefile
- docs/dev/index.md
We have multiple lint commands that are currently run sequentially. However, this makes it inefficient, as we will need to re-run the linter to get errors for subsequent commands. 
This change will allow us to use the `Makefile`'s `--keep-going` (`-k`) so that it can run all the dependant targets in the `lint` target regardless of whether it fails the checks. I opted for this approach over using multiple CircleCI jobs as it feels kind of overkill to bootstrap another job container to do all these small checks.  
Devs will also need to update their workflow to run `make -k lint` rather than `make lint` to get the advantage of parallelism (I'll make an announcement on Slack).
> Split the `lint` command to be able to run all in parallel

- merino/configs/development.toml
When executing Merino in a development environment, an error is raised if the AccuWeather API key is set to an empty value. This pull request sets the value to 'test'.
Example Error:
> fix: AccuWeather backend raises Error for undefined API key

- docs/ops.md
- merino/config.py
- merino/configs/default.toml
- merino/configs/testing.toml
- merino/web/api_v1.py
- tests/contract/client/tests/test_merino.py
- tests/integration/api/v1/suggest/test_suggest.py
Simple change to avoid potential DDoS where multiple instances of same provider are passed into the `providers` query param.  Wrapped in a set to eliminate duplicates. Didn't need additional filtering due to `if` check, which ensures the passed in `provider` is among those defined. Closes out one low severity finding in recent pen test. 
UPDATED: Added integration testing of api and also expanded functionality to limit number of `client_variants` that can be passed in to 5 to prevent low-risk reflection of client_variants. From the security assessment, it was found that because a list of `client_variants` would be constructed by splitting the `client_variant` query parameter, it was possible to pass in thousands of junk values or duplicates. This has now been limited to 5 and also …
> Suggest endpoint provider limitation on duplicate query params and client variants DISCO-2152

- .circleci/config.yml
Mdbook now requires rustc 1.64.
> chore: bump rust to 1.64 for mdbook

- docs/intro.md
The architecture diagram is coded with [Mermaid](https://mermaid.js.org/).
I put the image on the landing page of our documentation. If this isn't the right place for it, then we can create a new page. 
Also, I only included the `/api/v1/suggest` API for now. There are other APIs that we _might_ want to also add a flow diagram for. If we should add them, then let me know and I'll update the diagram.
> Add architecture diagram for Merino-py [do not deploy]

- .circleci/config.yml
- book.toml
This should fix the issue with the architecture diagram not compiling in mdbook.
> Add mbbook-mermaid to compile Mermaid diagrams in mdbook [do not deploy]

- merino/providers/__init__.py
- merino/providers/adm/backends/fake_backends.py
- merino/providers/adm/backends/protocol.py
- merino/providers/adm/backends/remotesettings.py
- merino/providers/adm/backends/testbackend.py
- merino/providers/adm/provider.py
- merino/providers/wikipedia/backends/fake_backends.py
- tests/integration/api/v1/suggest/test_suggest_wikipedia.py
- tests/unit/providers/adm/backends/test_remotesettings.py
- tests/unit/providers/adm/conftest.py
- tests/unit/providers/adm/test_provider.py
- tests/unit/providers/adm/test_provider_wikipedia.py
- tests/unit/providers/wikipedia/backends/test_elastic.py
* move AdM protocol from `...\adm\provider.py` to `...\adm\backends\protocol.py`
* move `TestBackend` from `...\adm\provider.py` to `...\adm\backends\test_backend.py`
* rename `RemoteSettingsBackend` to `AdmBackend`
* rename `LiveBackend` to `RemoteSettingsBackend`
* rename `TestBackend` to `FakeAdmBackend` and carry this convention to Wikipedia backends
* inject `merino.config.settings` into AdM `Provider` and `RemoteSettingsBackend`
* change `AdmBackend` protocol to have one method `fetch`
* move `fetch` method from AdM `Provider` to `RemoteSettingsBackend` 
* add unit tests for `RemoteSettingsBackend` 
**Note**
* Overall test coverage has increased from 97% to 98%
#167 | [DISCO-2166](https://mozilla-hub.atlassian.net/browse/DISCO-2174)
[DISCO-2166]: …
> [DISCO-2174] Refactor Merino AdM Protocol and Backends

- tests/load/Dockerfile
- tests/load/locust_tests/client_info.py
- tests/load/locust_tests/kinto_client.py
- tests/load/locust_tests/locustfile.py
- tests/load/locust_tests/suggest_models.py
- tests/load/poetry.lock
- tests/load/pyproject.toml
* Upgrade Merino-py load tests to python 3.11
#159 | [DISCO-2140](https://mozilla-hub.atlassian.net/browse/DISCO-2140)
[DISCO-2140]: https://mozilla-hub.atlassian.net/browse/DISCO-2140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2140] Upgrade Merino-py load tests to Python 3.11

- tests/load/README.md
- tests/load/locust_tests/locustfile.py
* Group all requests under the same category of URL to consolidate stats reporting and reduce output file size.
* Update the README documentation to remove UI crash warning and post exportation file aggregation
#188 | [DISCO-2228](https://mozilla-hub.atlassian.net/browse/DISCO-2228)
[DISCO-2228]: https://mozilla-hub.atlassian.net/browse/DISCO-2228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2228] Group HTTP calls for concise reporting in load tests

- Makefile
- dev/docker-compose.yaml
- docs/dev/dependencies.md
This fixes [DISCO-2234](https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/ )
[DISCO-2234]: https://mozilla-hub.atlassian.net/browse/DISCO-2234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2234] chore: Add redis for development

- merino/configs/default.toml
- merino/providers/__init__.py
- merino/providers/wikipedia/backends/elastic.py
- merino/providers/wikipedia/provider.py
- tests/unit/providers/wikipedia/backends/test_elastic.py
- tests/unit/providers/wikipedia/test_provider.py
Elastico requires a Cloud ID and API key to be passed to the client.
The provider times out when I try to connect to it locally, so I've increased the provider's timeout. Once we get an idea of what the distribution for the request looks like, we can reduce the timeout. The connection _should_ be faster in GCP, but not insignificant (around 170ms).
> Update Merino to grab the talk to the Elastico Elasticsearch

- .circleci/config.yml
I talked to jbuck about creating a new docker hub repo for `merino-jobs` however after some back and forth we decided to test how awkward it is to override the entrypoint in the job. To do that we need a stable tag for the docker image so this pr should tag and push a `latest` when we push to prod
> Tag and push a `latest` image to docker hub.

- docs/ops.md
This cleans up the documentation to reflect how we actually connect to Elasticsearch currently. Since we're still maintaining this page, the documentation should still be reflective of reality.
I also did a few grammatical clean up on the page.
[do not deploy]
> Remove unused configs and add `es_api_key` for Elasticsearch [do not deploy]

- docs/ops.md
- merino/cache/__init__.py
- merino/cache/none.py
- merino/cache/protocol.py
- merino/cache/redis.py
- merino/config.py
- merino/configs/default.toml
- merino/configs/development.toml
- merino/exceptions.py
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/backends/fake_backends.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- poetry.lock
- pyproject.toml
- tests/contract/README.md
- tests/contract/docker-compose.yml
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
This PR adds logic to cache `WeatherReport` responses from AccuWeather in Redis, expiring after 15 minutes by default.
> [DISCO-2028] Cache weather reports in Redis

- docs/adr/template.md
This commit adds a template for our Architecture Decision Records, using a similar format to Firefox Accounts, and already used for DISCO-2045.
It's more structured than Nygard's status-context-decision-consequences template, but explicitly enumerates the alternatives considered and the pros and cons of each, which has been helpful in other projects (FxA, Application Services, UniFFI) that use this format.
Factored out from #152—thanks for the reminder, @Trinaa! 😊
> [No bug] docs: add ADR template

- .circleci/config.yml
This bug was raised when working on contract tests for version endpoint. See [JIRA issue](https://mozilla-hub.atlassian.net/browse/DISCO-2264) for specifics. Changes in test client locally were not being reflected and new scenarios were causing test failures in CI. After digging, it was discovered that caching the docker image for contract tests was the issue. 
Verified by @Trinaa
> [DISCO-2264] changing docker contract test caching due to client errors 

- docs/ops.md
- merino/jobs/wikipedia_indexer/settings/v1.py
This lifecycle policy will expire the index after 90 days (around 3 months). We need to add the lifecycle policy to the cluster before we can merge this code change.
> Add a lifecycle policy for `enwiki` index

- .circleci/config.yml
- Makefile
- tests/contract/README.md
- tests/contract/client/README.md
- tests/contract/client/tests/models.py
- tests/contract/client/tests/test_merino.py
- tests/contract/docker-compose.yml
- tests/contract/volumes/client/scenarios.yml
* Version endpoint contract tests. 
* Took alternative path to cover all environments and to not simply skip in local. Achieved through:
- regex validation of sha-1 hash
- type check for HttpUrl to verify type check variance
- empty version string once in stage/prod
#170 | [DISCO-2178](https://mozilla-hub.atlassian.net/browse/DISCO-2178)
Replaces [old branch](https://github.com/mozilla-services/merino-py/pull/205) that was created when dealing with blocking cache bug that was resolved [DISCO-2264](https://mozilla-hub.atlassian.net/browse/DISCO-2264)
[DISCO-2178]: https://mozilla-hub.atlassian.net/browse/DISCO-2178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DISCO-2264]: https://mozilla-hub.atlassian.net/browse/DISCO-2264?atlOrigin=eyJpIjoiN …
> [DISCO-2178] Version Contract Tests for all environments

- docs/ops.md
- merino/configs/default.toml
- merino/providers/manager.py
- merino/providers/wikipedia/backends/elastic.py
- tests/unit/providers/wikipedia/backends/test_elastic.py
I'm saving the cloud id path just in case we want to still have it used for staging. It should be removed when we have some local development set up that involves a docker bootstrapped version of Elasticsearch.
> Initialize the Elasticsearch client with URL

- merino/configs/default.toml
- merino/jobs/wikipedia_indexer/__init__.py
- merino/jobs/wikipedia_indexer/util.py
- tests/unit/jobs/wikipedia_indexer/test_utils.py
This change will allow us to use the Elasticsearch URL if it is configured. If it doesn't exist, then fallback to using the Cloud ID.
@quiiver You should be able to configure the URL either with command line: `--elasticsearch_url` or setting the environment variable `MERINO__JOBS__WIKIPEDIA_INDEXER__ES_URL`.
> Allow Indexer job to configure URL Elasticsearch connection

- .circleci/config.yml
- add CircleCI step for building and publishing locust docker image
#224 | [DISCO-2274](https://mozilla-hub.atlassian.net/browse/DISCO-2274)
[DISCO-2274]: https://mozilla-hub.atlassian.net/browse/DISCO-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2274] Build load test Docker image in CI and Register

- .circleci/config.yml
- update dependency for docker-image-publish-merino-locust to docker-image-publish-stage
#224 | [DISCO-2274](https://mozilla-hub.atlassian.net/browse/DISCO-2274)
[DISCO-2274]: https://mozilla-hub.atlassian.net/browse/DISCO-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update dependency for docker-image-publish-merino-locust to docker-image-publish-stage

- merino/jobs/wikipedia_indexer/indexer.py
- tests/integration/jobs/wikipedia_indexer/test_indexer.py
`islice` is slightly shorter without annoying mypy. Also modified the tests to use generators as that's what the indexer expects (not sure why mypy didn't capture that).
> refactor: Replace chunk_bulk_stream with islice

- merino/providers/adm/backends/fake_backends.py
- merino/providers/adm/provider.py
- merino/providers/base.py
- merino/providers/top_picks/backends/top_picks.py
- merino/providers/top_picks/provider.py
- merino/providers/weather/backends/fake_backends.py
- merino/providers/wikipedia/backends/fake_backends.py
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_top_picks.py
- tests/unit/providers/adm/test_provider.py
- tests/unit/providers/top_picks/test_provider.py
The navigational top picks and AdM suggestion lookups are only triggered if the keyword it's written in all lowercase. Upper case or mixed case keywords do not currently result in a lookup.
- Top Picks and AdM return suggestions irrespective of case, regardless of what character may or may not be capitalized in the query string.
- As an added precaution, ensure domain property is lowercased and stripped during indexing (top picks)
- Create a default implementation of` normalize_query()` in the Provider abstract class so providers can implement their own normalization logic, based on their unique needs.
- Add relevant testing
- Added `normalize_query()` class for `Provider`, is extended for AdM and Top Picks
- Added logic to top picks backend to strip and lowercase domains as an added …
> [DISCO-2292] Add query string normalization to Merino

- PULL_REQUEST_TEMPLATE.md
JIRA: [DISCO-2295](https://mozilla-hub.atlassian.net/browse/DISCO-2295)
GitHub: N/A
Proposal to add a PR template to this project. All ideas, modifications and suggestions welcome!
[Github - Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
Examples\Inspo:
- [fxa template](https://github.com/mozilla/fxa/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
- firefox-ios
- [template](https://github.com/mozilla-mobile/firefox-ios/blob/main/PULL_REQUEST_TEMPLATE)
- [Pull Request Naming Guide](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [firefox-android …
> [DISCO-2295] Add Pull Request Template to Merino-py [do not deploy]

- .circleci/config.yml
- CONTRIBUTING.md
- docs/dev/release-process.md
- tests/load/README.md
* Add tagging functionality to trigger load tests.
The tag should take the form [load test: (abort|warn)]. 
The abort flag will prevent a stage deployment should the load test fail. 
The warn flag will output a Slack warning should the load test fail, but still allow for the stage deployment.
* Added shell script commands
* Annotated commands with comments
* Updated contributing docs
* Updated load test docs.
* Updated release-process.md docs
#222 | [DISCO-2254](https://mozilla-hub.atlassian.net/browse/DISCO-2254)
[DISCO-2254]: https://mozilla-hub.atlassian.net/browse/DISCO-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2254] Add keyword to Docker image tag for running load tests

- .circleci/config.yml
JIRA: [DISCO-2274](https://mozilla-hub.atlassian.net/browse/DISCO-2274)
GitHub: N/A
- add 'latest' tag for merino load test docker image
[DISCO-2274]: https://mozilla-hub.atlassian.net/browse/DISCO-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2274] Add 'latest' tag for merino load test docker image

- docs/SUMMARY.md
- docs/dev/index.md
- docs/intro.md
- docs/operations/configs.md
- docs/operations/elasticsearch.md
- docs/operations/index.md
- docs/operations/jobs.md
Adding and refactoring the documentations so that we are explicit about Merino Jobs operations. [do not deploy]
> Add Merino Jobs Operational Documentation [do not deploy]

- merino/providers/adm/provider.py
- tests/unit/providers/adm/conftest.py
- tests/unit/providers/adm/test_provider.py
JIRA: [DISCO-2236](https://mozilla-hub.atlassian.net/browse/DISCO-2236)
GitHub: [#193 ](https://github.com/mozilla-services/merino-py/issues/193)
This solution will ensure the provider is initialized with empty data and that queries will instead provide no result, opposed to raising a server error. An empty `suggestion_content` object will be used until the cron job gets a chance to retry the lookup of suggestion data. The retry cron has a fairly low latency so having no data to serve during that timeframe should be fine. This error should be rare in practice and since there is a retry mechanism in place, we do not need to take any other actions. 
The solution is to implement the initialization of an empty SuggestionContent object at the initialization of the AdM provider in the rare case …
> [DISCO-2236] AdM Provider Internal Server Error During Initialization

- .circleci/config.yml
JIRA: [DISCO-2169](https://mozilla-hub.atlassian.net/browse/DISCO-2169)
GitHub: N/A
- Fix the docker-image-publish job in CircleCI config
- Solution treats stage and prod Docker hub publishing distinctively, but another solution could be to use an or statement on the tag validation.
[DISCO-2169]: https://mozilla-hub.atlassian.net/browse/DISCO-2169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2169] Fix the docker-image-publish job in CircleCI config

- .circleci/config.yml
JIRA: [DISCO-2332](https://mozilla-hub.atlassian.net/browse/DISCO-2332)
GitHub: N/A
Remove the “main“ branch check from the `docker-image-publish` job and`docker-image-publish-locust` job in the Merino-py CI workflow. These jobs only run in the `main-workflow`, so the check is seemingly unneeded.
[DISCO-2332]: https://mozilla-hub.atlassian.net/browse/DISCO-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2332] Remove 'main' branch checks in Merino CI Docker Hub publication Jobs

- merino/configs/default.toml
JIRA: [DISCO-2345](https://mozilla-hub.atlassian.net/browse/DISCO-2345)
GitHub: [#TODO](https://github.com/mozilla-services/merino-py/issues/TODO)
This patch reduces the cache TTL for the weather provider from 2 hours to 30 minutes, which matches against the refresh cadence of Firefox.
[DISCO-2345]: https://mozilla-hub.atlassian.net/browse/DISCO-2345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2345] chore: Set the cache TTL for weather to match against Firefox

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
JIRA: [DENG-832](https://mozilla-hub.atlassian.net/browse/DENG-832)
JIRA: [DENG-834](https://mozilla-hub.atlassian.net/browse/DENG-834)
Post manual testing of new navigational suggestions job. Strips leading and trailing whitespace from the titles and corrects issue of image types not being set correctly.
[DENG-832]: https://mozilla-hub.atlassian.net/browse/DENG-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-834]: https://mozilla-hub.atlassian.net/browse/DENG-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DENG-832-834] title whitespace strip, change of upload_from_string call

- merino/configs/default.toml
- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
Fixes [DENG-833](https://mozilla-hub.atlassian.net/browse/DENG-833)
JIRA: https://mozilla-hub.atlassian.net/browse/DENG-833
Use GCS bucket CDN hostname (provided as cli options) for uploaded favicon url. When CDN hostname is not provided then use the public url of the uploaded favicon.
[DENG-833]: https://mozilla-hub.atlassian.net/browse/DENG-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use GCS bucket CDN hostname for uploaded favicon url

- merino/configs/default.toml
- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
JIRA:
GitHub:
We would like to be able to upload domain metadata to GCS even if the data already exists there.
_Why is this change necessary_?
Sometimes, it is necessary to update the entire domain metadata (see https://mozilla-hub.atlassian.net/browse/DENG-834 as a recent incident). Currently, the job avoids uploading the domain metadata to GCS if it already exists.
Due to the limitation of developers not having deletion rights in staging and prod environment, a force upload flag allows developers to re-upload the entire domain metadata to GCS staging and prod environment while simultaneously keeping the functionality to avoid re-uploading it if it already exists there.
> Enable force uploading in navigational suggestion job

- tests/integration/jobs/navigational_suggestions/test_domain_metadata_extractor.py
JIRA: [DISCO-2359](https://mozilla-hub.atlassian.net/browse/DISCO-2359)
GitHub: N/A
- Mark 'test_get_favicons' with xfail in order to mitigate the impact of test Flake on individual development and CI
[DISCO-2359]: https://mozilla-hub.atlassian.net/browse/DISCO-2359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2359] XFail 'test_get_favicons'

- merino/config_sentry.py
- tests/unit/test_config_sentry.py
JIRA: [DISCO-2235](https://mozilla-hub.atlassian.net/browse/DISCO-2235)
GitHub: [#261 ](https://github.com/mozilla-services/merino-py/issues/261)
It is essential to filter out potentially sensitive data when emitting events to Sentry. Currently, query strings and search terms are the values to be filtered and removed.
Accessing this through sentry requires defining a callback function that is associated with the `before_send` parameter in sentry_init(). See [Sentry documentation here](https://sentry-docs-o2paie5ivq-uc.a.run.app/error-reporting/configuration/filtering/?platform=python). This function grants access to the `event` object, in which all context of stack frames exit.  
It was found that at the API request level, the `query_string` parameter passed to Sentry is found at …
> [DISCO-2235] Exclude Sensitive Data from Sentry 

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
JIRA:
GitHub:
1. Removed non-leading and non-trailing duplicate whitespace/newline from title
1. As per the [comment](https://mozilla-hub.atlassian.net/browse/DENG-832?focusedCommentId=675222) in [DENG-832](https://mozilla-hub.atlassian.net/browse/DENG-832), this fixed the issue with the title for the domain "zara" observed in the [latest top picks](https://merino-images.services.mozilla.com/1682101445000.0_top_picks.json) file.
3. Added "Error" and "This page is not allowed" to the invalid title list
1. As per the [latest top picks](https://merino-images.services.mozilla.com/1682101445000.0_top_picks.json) file that was added via the [PR](https://github.com/mozilla-services/merino-py/pull/271) in this repo:
- 25 whatsapp, title: “Error”
- 269 hotstar, title: “Error”
- 721 ycombinator, …
> Improve quality of the titles for navigational suggestions

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_extractor.py
JIRA:
GitHub:
Somains for which scraper library couldn't scrape the title were assigned second level domain name as fallback title. The second level domain name always starts with lowercase letter. Hence capitalizing it made sense.
**Just to be consistent, I am capitalizing all the titles and not just the fallback ones.**
> Capitalize titles for navigational suggestions

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
JIRA:
GitHub:
This PR fixes following:
1. To test the presence of a domain's default favicon, we were wrongly checking whether the domain url is reachable or not instead of domain's default favicon url.
2. Robust generation of default favicon url (using `urllib.parse.urljoin` for generation)
> Fix logic to check the presence of default favicon

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
JIRA:
GitHub:
PR https://github.com/mozilla-services/merino-py/pull/274 capitalized all the titles. For lots of domains, this resulted into weird titles. e.g.
`YouTube` changed to `Youtube`
`Cloud Computing Services | Microsoft Azure` changed to `Cloud computing services | microsoft azure`
`OpenAI` changed to `Openai`
`MSN` changed to `Msn`
=> Capitalizing only fallback titles and leaving all the other ones same as scraped from the webpage.
> Capitalize only fallback titles for navigational suggestions

- merino/configs/default.toml
- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_extractor.py
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1830328
JIRA:
GitHub:
- Added a criteria to filter all favicons below a certain specified width so that they don't look blurry in Firefox Address bar
- Width can be specified via cli option "--min-favicon-width"
- Added a test case
> [Bugzilla-1830328] Fix blurry Top picks favicons

- .pre-commit-config.yaml
- merino/providers/amo/backends/dynamic.py
- merino/providers/amo/provider.py
- tests/unit/providers/amo/backends/test_dynamic.py
- tests/unit/providers/amo/test_provider.py
JIRA: [DISCO-2387](https://mozilla-hub.atlassian.net/browse/DISCO-2387)
GitHub: N/A
Noticed Merino's startup latency increased a lot when running Merino locally. The metrics suggested that the `amo` provider was the regressor. This patch makes the backend load addon data concurrently which speeds up its initialization on my box (from 3.8 seconds to 1.4 seconds). 
[DISCO-2387]: https://mozilla-hub.atlassian.net/browse/DISCO-2387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2387] refactor: Load addon data concurrently for the amo dynamic backend

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
Adds a flag to the nav suggestion job to write Airflow xcom data
See https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html#how-does-xcom-work and https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/xcoms.html for more detail.
Complement to https://github.com/mozilla/telemetry-airflow/pull/1700
> feat: Add flag to write Airflow XCom metadata.

- docs/operations/configs.md
- merino/config.py
- merino/configs/default.toml
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2372](https://mozilla-hub.atlassian.net/browse/DISCO-2372)
According to https://apidev.accuweather.com/developers/partner-code, we should append our partner code to the current conditions and forecast URLs returned in the API responses from AccuWeather.
This value isn't secret—it'll be returned in Merino API responses, and users will see it when they open the suggestion—but it's Mozilla-specific, so I'll add it to our ConfigMap instead of here.
[DISCO-2372]: https://mozilla-hub.atlassian.net/browse/DISCO-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2372] Append an optional partner code to AccuWeather response URLs

- merino/jobs/navigational_suggestions/domain_data_downloader.py
[DENG-880](https://mozilla-hub.atlassian.net/browse/DENG-880)
[DENG-881](https://mozilla-hub.atlassian.net/browse/DENG-881)
Update the domain category filter to remove `Weapons` and `Gambling` categories from the top domain query results. There was also a typo in the domain category id for `Violence` that has been fixed. 
[DENG-880]: https://mozilla-hub.atlassian.net/browse/DENG-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-881]: https://mozilla-hub.atlassian.net/browse/DENG-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DENG-880 DENG-881 Update domain category filters

- merino/providers/amo/addons_data.py
- merino/providers/amo/backends/dynamic.py
- merino/providers/amo/backends/protocol.py
- merino/providers/amo/backends/static.py
- merino/providers/amo/provider.py
- merino/providers/custom_details.py
- tests/unit/providers/amo/backends/test_dynamic.py
- tests/unit/providers/amo/backends/test_static.py
- tests/unit/providers/amo/test_provider.py
Since the `guid` is unlikely to change, we have added it to the static data of the addon. If we're finding that it _does_ change, can move it back to the API.
cc: @0c0w3 
> Add and return `guid` to AMO suggestions

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py
~~Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1832555~~
JIRA:
GitHub:
- Using scraping library with `allow_redirects=True`
- Use final redirected base url returned by scraping library for top picks file
- Skip domains for which the corresponding final redirected base url doesn't have domain itself as a substring
- Skip domains that are unreachable
- Updated unit test cases
~~Tested with `minecraft` and `facebook` domain to confirm that the final redirected base urls are being stored in top picks file.~~
> Improve URL for navigational suggestions

- merino/web/api_v1.py
- tests/contract/volumes/client/scenarios.yml
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/integration/api/v1/suggest/test_suggest_wikipedia.py
JIRA: [DISCO-2410](https://mozilla-hub.atlassian.net/browse/DISCO-2410)
GitHub: N/A
Merino includes all the optional fields (with the value set to null if unspecified - see discussion [here](https://github.com/mozilla-services/merino-py/pull/273#discussion_r1183193064)), which has accidentally changed the semantics in reporting. Specifically, Firefox used to omit those optional fields in telemetry if their values are set to `undefined`, but now they are `null`, which is not a valid value for reporting_url([schema def](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/templates/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json#L36-L39)).
This patch prevents Merino from sending nulls for optional fields in the response payload.
_Put an …
> [DISCO-2410] fix: Exclude optional fields from the API response

- merino/providers/wikipedia/provider.py
- tests/integration/api/v1/suggest/test_suggest_wikipedia.py
JIRA: [DISCO-2413](https://mozilla-hub.atlassian.net/browse/DISCO-2413)
GitHub: N/A
Regressed by the DISCO-2410 because we are not specifying the `block_id` for Dynamic Wikipedia suggestions but using the default value which will be excluded from the API reponse. Though `block_id` is a required field for Contextual Services impressions/clicks.
[DISCO-2413]: https://mozilla-hub.atlassian.net/browse/DISCO-2413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2410] fix: Use a dummy block_id for dynamic wikipedia suggestions

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py
JIRA:
GitHub:
- return combined metadata in single API instead of multiple functions for each metadata
- open the domain to be scraped only once instead of opening it multiple times (for favicon and title extraction)
- scrape for default favicon only when the domain doesn't specify one in the document explicitly
- modify unit tests
> Refactor domain metadata extraction for navigational suggestions

- merino/jobs/navigational_suggestions/utils.py
JIRA:
GitHub:
- Timeout of 60s is an overkill as it is delaying the execution of the whole job
- Reduced timeout to 10s
> Reduce http request timeout for navigational suggestions

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
Fixes [broken favicon for xfinity](https://bugzilla.mozilla.org/show_bug.cgi?id=1830535#c5) along with other favicons that might be broken because of the same reason.
JIRA:
GitHub:
- Avoid using 'sizes' attribute as the preferred and sufficient way to compute favicon size as some corrupted favicons ([like xfinity](https://bugzilla.mozilla.org/show_bug.cgi?id=1830535#c5)) made it to the top pick file by just having their sizes specificed via 'sizes' attribute
- Always compute favicon size via Pillow library to make sure the favicon itself is not corrupted
- this library is already being used to compute favicon sizes for the domains that don't specify size via 'sizes' attribute
- Removed obsolete unit test cases
> [bugzilla-1830535] Fix broken favicons for navigational suggestions

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
JIRA: Fixes https://mozilla-hub.atlassian.net/browse/DENG-917
GitHub:
- Using ["get_text()"](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#get-text) API to extract the text of "title" element instead of using ["string"](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#string) property
- "string" property returns "None" for the elements containing no text while get_text() returns empty string which is the right outcome
Tested for "nordstrom" and "jobs2careers" and the title is "Nordstrom" and "Jobs2careers" respectively instead of "None".
> [DENG-917] Robust title extraction for navigational suggestions

- merino/providers/adm/provider.py
- merino/providers/manager.py
- tests/unit/providers/adm/conftest.py
- tests/unit/providers/amo/test_provider.py
It's currently not using this, even though it's been defined. Fixing it so that it's refreshed more frequently.
Also added some more tests for AMO because I missed testing a line in the previous change.
> Use `cron_interval_sec` for AdM cron ticker

- .circleci/config.yml
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
- docs/dev/release-process.md
JIRA: [DISCO-2389](https://mozilla-hub.atlassian.net/browse/DISCO-2389)
GitHub: [#312 ](https://github.com/mozilla-services/merino-py/issues/312)
In order to assure fast feedback and accountability for all contributions, deploy all changes to the Merino-py main branch.
Acceptance Criteria
- Remove the skip-if-do-not-deploy command and it’s invocation from jobs in the CircleCI config
- Remove references to 'do not deploy' in documentation, including:
- docs/release_process.md
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
[DISCO-2389]: https://mozilla-hub.atlassian.net/browse/DISCO-2389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2389] Remove [do not deploy]

- merino/jobs/navigational_suggestions/domain_data_downloader.py
JIRA:
GitHub:
`top_domains_v1` table is scheduled to be updated every month via Airflow job. This job runs on 1st of a month for data collected for previous month and makes the `submission_date` as 1st of previous month.
Change `submission_date` filter accordingly.
> Fix submission date in SQL query for navigational suggestions

- merino/providers/amo/provider.py
- tests/integration/api/v1/suggest/test_suggest_amo.py
- tests/unit/providers/amo/test_provider.py
The logic that we want to use for AMO is to match the first word _exactly_ and then keyword expand the rest. This is as specified in the [Addons Suggest spec section 4.1.](https://docs.google.com/document/d/1XdEfA2Yr7x060hjCFo2dDBHfgBrVwH3on8OvKkRNL24/edit)
> Match full first word for AMO suggestions

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
An Attempt in the direction of fixing https://mozilla-hub.atlassian.net/browse/DENG-916
JIRA: https://mozilla-hub.atlassian.net/browse/DENG-916
GitHub:
The PR improves favicon scraping by
- Always including the default "favicon.ico" (which is present in the root of the domain) in the list of scraped favicons irrespective of whether we could scrape any favicon from document or not
- More comprehensive link and meta selectors
- Taken from favicongrabber source code [meta selectors](https://github.com/antongunov/favicongrabber.com/blob/master/server/api/grabber/browserconfig.js#LL4C35-L4C58) and [link selectors](https://github.com/antongunov/favicongrabber.com/blob/master/server/api/grabber/links.js#L6-L7)
> Improve favicon scraping for navigational suggestions

- dev/top_picks.json
JIRA:
GitHub:
- Imported from https://merino-images.services.mozilla.com/1686144862000.0_top_picks.json
- This causes the addition of favicons (thanks to this [PR](https://github.com/mozilla-services/merino-py/pull/319)) for few top domains for which we didn't have favicons before. e.g. **`yelp.com`, `tripadvisor.com`, `marriot.com`, `zillow.com`, `redfin.com`, `instacart.com`**
> Update top picks file for navigational suggestions

- tests/contract/client/Dockerfile
- tests/contract/docker-compose.yml
- tests/contract/kinto-setup/Dockerfile
JIRA: [DISCO-2442](https://mozilla-hub.atlassian.net/browse/DISCO-2442)
GitHub: N/A
- Fix the Poetry command in Contract Test DockerFiles
[DISCO-2442]: https://mozilla-hub.atlassian.net/browse/DISCO-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2442] Merino Contract Tests Failing In CI With Redis Error

- .circleci/config.yml
- dev/docker-compose.yaml
- tests/contract/docker-compose.yml
JIRA: N/A
GitHub: N/A
Pin Redis to the stable 6_X as what we use in production.
> chore: Pin Redis to 6_X

- .circleci/config.yml
JIRA: [DISCO-2445](https://mozilla-hub.atlassian.net/browse/DISCO-2445)
GitHub: N/A
Due to the Rust build overhead, the "build-docs" job in CI is now the long pole in the tent of our CI workflow. This patch switches to use the pre-built binaries which cut the job duration from 4 minutes to 4 seconds. The setup step looks messier but the gain is quite significant. 
[DISCO-2445]: https://mozilla-hub.atlassian.net/browse/DISCO-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2445] chore: Speedup the build-docs job in CI

- merino/configs/default.toml
JIRA: [DISCO-2446](https://mozilla-hub.atlassian.net/browse/DISCO-2446)
GitHub: N/A
Sentry sent an email indicating this feature is out of beta and will become a subscripted service. We don’t find this super useful for Merino, so let’s disable it.
[DISCO-2446]: https://mozilla-hub.atlassian.net/browse/DISCO-2446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2446] chore: Disable Sentry transactions

- merino/configs/default.toml
JIRA: [DENG-916](https://mozilla-hub.atlassian.net/browse/DENG-916)
GitHub:
- Reduce the width from 52 to 48 to include a lot of top ranked domains who have 48-pixel wide favicons
- Some of these domains are (as per local testing):  amazon, adobe, roblox, dailymail, bloomberg, cnbc, w3schools, snapchat, goodreads, ikea, expedia, accuweather
- It is worth to run the job with this change and let QA confirm us whether 48-pixel wide favicons also exhibit the same blurry behavior as was noticed in https://bugzilla.mozilla.org/show_bug.cgi?id=1830328
[DENG-916]: https://mozilla-hub.atlassian.net/browse/DENG-916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Reduce minimum favicon width criteria for navigational suggestions

- merino/providers/amo/provider.py
- tests/load/locust_tests/locustfile.py
- tests/unit/providers/amo/test_provider.py
JIRA: [DISCO-2388](https://mozilla-hub.atlassian.net/browse/DISCO-2388)
This adds some load tests for the AMO. AMO's keywords are hard coded, we can just import them to get some results.
Screenshot below of how it looks in Locust UI:
I hope that's sufficient for reporting purposes.
[DISCO-2388]: https://mozilla-hub.atlassian.net/browse/DISCO-2388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2388] Add load tests for AMO provider [load test: abort]

- merino/configs/default.toml
- merino/jobs/amo_rs_uploader/__init__.py
- merino/jobs/amo_rs_uploader/chunked_rs_uploader.py
- tests/unit/jobs/amo_rs_uploader/test_amo_rs_uploader.py
- tests/unit/jobs/amo_rs_uploader/test_chunked_rs_uploader.py
Modify the AMO RS uploader job by adding scores to AMO RS suggestions. The purpose of this is to give AMO RS suggestions a high score to ensure the client will prefer them to adM suggestions when there are keyword collisions. (There are currently 22 collisions total.)
This is intended as a quick fix for the upcoming AMO suggestions experiment. The client already looks for a `score` property in AMO suggestions, but currently none is defined, so the default 0.2 score is used. If/when AMO suggestions are enabled by default instead of being enabled only in experiments, we will want to revisit this.
To implement this in a way that can be used for all RS suggestion types, add a param to the chunked RS uploader that lets the consumer specify a fallback score for suggestions. If a suggestion …
> feat: add score to AMO RS suggestions and fallback scores to chunked RS uploader

- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/backends/fake_backends.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-2450](https://mozilla-hub.atlassian.net/browse/DISCO-2450)
Removing the caching from the weather provider because we are caching the full Accuweather response in the backend. 
[DISCO-2450]: https://mozilla-hub.atlassian.net/browse/DISCO-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2450] Remove caching from Weather Provider [load test: warn]

- merino/configs/default.toml
- merino/jobs/amo_rs_uploader/__init__.py
Change the score of AMO suggestions so it's less than the score of adM suggestions. Use the new score for both Merino and remote settings AMO suggestions. This ensures the client will show sponsored suggestions instead of AMO suggestions when keyword collisions occur, which according to Product is the desired behavior for both the addons-suggestion experiment and general release.
> fix: score AMO suggestions below adM suggestions

- tests/load/README.md
JIRA: [DISCO-2472](https://mozilla-hub.atlassian.net/browse/DISCO-2472)
GitHub: N/A
- Add workaround instruction to the load test Distributed GCP Execution procedure
[DISCO-2472]: https://mozilla-hub.atlassian.net/browse/DISCO-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2472] Load Test Script Modifies Kubernetes Config On First Run Only [load test: abort]

- merino/configs/default.toml
- merino/jobs/amo_rs_uploader/__init__.py
- merino/jobs/cli.py
- merino/jobs/pocket_rs_uploader/__init__.py
- merino/jobs/utils/chunked_rs_uploader.py
- tests/unit/jobs/amo_rs_uploader/test_amo_rs_uploader.py
- tests/unit/jobs/pocket_rs_uploader/test.csv
- tests/unit/jobs/pocket_rs_uploader/test_pocket_rs_uploader.py
- tests/unit/jobs/utils/test_chunked_rs_uploader.py
Add a job that uploads Pocket suggestions to remote settings. The source data is expected to be in a CSV file because we're collaborating with the Pocket team to build a list of suggestions and keywords using [this Google sheet](https://docs.google.com/spreadsheets/d/14mjaEYWnHD3VuTT5vq1HCzCz9e98cm8Z5a9fwjtKzGw/edit?usp=sharing). Running this job requires an initial manual step of exporting the sheet as CSV. I didn't add the CSV to this commit because I don't think we want to keep it in the repo.
Move chunked_rs_uploader.py to a new jobs/utils directory so it can be shared between the AMO and Pocket uploader and any future uploader jobs. Modify it to zero-pad the chunk start and end indexes in record IDs similar to how indexes are zero-padded in adm records.
_Put an `x` in the boxes that …
> feat: add Pocket RS suggestions uploader

- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2473](https://mozilla-hub.atlassian.net/browse/DISCO-2473)
GitHub: N/A
- follow-up to https://github.com/mozilla-services/merino-py/pull/354, enable injection of the AsyncClient to maintain test-ability ([ref](https://github.com/mozilla-services/merino-py/pull/354#discussion_r1253210392))
[DISCO-2473]: https://mozilla-hub.atlassian.net/browse/DISCO-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2473] Inject AsyncClient into AccuweatherBackend

- docs/dev/release-process.md
- tests/load/README.md
- tests/load/docker-compose.yml
JIRA: [DISCO-2478](https://mozilla-hub.atlassian.net/browse/DISCO-2478)
GitHub: N/A
- Remove merino from the load test docker-compose definition
- It is not the common use case that a team member would execute the load tests against a local instance of Merino. Furthermore, local execution would most likely be for the profiling use case, which necessitates executing Merino with different configurations. 
- Add instructions for accessing load test logs in release procedure
- Add resource consumption to load test result analysis documentation
[DISCO-2478]: https://mozilla-hub.atlassian.net/browse/DISCO-2478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2478] Merino: Load Test Config Changes & Document Updates

- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2480](https://mozilla-hub.atlassian.net/browse/DISCO-2480)
GitHub: N/A
We currently cache the raw API responses from AccuWeather in Redis which contain lots of unused data. To reduce the bandwidth and cache fetch/store time, we should only cache the processed data instead.
Raw vs. Processed for one record:
- Location key: 1.2 KB / 0.03 KB
- Current conditions: 0.5 KB / 0.05 KB
- Forecasts: 1 KB / 0.05 KB
[DISCO-2480]: https://mozilla-hub.atlassian.net/browse/DISCO-2480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2480] refactor: cache processed content for accuweather

- tests/load/README.md
- tests/load/kubernetes-config/locust-master-controller.yml
- tests/load/kubernetes-config/locust-worker-controller.yml
- tests/load/setup_k8s.sh
JIRA: [DISCO-2472](https://mozilla-hub.atlassian.net/browse/DISCO-2472)
GitHub: #350 
- Improve load test setup script by using patterns fixed on constants instead of placeholders
- Update load test README
**Related PR:** https://github.com/mozilla-services/contile/pull/609
[DISCO-2472]: https://mozilla-hub.atlassian.net/browse/DISCO-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2472] Merino: Load Test Script Modifies Kubernetes Config On First Run Only

- merino/providers/wikipedia/backends/elastic.py
- tests/unit/providers/wikipedia/backends/test_elastic.py
JIRA: [DISCO-2474](https://mozilla-hub.atlassian.net/browse/DISCO-2474)
GitHub: [#366 ](https://github.com/mozilla-services/merino-py/issues/366)
Reported on the #contextual-services-tech Slack channel on June 28th 2023
Some titles on wikipedia seem to have a comma at the end (this one is likely because the title is “Split, Croatia”). It’s low priority but we should fix it at some point if we can if there are multiple occurrences.
Multiple occurrences found, mostly with geographic locations.
As discussed in ticket, we could just again return the title, but upon investigation this method required the removal of the comma from passed in title, as `get_best_keyword` method splits on the space, which is inclusive of the comma.  Have added logic to remove any and all punctuation that could …
> [DISCO-2474] Merino: Titles in Wikipedia Suggestions Have Trailing Punctuation

- merino/configs/default.toml
- merino/providers/weather/backends/accuweather.py
GitHub: [#TODO](https://github.com/mozilla-services/merino-py/issues/TODO)
Temporarily increase the cache TTL (from 30 mins to 45 mins) due to high request latency to AccuWeather.
> chore: Increase cache TTL for accuweather

- merino/configs/default.toml
Currently we're running into quite a lot of API failures. While we investigate this, let's switch over to the static AMO suggestions to stop unnecessarily calling the live Addons endpoint.
Errors can be seen in Sentry: https://mozilla.sentry.io/issues/?project=6622434
> Temporarily turn off Dynamic AMO

- merino/config_logging.py
JIRA: [DISCO-2475](https://mozilla-hub.atlassian.net/browse/DISCO-2475)
GitHub: #369 
Check to see if this will fix the log categorization in GCP. 
This should switch _severity_ to using the GCP compatible severity codes, rather than the syslog codes that is outputted by `mozlog`. If this fixes the issue, consider patching [dockerflow](https://github.com/mozilla-services/python-dockerflow/blob/main/src/dockerflow/logging.py#L35).
[DISCO-2475]: https://mozilla-hub.atlassian.net/browse/DISCO-2475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2475] Overwrite the log severity codes to GCP logging

- merino/config.py
- merino/config_logging.py
- merino/configs/default.toml
- merino/configs/testing.toml
JIRA: [DISCO-2475](https://mozilla-hub.atlassian.net/browse/DISCO-2475)
This sets the Merino logger `propagate=False`. This is to hopefully prevent the ancestor loggers from logging unnecessarily to the stdout/stderr. I _think_ that this will fix the issue with GCP logging a random `text` formatted message, but not entirely certain. If anything, this change will clean up the logging locally (prevent the double entries when you run server).
Some documentation on `propagate`: https://docs.python.org/3/library/logging.html?highlight=propagate#logging.Logger.propagate
[DISCO-2475]: https://mozilla-hub.atlassian.net/browse/DISCO-2475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Disable propagate logs

- merino/configs/default.toml
JIRA: [DISCO-2563](https://mozilla-hub.atlassian.net/browse/DISCO-2563)
GitHub: [#TODO](https://github.com/mozilla-services/merino-py/issues/TODO)
Product has given the go-ahead call to enable `top_picks` in Merino.
[DISCO-2563]: https://mozilla-hub.atlassian.net/browse/DISCO-2563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Enabled the top_picks provider

- PULL_REQUEST_TEMPLATE.md
JIRA: [DISCO-2572](https://mozilla-hub.atlassian.net/browse/DISCO-2572)
remove github link from PR template
[DISCO-2572]: https://mozilla-hub.atlassian.net/browse/DISCO-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2572] remove github link from PR template

- merino/cache/none.py
- merino/cache/protocol.py
- merino/cache/redis.py
- merino/config.py
- merino/configs/default.toml
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2482](https://mozilla-hub.atlassian.net/browse/DISCO-2482)
GitHub: N/A
This patch uses a Lua script to bulk fetch weather data from Redis. It cuts the Redis lookup calls from 3 to 1 per each request. Local benchmark suggests it has increased ~50% in throughput and ~30% in latency in a high cache-hit scenario (similar to production). It should perform better in other scenarios as well as it reduces the overall overhead for Redis cache lookups.
Main vs This branch
QPS: 1,150 vs 1,750 (52%)
Latency (p95): 110ms vs 77ms (30%)  
Need to add/fix tests
[DISCO-2482]: https://mozilla-hub.atlassian.net/browse/DISCO-2482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2482] refactor: Use bulk fetch for accuweather backend [load test: abort]

- docs/operations/configs.md
- merino/cache/redis.py
- merino/config.py
- merino/configs/default.toml
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2575](https://mozilla-hub.atlassian.net/browse/DISCO-2575)
Merino currently refreshes "Current Conditions" and "Forecast" at the same time regardless of its cache validity, this patch implements fine-grained refreshing so that it only refreshes the cached data if they're expired. 
[DISCO-2575]: https://mozilla-hub.atlassian.net/browse/DISCO-2575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2575] refactor: Perform fine-grained cache refreshing for accuweather backend [load test: abort]

- docs/SUMMARY.md
- docs/dev/release-process.md
- docs/operations/rollback.md
- docs/operations/testfailures.md
JIRA: [DISCO-2513](https://mozilla-hub.atlassian.net/browse/DISCO-2513)
Fixes #400 
This makes the "rollback" documentation more searchable. 
I also moved out the test "debugging" documentation from the release docs. We want to keep stuff in the "Release Process" documentation at a conceptual level. However as procedural documentation, they're excellent (so they're unmodified).
[DISCO-2513]: https://mozilla-hub.atlassian.net/browse/DISCO-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Moved Rollback documentation into its own file

- Makefile
- tests/load/README.md
JIRA: [DISCO-2581](https://mozilla-hub.atlassian.net/browse/DISCO-2581)
Updates the following for load tests:
- Update the load-tests-clean command to match the contract tests, adding `docker rmi locust` to remove containers and networks when changes made to load test code
- Added local dev note to run `make load-tests-clean` between code changes.
- Added documentation on how to access host mach ine's merino instance through `host.docker.internal`
- Added context to requirement to add API key
[DISCO-2581]: https://mozilla-hub.atlassian.net/browse/DISCO-2581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2581] update load test docker command and documentation for local tests

- merino/providers/adm/backends/remotesettings.py
- tests/load/locustfiles/locustfile.py
JIRA: [DISCO-2534](https://mozilla-hub.atlassian.net/browse/DISCO-2534)
Related to DISCO-2534.
Fix for production env of locust where change could not be verified locally. `KeyError` occurred from `KINTO__SERVER_URL` not being found. 
Due to a change to enforce stricter typing of imported enviornment variables, `os.environ["KEY"]` replaced a call to `os.getenv("KEY")`. This was done as `getenv` can return `None`, which did not match the class signatures which these variables are passed into. 
Upon further investigation, it became clear that in `remotesettings.py`, a check is done at the creation of `RemoteSettingsBackend` (see [HERE](https://github.com/mozilla-services/merino-py/blob/28b3775ed9a0dc9ba446d1627149255693afd1d4/merino/providers/adm/backends/remotesettings.py#L37-L57)) to see …
> fix to resolve kinto key error for load tests [load test: abort]

- merino/providers/amo/backends/dynamic.py
- tests/unit/providers/amo/backends/test_dynamic.py
JIRA: [DISCO-2598](https://mozilla-hub.atlassian.net/browse/DISCO-2598)
This is to help us hopefully get more information on what is causing the errors for AMO requests.
[DISCO-2598]: https://mozilla-hub.atlassian.net/browse/DISCO-2598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2598] Add some extra logging to AMO request errors

- docs/operations/configs.md
- merino/configs/default.toml
JIRA: [DISCO-2583](https://mozilla-hub.atlassian.net/browse/DISCO-2583)
Merino currently keeps configuration documents, we’ve found it inconvenient to keep two sources of documents - this and the one within the configuration TOML files. Let’s move the relevant docs from the Markdown file to `default.toml` to ease the config documentation for Merino.  
Notes for review:
Updated readability of toml file so more space delineates configs, all env vars like in original documentation define start of new value.
The `configs.md` remains with important contextual documentation that also points to external links. Hence this is why it wasn't moved into the `toml` file. Optionally, this could be moved, but since it's more broad generalized documentation that isn't specifically related to the configs …
> [DISCO-2583] configs from config.md to default.toml

- docs/operations/jobs/csv-remote-settings.md
- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/base.py
- merino/jobs/utils/chunked_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/test_csv_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/test_mdn.py
- tests/unit/jobs/csv_rs_uploader/test_pocket.py
[Dupe keyword discussion](https://github.com/mozilla/application-services/pull/5841)
There's some kind of unrelated new problem with the uploader where `json.dumps()` can't serialize the `Url` objects created by Pydantic. Nothing changed in the uploader so I don't know if this is due to upgrading Pydantic or what. This PR fixes that too.
> feat: modify csv uploader job to remove dupe keywords

- merino/providers/adm/backends/remotesettings.py
JIRA: [DISCO-2585](https://mozilla-hub.atlassian.net/browse/DISCO-2585)
During on_locust_test_start, the Merino load tests query Remote Settings in order to gather query strings for performance evaluation of the AdM provider. Occasionally this query fails at which time the load tests are programmed to exit with a failure status. There are also times when this fails when merino is running locally without load tests. This behavior is geared towards the CD use case, where we want to fail fast and a proper exit code is required. The behavior is not ideal for local execution as it requires re-starting the locust_master Docker container to try again.
Ideally, we will increase the timeout duration and hopefully this will be similar to the issues we had with the AMO provider timeouts.
Note: this …
> [DISCO-2585] Merino: Intermittent Failure Gathering AdM Queries From Remote Settings In Local Dev & Load Tests [load test: abort]

- docs/dev/content-moderation.md
- docs/operations/blocklist-wikipedia.md
- merino/jobs/wikipedia_indexer/__init__.py
- merino/providers/manager.py
- merino/providers/top_picks/backends/top_picks.py
- merino/utils/blocklist.py
- merino/utils/blocklists.py
- tests/data/top_picks.json
- tests/integration/api/v1/suggest/test_suggest_top_picks.py
- tests/load/locustfiles/locustfile.py
- tests/unit/providers/top_picks/backends/test_top_picks.py
- tests/unit/providers/top_picks/conftest.py
JIRA: [DISCO-2623](https://mozilla-hub.atlassian.net/browse/DISCO-2623)
Currently, we have a feature in the Wikipedia provider that checks against categories in a block list. This allows for ad-hoc blocking which requires just a PR and merge to immediately remove terms from being presented to clients. 
This is implemented for the Top Picks Provider, though with some differences:
- Block 2nd-level domain, not term. Contained in a set of strings. This is the `"domain"` key in the JSON data.
- This filtering takes place at the creation of the backend and therefore a blocked suggestion is not indexed.
- Uniform `blocklists.py` utility module that contains the in-memory blocklists for Wikipedia and Top Picks.
Note: Subsequent PR will decouple the `navigational_suggestions` job block list JSON …
> [DISCO-2623] Top Picks Content Moderation - Ad-hoc Blocking: Exclude Blocklist Domains at Provider Backend

- merino/jobs/csv_rs_uploader/pocket.py
- tests/unit/jobs/csv_rs_uploader/test_pocket.py
See discussion in https://github.com/mozilla/application-services/pull/5841
When validating Pocket suggestions, remove low-confidence keywords that dupe high-confidence keywords.
> feat: modify csv uploader job to remove low keywords that dupe high keywords

- merino/config.py
- merino/configs/default.toml
- merino/configs/testing.toml
- merino/providers/__init__.py
- merino/providers/manager.py
- tests/integration/api/v1/conftest.py
- tests/integration/api/v1/fake_providers.py
- tests/integration/api/v1/providers/test_providers.py
- tests/unit/providers/test_init_providers.py
JIRA: [DISCO-2634](https://mozilla-hub.atlassian.net/browse/DISCO-2634)
Implementation of a circuit-breaker to disable certain providers from initializing that can't be bypassed using normal API request params like `enabled_by_default` and `hidden`
Documentation in disaster recovery runbook updated as well. 
[DISCO-2634]: https://mozilla-hub.atlassian.net/browse/DISCO-2634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2634] Disable Provider Disaster Recovery

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
JIRA: [DISCO-2626](https://mozilla-hub.atlassian.net/browse/DISCO-2626)
The merino_job currently generates a new file with the Unix Epoch timestamp prepending the file. We want to add _latest for easily grabbing the file and to also have functionality to update the existing _latest each time the job runs.
Some improvements were made to the `DomainMetadataUploader` like converting the `_destination_top_pick_name` method to a staticmethod with a parameter for suffix to make it more testable, as well as resolving the rounding issue where a needless trailing `.0` was generated after each epoch timestamp. Also, the timestamp is converted from microseconds to a standard timestamp with a simpler method, being `int(current.timestamp())`, given it is called in the UTC context anyways, avoiding a …
> [DISCO-2626] Update merino_job to generate file with _latest prefix, update old file

- .circleci/config.yml
- tests/load/Dockerfile
- tests/load/poetry.lock
- tests/load/pyproject.toml
- tests/load/setup_k8s.sh
JIRA: [DISCO-2465](https://mozilla-hub.atlassian.net/browse/DISCO-2465)
Update dependencies according to our maintenance guidelines for merino load tests.
-Updates image definitions for ubuntu
-Update all Poetry dependencies (will resolve all security warnings in repo)
-Update `setup_k8s.sh` to include `--total` in front of `min-nodes` and `max-nodes` so this encompasses all regions and does not spin up the min/max in each and every region
[DISCO-2465]: https://mozilla-hub.atlassian.net/browse/DISCO-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2465] Q4 load test maintenance [load test: abort]

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_diff.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- merino/providers/top_picks/backends/filemanager.py
- merino/providers/top_picks/provider.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_diff.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/providers/top_picks/backends/test_filemanager.py
- tests/unit/providers/top_picks/backends/test_top_picks.py
- tests/unit/providers/top_picks/test_provider.py
JIRA: [DISCO-2620](https://mozilla-hub.atlassian.net/browse/DISCO-2620)
Like the spec for Shepherd storage.py [here](https://github.com/mozilla-services/consvc-shepherd/blob/main/consvc_shepherd/storage.py), we want merino jobs to similarly create a latest file which is always overridden (`top_picks_latest.json`) and used as the single domain source while also writing a second file for our records with the time stamp(`<0123>_top_picks_latest.json`).
This improves reliability and decreases possibility of bottlenecks when future data grows. 
Note: The process will now write a`top_picks_latest.json` file from which data will be read and overwritten as well as a timestamped file `<0123>_top_picks_latest.json` for our records. The timestamped files at each generation will have the `_latest` …
> [DISCO-2620] Update `_latest` logic to write core domain file and timestamp file

- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
add delimiter to just get files in root and match_glob to only capture json files
> Update method to exclude favicons and match only json files

- merino/config.py
- merino/configs/stage.toml
JIRA: [DISCO-2706](https://mozilla-hub.atlassian.net/browse/DISCO-2706)
Add stage configs to scope values for stage deployment
Matching SRE cloudops-infra ticket [here](https://github.com/mozilla-services/cloudops-infra/pull/5313/files)
[DISCO-2706]: https://mozilla-hub.atlassian.net/browse/DISCO-2706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2706] stage configs

- catalog-info.yaml
This is because this link is supposed to point to internal backstage documentation, not to external docs. So removing it from the catalog.
> Remove techdocs reference in Service Catalog

- merino/middleware/geolocation.py
- merino/providers/geolocation/provider.py
- tests/unit/middleware/test_geolocation.py
- tests/unit/providers/geolocation/test_provider.py
JIRA: https://mozilla-hub.atlassian.net/browse/SNG-928
We implemented a provider that returns geolocation in https://github.com/mozilla-services/merino-py/pull/482.
The provider returns iso code as a city and region name, but cannot be used as a parameter for Yelp since it is represented by a number in Japan. (e.g. `14` which expresses `Kanagawa`)
https://en.wikipedia.org/wiki/ISO_3166-2:JP
Therefore, make the provider return the name of the country and the name of the region.
> Make geolocation provider return location name instead of iso code

- merino/config_sentry.py
- tests/unit/test_config_sentry.py
JIRA: [DISCO-2731](https://mozilla-hub.atlassian.net/browse/DISCO-2731)
We want to redact the Elasticsearch queries that are sent to Sentry because they might contain keywords. So, this will just redact the whole Elasticsearch query object. 
[DISCO-2731]: https://mozilla-hub.atlassian.net/browse/DISCO-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Redact the Elasticsearch query in Sentry

- .circleci/config.yml
- tests/contract/client/Dockerfile
- tests/contract/kinto-setup/Dockerfile
- tests/load/Dockerfile
JIRA: [DISCO-2766](https://mozilla-hub.atlassian.net/browse/DISCO-2766)
- Fix the following error message by changing the `PYTHON_VENV`environment name from "venv" to ".venv". The [documentation](https://python-poetry.org/docs/configuration#virtualenvscreate) indicates that ".venv" is required when setting `POETRY_VIRTUALENVS_CREATE` to "false".
- Fix the following warning message with the `--no-root` option
- Add creation of load test Docker image to the PR workflow so that we get earlier notice of this type of break if it should happen in the load test solution. Load test Docker image publication was tested [here](https://app.circleci.com/pipelines/github/mozilla-services/merino-py/2435/workflows/ad9cc8cc-28b5-4c33-9452-f119b4aaa677) and …
> [DISCO-2766] Error with Poetry configurations/CLI arguments for contract tests in Merino [load test: warn]

- .gitignore
- merino/content_handler/__init__.py
- merino/content_handler/gcp_uploader.py
- merino/content_handler/models.py
- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- merino/jobs/navigational_suggestions/utils.py
- tests/unit/content_handler/test_gcp_uploader.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py
JIRA: [DISCO-2742](https://mozilla-hub.atlassian.net/browse/DISCO-2742)
Refactoring and decoupling the GCP logic for uploading files into a separate module.
[DISCO-2742]: https://mozilla-hub.atlassian.net/browse/DISCO-2742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Extract gcp upload logic into a separate module

- .circleci/config.yml
- docs/testing/integration-tests.md
- poetry.lock
- pyproject.toml
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_uploader.py
JIRA: [DISCO-2767](https://mozilla-hub.atlassian.net/browse/DISCO-2767)
Add integration tests for `GcsUploader` using `testcontainers` library
We had to switch to using `machine` executors for running the `integration-tests` check since the `testcontainers` test spin up a docker container at run time. This wasn't working if we were using the docker container to run those tests in. Surprisingly, setting up a python environment on a bare bones ubuntu VM and running the tests seems to be slightly faster than using a pre-built python docker image
In the `project.toml` file, you'll see that the new dev dependencies are added under `tool.poetry.group.dev.dependencies` and not `tool.poetry.dev.dependencies`. This is because the latter has been deprecated. Poetry wants us to use `...group...` …
> test: add integration tests for GcsUploader using testcontainers library

- merino/configs/default.toml
- merino/jobs/relevancy_uploader/__init__.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- tests/unit/jobs/relevancy_uploader/test_chunked_relevancy_rs_uploader.py
- tests/unit/jobs/relevancy_uploader/utils.py
JIRA: [DISCO-2795](https://mozilla-hub.atlassian.net/browse/DISCO-2795)
I accidentally edited `delete_existing_records` default config value by accident
and delete records wasn't deleting properly since I didn't override it for relevancy specifically
[DISCO-2795]: https://mozilla-hub.atlassian.net/browse/DISCO-2795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2795] fix: relevancy job to delete records by category

- merino/cache/protocol.py
- merino/configs/default.toml
- merino/providers/custom_details.py
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-2781](https://mozilla-hub.atlassian.net/browse/DISCO-2781)
This PR is in lieu of this [original PR](https://github.com/mozilla-services/merino-py/pull/505). Since I broke prod with the original PR, this PR serves as a fix. [See sentry errors](https://mozilla.sentry.io/issues/?environment=prod&project=6622434&referrer=sidebar&statsPeriod=24h&utc=true).
I cherry picked the commit from the original one since most of the logic / work is the same except the bug fix. I've added comments below where I've added the bug fix.
I've tested it locally with different partial cache hit scenarios.
[DISCO-2781]: https://mozilla-hub.atlassian.net/browse/DISCO-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2781] Set http cache header for suggestions response

- merino/configs/default.toml
- merino/providers/base.py
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/backends/test_accuweather_city.py
JIRA: [DISCO-2806](https://mozilla-hub.atlassian.net/browse/DISCO-2806)
Adding functionality to provide location completion suggestions via Accuweather api by modifying our existing `/suggest` endpoint.
- Make sure your `default.local.toml` has the correct settings and the `accuweather_city` provider's `cache` is set to `redis`. 
- Start the redis instance: `cd dev && docker-compose up`
- Start merino `make dev`
This should return empty suggestions:
`curl -i -X 'GET' 'localhost:8000/api/v1/suggest?q=new&providers=accuweather&request_type=location'`
This should return weather suggestions:
`curl -i -X 'GET' 'localhost:8000/api/v1/suggest?q=&providers=accuweather&request_type=weather'`
This should also return weather suggestions:
`curl -i -X 'GET' …
> [DISCO-2806]: Add location completion via accuweather api

- merino/providers/weather/backends/accuweather.py
JIRA: [DISCO-2838](https://mozilla-hub.atlassian.net/browse/DISCO-2838)
Added the `alias` param for the cities accuweather endpoint.
[DISCO-2838]: https://mozilla-hub.atlassian.net/browse/DISCO-2838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2838] Add alias param for accuweather city endpoint

- merino/jobs/amo_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/chunked_rs_uploader.py
- merino/jobs/relevancy_uploader/__init__.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- merino/jobs/utils/chunked_rs_uploader.py
- tests/unit/jobs/amo_rs_uploader/test_amo_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/utils.py
- tests/unit/jobs/relevancy_uploader/test_chunked_relevancy_rs_uploader.py
- tests/unit/jobs/relevancy_uploader/utils.py
- tests/unit/jobs/utils/test_chunked_rs_uploader.py
JIRA: [DISCO-2794](https://mozilla-hub.atlassian.net/browse/DISCO-2794)
I took out the common components of the uploader job and kept them in `merino/jobs/utils/chunked_rs_uploader.py`.
Added a `ChunkedRemoteSettingsSuggestionUploader` class that has the extra fallback score field and the `add_suggestion` logic
[DISCO-2794]: https://mozilla-hub.atlassian.net/browse/DISCO-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2794] RS job refactor

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2843](https://mozilla-hub.atlassian.net/browse/DISCO-2843)
Current implementation assumes that there is only one entry in the response from Accuweather's city look up API.
This isn't always the case, and when there is more than one entry, Merino currently returns None rather than the first entry of the response, which is the highest ranked entry.
[DISCO-2843]: https://mozilla-hub.atlassian.net/browse/DISCO-2843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2843] Accuweather - Handle case when there are multiple location keys for a given city

- merino/jobs/csv_rs_uploader/base.py
- merino/jobs/csv_rs_uploader/mdn.py
- merino/jobs/csv_rs_uploader/pocket.py
- tests/unit/jobs/csv_rs_uploader/model.py
Trying my hand at a Merino PR, how does this one look?
This doesn't match all of the contribution guidelines, but it seems like those aren't being strictly followed based on the latest PRs in the queue.  Is there something important I'm missing?
_validate_str and _validate_keywords were logically class methods, but without the @classmethod decorator which lead to them being called in a non-standard way.
> Fix: Validate class methods

- merino/configs/default.toml
- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/base.py
- merino/jobs/csv_rs_uploader/fakespot.py
- tests/unit/jobs/csv_rs_uploader/test_fakespot.py
Putting this one up for early review.  I haven't gotten this to successfully run because of issues with the schema for the fakespot collection.  I filed a bugzilla ticket for that, hopefully we can get it sorted out soon.
JIRA: [DISCO-2834](https://mozilla-hub.atlassian.net/browse/DISCO-2834)
Added fakespot model to `csv_rs_uploader.
Reworked `csv_rs_uploader` so that models can specify their own default collection.  The fakespot data is going to live in a different collection and I didn't want to rely on users always typing that into the CLI.
[DISCO-2834]: https://mozilla-hub.atlassian.net/browse/DISCO-2834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2834] Fakespot upload job

- merino/curated_recommendations/__init__.py
- merino/curated_recommendations/corpus_backends/__init__.py
- merino/curated_recommendations/corpus_backends/fake_backends.py
- merino/curated_recommendations/corpus_backends/protocol.py
- merino/curated_recommendations/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/curated_recommendations/__init__.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1100](https://mozilla-hub.atlassian.net/browse/MC-1100)
This is the first step in moving the endpoint for New Tab curated recommendations to Merino. As outlined in the [Merino migration tech spec](https://mozilla-hub.atlassian.net/wiki/spaces/MozSocial/pages/726466605/New+Tab+Merino+migration), our objectives are to consolidate, improve scalability, and support topic preferences.
[MC-1100]: https://mozilla-hub.atlassian.net/browse/MC-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1100] feat: add curated-recommendations endpoint

- merino/configs/default.toml
- merino/jobs/amo_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/relevancy_uploader/__init__.py
- tests/unit/jobs/amo_rs_uploader/test_amo_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/test_csv_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/utils.py
- tests/unit/jobs/relevancy_uploader/test_relevancy_csv_uploader.py
- tests/unit/jobs/relevancy_uploader/utils.py
JIRA: [DISCO-2850](https://mozilla-hub.atlassian.net/browse/DISCO-2850)
fixes #531 
It was confusing when we had  `--delete-existing-records`, since when you add flag to the command line it will toggle the value and turn it to False, which isn't what we want...
Renamed it to `keep-existing-records` with a default to false instead
[DISCO-2850]: https://mozilla-hub.atlassian.net/browse/DISCO-2850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2850] Fix option to delete records for jobs

- merino/jobs/csv_rs_uploader/base.py
- merino/jobs/csv_rs_uploader/fakespot.py
- merino/jobs/csv_rs_uploader/row_major_base.py
- merino/jobs/csv_rs_uploader/yelp.py
- merino/utils/blocklists.py
- tests/unit/jobs/csv_rs_uploader/test_fakespot.py
Added code in the fakespot model to filter out items based on a blocklist.
Changed the signature of `csv_to_suggestions` to return `list[typing.Self]`.  I think this is more correct since the method should return instances of the subclass.  It's also needed to prevent lint errors.
It's possible we end up using a different system for the experiment, but this was easy to implement so I figured we might as well just do it.  If we need  to throw away the code later, it's fine.
> [DISCO-2833] Fakespot blocklists

- .pre-commit-config.yaml
JIRA: [DISCO-2165](https://mozilla-hub.atlassian.net/jira/software/c/projects/DISCO/boards/301?selectedIssue=DISCO-2165)
Leftover from removing `black`. It was still being used in the `pre-commit` hook.
[DISCO-2165]: https://mozilla-hub.atlassian.net/browse/DISCO-2165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-2165: remove black from pre-commit hook

- .pre-commit-config.yaml
- docs/data.md
- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2846](https://mozilla-hub.atlassian.net/jira/software/c/projects/DISCO/boards/301?selectedIssue=DISCO-2846)
We want to report `TTL` misses when trying to get the weather results from the cache. So far, we just report `None` if [Redis returns `-1` or `-2`:](https://redis.io/docs/latest/commands/ttl/)
```md
* The command returns -2 if the key does not exist.
* The command returns -1 if the key exists but has no associated expire.
```
We will report now if we hit or miss a `TTL`:
```python
self.metrics_client.increment(
"accuweather.cache.hit.ttl" if ttl else "accuweather.cache.fetch.miss.ttl"
)
```
Needs to be reviewed by someone who has experience with the Redis cache. I am not sure if, from a business point of view, we want to report on every TTL hit, or if we want to adjust …
> DISCO-2846: report ttl misses to metrics

- docs/data.md
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/provider.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-2858](https://mozilla-hub.atlassian.net/jira/software/c/projects/DISCO/boards/301?selectedIssue=DISCO-2858)
From Jira:
> The warning Country and/or region/city unknown is dominating the warning logs of Merino and making log consumption noisy. We can replace it with a metric (e.g. a counter) to mitigate that.
This PR removes the `raise AccuweatherError("Country and/or region/city unknown")` and instead adds a new counter called `accuweather.request.location.not_provided`. It increments each time a query for fetching a weather report was made without a proper city or country code. 
[DISCO-2858]: https://mozilla-hub.atlassian.net/browse/DISCO-2858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: increase counter instead of logging warning

- tests/integration/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2324](https://mozilla-hub.atlassian.net/browse/DISCO-2324)
Fixing asserts on two tests that I missed due to not rebasing on `main` branch in this [pull request](https://github.com/mozilla-services/merino-py/pull/545)
[DISCO-2324]: https://mozilla-hub.atlassian.net/browse/DISCO-2324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [load test: warn] fix failing redis accuweather integration tests

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_corpus_api_backend.py
JIRA: [MC-1208](https://mozilla-hub.atlassian.net/browse/MC-1208)
Guarantee reliability of the Pocket Graph and Merino, even when Merino will be handling thousands of requests per second for curated recommendations. This isn't an issue today, because a CDN sits in front of the firefox-proxy-api to cache and [coalesce requests](https://cloud.google.com/cdn/docs/caching#request-coalescing).
1. The curated corpus api should be guarded against high request volumes. The [ScheduledSurface query](https://studio.apollographql.com/graph/pocket-client-api/variant/current/insights?insightsTab=operations&operationSearch=scheduledsurf&operationsPage=0&query=31f1c92b1287f1f5a8d9b85f4d6806f5ac85d91a&queryName=ScheduledSurface) currently handles 90 requests/min, and Merino shouldn't send it much more …
> [MC-1208] feat: add caching to CorpusApiBackend

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- tests/unit/curated_recommendations/test_corpus_api_backend.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1199
The date for requesting curated recs is supposed to progress at 3am local time, where 'local time' is based on the timezone associated with the scheduled surface. Ported `get_surface_timezone` from recs-api & changed it to return a `ZoneInfo` obj instead of `pytz.timezone` so that we don't need to install the new package.
> MC-1199: curated-recs: map UTC date to scheduled date for timezone

- docs/operations/testfailures.md
- docs/testing/load-tests.md
JIRA: [DISCO-2883](https://mozilla-hub.atlassian.net/browse/DISCO-2883)
- update the documentation to distinguish between the manual and CI processes for execution of distributed load tests  
[DISCO-2883]: https://mozilla-hub.atlassian.net/browse/DISCO-2883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2883] Add 'Distributed GCP Execution - CI Trigger' section to load-test.md

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-142](https://mozilla-hub.atlassian.net/browse/HNT-142)
The curated-recs endpoint should accept a list of topics.
[HNT-142]: https://mozilla-hub.atlassian.net/browse/HNT-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [hnt-142] feat: curated-recs endpoint accepts topics

- merino/web/api_v1.py
JIRA: [MC-1309](https://mozilla-hub.atlassian.net/browse/MC-1309)
Fix the description in the [API documentation](https://merino.services.mozilla.com/docs#/) for the curated-recommendation endpoint.
Currently the topics parameter is missing:
[MC-1309]: https://mozilla-hub.atlassian.net/browse/MC-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1309] fix: curated-recommendations body description

- merino/curated_recommendations/provider.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: [MC-1200](https://mozilla-hub.atlassian.net/browse/MC-1200)
Implement publisher spread algorithm in curated recommendations. This is a slightly modified copy of the [same functionality existing in Recommendation API](https://github.com/Pocket/recommendation-api/blob/main/app/rankers/algorithms.py#L183-L207) (the legacy API that serves recommendations to Firefox).
[MC-1200]: https://mozilla-hub.atlassian.net/browse/MC-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1200] feat: add publisher spread to curated recommendations provider

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2857](https://mozilla-hub.atlassian.net/browse/DISCO-2857)
We're getting lots of warnings for unexpected forecast, current condition and location responses.
To aid in this investigation, added more context to logs and error messages.
I can see these changes may or may not be annoying, can and will refine/remove with bug fixes that will follow with the investigation.
[DISCO-2857]: https://mozilla-hub.atlassian.net/browse/DISCO-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2857] Enhance accuweather logs and error message

- merino/middleware/geolocation.py
- tests/unit/middleware/test_geolocation.py
JIRA: [DISCO-2889](https://mozilla-hub.atlassian.net/browse/DISCO-2889)
We have city names given by maxmind db like La’ie , ’Aiea, Kīhei, Querétaro, accuweather isn't able to handle them, so we should normalize them
[DISCO-2889]: https://mozilla-hub.atlassian.net/browse/DISCO-2889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2889]: Normalize geolocation city name

- docs/data.md
- docs/intro.md
- merino/curated_recommendations/__init__.py
- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1229](https://mozilla-hub.atlassian.net/browse/MC-1229)
Graphana: [Merino Curated Recommendations dashboard](https://earthangel-b40313e5.influxcloud.net/d/nqIyrq_Sk/merino-py-curated-recommendations?orgId=1&var-environment=stagepy&var-canary=All&from=1721076381565&to=1721077470717)
Create a Graphana dashboard for the curated-recommendations endpoint, to be used in addition to the [existing Merino dashboard](https://earthangel-b40313e5.influxcloud.net/d/rQAfYKIVk/merino-py-application-and-infrastructure?orgId=1&refresh=1m). We want to start simple with metrics that are essential for monitoring after the roll-out to release, and for analyzing a load test.
I think the following are essential:
- Endpoint latency (p50, p95, p99)
- Endpoint status codes
- Curated-corpus-api latency …
> [load test: warn] [MC-1229] feat: add metrics to curated-recommendations

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- tests/data/scheduled_surface.json
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_corpus_api_backend.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1212
Adding `utm_source` param to the curated rec url returned from corpus API. Adding a new one or replacing existing one. Created a `SCHEDULED_SURFACE_ID_TO_UTM_SOURCE` dict to map to the appropriate `utm_source`. Using `urllib.parse` to add/replace `utm_source` in a url.
> [MC-212] feat: Adding utm_source param to curated rec url

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: [MC-1352](https://mozilla-hub.atlassian.net/browse/MC-1352)
We've decided to keep emitting tileId to de-risk maintaining existing Mode reports that rely on tile_id.
[MC-1352]: https://mozilla-hub.atlassian.net/browse/MC-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [load test: warn] [MC-1352] feat: add tileId to curated-recommendations

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2857](https://mozilla-hub.atlassian.net/browse/DISCO-2857)
We're still seeing spikes in not being able to retrieve a non empty
[DISCO-2857]: https://mozilla-hub.atlassian.net/browse/DISCO-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2857] Introduce more logs for accuweather debugging

- docs/data.md
- merino/cron.py
- merino/curated_recommendations/engagement_backends/__init__.py
- merino/curated_recommendations/engagement_backends/gcs_engagement.py
- merino/curated_recommendations/engagement_backends/protocol.py
- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
- PR JIRA task: [MC-1294](https://mozilla-hub.atlassian.net/browse/MC-1294)
- JIRA story: [MC-1256](https://mozilla-hub.atlassian.net/browse/MC-1256)
- [GCP Blob class documentation](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_reload)
- staging bucket (empty): [merino-airflow-data-stagepy ](https://console.cloud.google.com/storage/browser/merino-airflow-data-stagepy;tab=objects?forceOnBucketsSortingFiltering=true&project=moz-fx-merino-nonprod-ee93&prefix=&forceOnObjectsSortingFiltering=false)
- production bucket (empty): [merino-airflow-data-prodpy ](https://console.cloud.google.com/storage/browser/merino-airflow-data-prodpy;tab=objects?forceOnBucketsSortingFiltering=true&project=moz-fx-merino-prod-1c2f&prefix= …
> [MC-1294] feat: add GcsEngagement to get aggregate clicks & impressions

- merino/jobs/relevancy_uploader/__init__.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- tests/unit/jobs/relevancy_uploader/utils.py
JIRA: [DISCO-2908](https://mozilla-hub.atlassian.net/browse/DISCO-2908)
Delete logic wasn't correct, `version` was 1 level deeper.
Current behaviour is that we delete per category, but that doesn't work when a new upload doesn't include a preexisting category, those records would stay in the collection
[DISCO-2908]: https://mozilla-hub.atlassian.net/browse/DISCO-2908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2908] fix: relevancy uploader to delete records before upload

- Dockerfile
JIRA: [DISCO-2881](https://mozilla-hub.atlassian.net/browse/DISCO-2881)
Using the `uv` rust based [package](https://pypi.org/project/uv/) to resolve and install project dependencies to improve CI times.
[DISCO-2881]: https://mozilla-hub.atlassian.net/browse/DISCO-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2881] use uv package to install project dependencies

- merino/configs/default.toml
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
JIRA: [DISCO-2913](https://mozilla-hub.atlassian.net/browse/DISCO-2913)
We need to handle accuweather location completion request errors. There has been a sudden uptick in the `ConnectTimeout` errors when trying to request the location autocomplete endpoint of accuweather. We are also increasing the connect timeout for its http client.
[DISCO-2913]: https://mozilla-hub.atlassian.net/browse/DISCO-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2913] Handle accuweather location completion errors

- merino/providers/weather/backends/accuweather.py
JIRA: [DISCO-2913](https://mozilla-hub.atlassian.net/browse/DISCO-2913)
Patching the previously merged PR, replacing the generic `Exception` class with `httpx.HTTPError` class.
[DISCO-2913]: https://mozilla-hub.atlassian.net/browse/DISCO-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2913] Catch for httpx.HTTPError instead of Exception for location completion request

- merino/jobs/relevancy_uploader/__init__.py
- tests/unit/jobs/relevancy_uploader/test_relevancy_csv_uploader.py
- tests/unit/jobs/relevancy_uploader/test_relevancy_data.csv
- tests/unit/jobs/relevancy_uploader/utils.py
JIRA: [DISCO-2823](https://mozilla-hub.atlassian.net/browse/DISCO-2823)
Uploaded new mapping into Remote Settings Dev 🙂 
I think there's something funny with deleting existing records, will investigate as a diff issue.
Instead of using our own mapping of categories, allow the job to use a mapping json file of categories to domains instead.
[DISCO-2823]: https://mozilla-hub.atlassian.net/browse/DISCO-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2823] Refine Inconclusive interest data

- merino/providers/weather/backends/accuweather.py
- tests/integration/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2785](https://mozilla-hub.atlassian.net/browse/DISCO-2785)
- Refactoring the Lua script to conditionally get the TTLs only if both keys exist. 
- Removing an invalid test since that use case is not applicable (see comment below).
- Minor tests refactor to use more accurate TTL values for different entities.
[DISCO-2785]: https://mozilla-hub.atlassian.net/browse/DISCO-2785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2785]: Refactor lua script to fetch ttl only when both keys exist

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2914](https://mozilla-hub.atlassian.net/browse/DISCO-2914)
There was sudden spike in these [Sentry errors](https://mozilla.sentry.io/issues/5648007025/?environment=prod&project=6622434&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0&utc=true) last week. This is due to Accuweather returning a successful response for location completion but with an _**invalid shape**_. We are adding some defensive logic here to handle it gracefully.
[DISCO-2914]: https://mozilla-hub.atlassian.net/browse/DISCO-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2914]: Handle location completion empty request responses

- tests/load/Dockerfile
JIRA: [DISCO-2939](https://mozilla-hub.atlassian.net/browse/DISCO-2939)
The load tests aren't executing as expected in CI with the changes made in DISCO-2904. This reverts the Dockerfile change.
[DISCO-2939]: https://mozilla-hub.atlassian.net/browse/DISCO-2939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2939] fix(load-tests): revert CMD to ENTRYPOINT change in the Dockerfile [load test: warn]

- Makefile
- docs/testing/load-tests.md
- tests/load/Dockerfile
- tests/load/locustfiles/average_load.py
- tests/load/locustfiles/smoke_load.py
JIRA: [DISCO-2939](https://mozilla-hub.atlassian.net/browse/DISCO-2939)
- Have the load test Docker image entrypoint include all locust files
- Update the Makefile to use 'docker compose' instead of 'docker-compose'
- Add documentation for location of CD load test command
- Update load test shapes to use 5 users per worker (6 was causing some CPU warnings)
Note the command was changed in the Jenkins file here: https://github.com/mozilla-services/cloudops-infra/pull/5835 
[DISCO-2939]: https://mozilla-hub.atlassian.net/browse/DISCO-2939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(load-tests): entrypoint to include all locustfiles and Makefile docker compose commands

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2951](https://mozilla-hub.atlassian.net/browse/DISCO-2951)
Fix the `emit_cache_fetch_metrics` function to emit ttl cache miss metric only when `current conditions` and `forecast` are not None but `ttl` is `None`
[DISCO-2951]: https://mozilla-hub.atlassian.net/browse/DISCO-2951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2951]: Investigate ttl cache miss high count

- docs/data.md
- merino/configs/default.toml
- merino/metrics.py
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather/backend.py
- tests/integration/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2940](https://mozilla-hub.atlassian.net/browse/DISCO-2940)
Adding sampling for some of the accuweather metrics at 90% (0.9)
Verifying that metrics are being emitted with the correct sample rate value. Notice the `@0.9`
```
// location key exists but forecast and current conditions expired
merino.accuweather.cache.fetch:4|ms|@0.9|
merino.accuweather.cache.hit.locations:1|c|@0.9|
merino.accuweather.cache.fetch.miss.currentconditions:1|c|@0.9|
merino.accuweather.cache.fetch.miss.forecasts:1|c|@0.9|
merino.accuweather.request.forecasts.get:322|ms|@0.9|
merino.accuweather.cache.store:6|ms|@0.9|
merino.accuweather.request.currentconditions.get:780|ms|@0.9|
merino.accuweather.cache.store:6|ms|@0.9|
// location key, forecast and current conditions all exist …
```
> [DISCO-2940]: Implement sampling for accuweather metrics

- merino/configs/default.toml
JIRA: [DISCO-2964]https://mozilla-hub.atlassian.net/browse/DISCO-2964)
Lowering sampling rate to 75%
[DISCO-2964]: https://mozilla-hub.atlassian.net/browse/DISCO-2964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2964]: Lower accuweather metrics sampling to 75 percent

- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
JIRA: [MC-1452](https://mozilla-hub.atlassian.net/browse/MC-1452)
Disable a [failing test test_gcs_engagement_logs_error_for_large_blob](https://app.circleci.com/pipelines/github/mozilla-services/merino-py/3225/workflows/7836c25d-4ffd-4980-abd2-d416028f4398/jobs/21662) to unblock deployment.
```
>       assert "Curated recommendations engagement size 1000003 exceeds 1000000" in caplog.text
E       AssertionError: assert 'Curated recommendations engagement size 1000003 exceeds 1000000' in ''
E        +  where '' = <_pytest.logging.LogCaptureFixture object at 0x7f6dd2a01c40>.text
```
- Test passes successfully 100 times locally
- Test passed successfully in pr-workflow, at least 4 times
- I don't see why a different environment causes this to fail. The `max_size` setting only has a default …
> [MC-1452] fix(curated-recommendations): disable failing test [load test: warn]

- merino/jobs/utils/chunked_rs_uploader.py
Avoid crashing when an existing record does not have a `type` field.
JIRA: [DISCO-2963](https://mozilla-hub.atlassian.net/browse/DISCO-2963)
[DISCO-2963]: https://mozilla-hub.atlassian.net/browse/DISCO-2963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2963] Fix type KeyErrors

- merino/configs/default.toml
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather/pathfinder.py
- merino/providers/weather/provider.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-2962](https://mozilla-hub.atlassian.net/browse/DISCO-2962)
We have a look up map to help with retrieving the correct region for a given city, made changes so we can see the size of the map periodically. Debated whether we should log the contents of the map, but decided to hold off, until we look at the size?
[DISCO-2962]: https://mozilla-hub.atlassian.net/browse/DISCO-2962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2962] - Add cron job to gauge size of the region look up map

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- [MC-1439](https://mozilla-hub.atlassian.net/browse/MC-1439): As [a workaround](https://mozilla.slack.com/archives/C06TBL1E1PD/p1724768971239179), we agreed with Firefox FE (Scott) that we will not emit topics for markets other than New Tab en-US, because we are not confident topic labels are localized correctly in Fx130, and we only need to experiment with them in English locales. I believe there was a concern about feature whiplash if this were to be solved in Nimbus through audience targeting, and that the underlying issue causing feature whiplash has been solved starting from Fx131. (But I have to admit it's a bit out of my wheelhouse.)
- [MC-1474](https://mozilla-hub.atlassian.net/browse/MC-1474): receivedRank must be 0, 1, 2, ... in the response. This was a bug.
_Put an `x` in the …
> [MC-1439][MC-1474] fix(curated-recommendations): fix topic and receivedRank

- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/chunked_rs_uploader.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- merino/jobs/utils/chunked_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/utils.py
- tests/unit/jobs/utils/test_chunked_rs_uploader.py
JIRA: [DISCO-2967](https://mozilla-hub.atlassian.net/browse/DISCO-2967)
Added the `--allow-delete` flag.  If it's not present, don't allow records to be deleted.  See
https://bugzilla.mozilla.org/show_bug.cgi?id=1908802 for details.  I turned off the flag for relevancy updates, because the bug only affects Suggest.
Refactored the CSV uploader so that it records changes it's going to make and executes them at the end.  This is needed to correctly determine if there's a deletion. The current pattern is to delete all records, then update ones from the CSV data -- undoing the delete.
[DISCO-2967]: https://mozilla-hub.atlassian.net/browse/DISCO-2967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2967] deleting records error + CLI flag

- merino/jobs/relevancy_uploader/__init__.py
- tests/unit/jobs/relevancy_uploader/test_relevancy_csv_uploader.py
- tests/unit/jobs/relevancy_uploader/test_relevancy_data.csv
JIRA: [DISCO-2824](https://mozilla-hub.atlassian.net/browse/DISCO-2824)
Remove fallback categorization logic for r2d2 upload job, as the number of domains it categorized is minimal and the categorization isn't accurate
[DISCO-2824]: https://mozilla-hub.atlassian.net/browse/DISCO-2824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2824] R2D2 job: Remove fallback categorization logic

- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
Forgot to remove the repeat param to run a test 20 times in this recent PR: https://github.com/mozilla-services/merino-py/pull/619
> MC-1462: remove repeat param to run gcs tests 20 times

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/curated_recommendations/rankers.py
- tests/data/scheduled_surface_short.json
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1432
Return a 200 OK content feed even if server receives an unknown or invalid preferred topics. If multiple preferred topics passed, ignore invalid ones (treat as blank) & return feed based on valid topics (if present). 
Set `topics` param to `Optional[list[Topic | str]] = None` to accommodate for invalid `str` topics. Using pydantics `@field_validator` to run a `validate_topics` on `topics`.
> MC-1432: return 200 (ok) feed for unknown / invalid topics

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/utils.py
- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2975](https://mozilla-hub.atlassian.net/browse/DISCO-2975)
Added a new and separate **count** metric to correctly represent and track upstream requests made to accuweather. Before that, we were piggy backing the `timeit()` metric for request latency to count the no. of requests but since we are sampling that metric, the count accuracy is also affected. This change fixes that.
Also tested locally and verified that the new metric is emitted.
[DISCO-2975]: https://mozilla-hub.atlassian.net/browse/DISCO-2975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2975] Add count metric for upstream accuweather requests

- poetry.lock
JIRA: N/A
This fixes https://github.com/mozilla-services/merino-py/security/dependabot/104.
> chore: Update cryptography for CWE-1395

- merino/providers/weather/provider.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-2896](https://mozilla-hub.atlassian.net/browse/DISCO-2896)
related PR: https://github.com/mozilla-services/merino-py/pull/569 
For the suggest endpoint,  we need to return a http 400 error when `q` query param has a value but `request_type` query param is missing. 
These query param combinations work (as expected)
`... suggest?q=&providers=accuweather`
`... suggest?q=&providers=accuweather&request_type=weather`
`... suggest?q=&providers=accuweather&request_type=location`
`... suggest?q=new&providers=accuweather&request_type=location`
This query param combination does not work (as expected)
`... suggest?q=weather&providers=accuweather`
[DISCO-2896]: https://mozilla-hub.atlassian.net/browse/DISCO-2896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> [DISCO-2896] Suggest endpoint query param validation

- merino/curated_recommendations/engagement_backends/fake_engagement.py
- merino/curated_recommendations/engagement_backends/gcs_engagement.py
- merino/curated_recommendations/engagement_backends/protocol.py
- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1459](https://mozilla-hub.atlassian.net/browse/MC-1459)
We want to experiment with ranking New Tab recommendations differently by region, after a successful experiment in Canada in recommendation-api.
This PR takes the first step, by allowing engagement to be loaded from different regions. This data does not exist yet, so the code can to read data _with_ and _without_ the `region` field present.
[MC-1459]: https://mozilla-hub.atlassian.net/browse/MC-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [MC-1459] Load engagement by region

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1498
This is a prototype of an additional feed of curated corpus recommendations alongside the one already being sent to New Tab surfaces. If an optional parameter (`"feeds": ["need_to_know"]`) is requested with the API call, the new feed of 5-10 items (10 for the current prototype with semi-mocked data) is returned. 
The shape of the API response becomes the following:
```
{
recommendedAt: int
data: recommendation[]
feeds: {
need_to_know: {
recommendations: recommendation[],
title: string // localized based on locale value sent in request
}
}
}
```
The full spec is available at https://mozilla-hub.atlassian.net/wiki/spaces/FPS/pages/975110262/API+Technical+Specification.
> feat(curated recommendations): [MC-1498] Prototype support for contextual content experiments [load test: warn]

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/curated_recommendations/rankers.py
- merino/web/api_v1.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1518](https://mozilla-hub.atlassian.net/browse/MC-1518)
[Experiment brief](https://docs.google.com/document/d/1YaZYPZ-ZR06_9XdNcm27KUDSvGi9hl_51G0vp6ol-Uk/edit) (in progress of being drafted)
Building on https://github.com/mozilla-services/merino-py/pull/633, this PR uses regional engagement in Thompson sampling in the treatment branch of an experiment.
- [] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
[MC-1518]: https://mozilla-hub.atlassian.net/browse/MC-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1518] Rank using region engagement in experiment

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- merino/curated_recommendations/corpus_backends/protocol.py
- tests/data/scheduled_surface.json
- tests/data/scheduled_surface_short.json
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_provider.py
- tests/unit/curated_recommendations/test_rankers.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1520
Make incremental progress on the "Need to Know" prototype by adding the field we will be differentiating the data by, `isTimeSensitive`, to the GraphQL query that fetches curated recommendations.
- Added new field to the Curated Corpus Graphql query
- Updated CorpusItem and CorpusRecommendation classes
- Updated existing tests and sample test data
> feat(curated recommendations): [MC-1520] Add `isTimeSensitive` to corpus GraphQL query

- merino/curated_recommendations/provider.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1519
Implement review feedback from https://github.com/mozilla-services/merino-py/pull/629: 
- Split out processing for need-to-know recommendations into a separate method.
- Add unit tests for new `rank_need_to_know_recommendations` method.
> chore(curated recommendations): [MC-1519] Clean up need-to-know-prototype code

- merino/configs/testing.toml
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1473](https://mozilla-hub.atlassian.net/browse/MC-1473)
Fix a flaky test that failed in 3% of cases, due to Thompson sampling not ranking an item on top.
Also adds a config setting to make it easier to repeat tests which can be affected by Thompson sampling.
[MC-1473]: https://mozilla-hub.atlassian.net/browse/MC-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1473] fix flaky test due to Thompson sampling

- dev/top_picks_for_ci.json
- merino/providers/top_picks/backends/top_picks.py
- tests/data/top_picks.json
- tests/unit/providers/top_picks/test_provider.py
Forgot to account for cases where a top pick does not have a serp category associated to it 🙈 
> fix: handle case where top picks domain does not have serp categories

- merino/curated_recommendations/provider.py
- tests/data/scheduled_surface.json
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1521
Replace the current prototype code that builds the “need to know” feed with logic using isTimeSensitive.
- The `need_to_know` feed is now populated with time-sensitive items instead of the bottom 10 items from the general feed.
- The `receivedRank` values for items in the `need_to_know` feed now start at zero and are consecutive numbers - essentially these are array indexes, similar to the general feed with or without the new feed.
> [MC-1521] Use isTimeSensitive to populate Need to Know feed

- docs/data.md
- merino/providers/weather/backends/accuweather/backend.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-3008](https://mozilla-hub.atlassian.net/browse/DISCO-3008)
We no longer use the `accuweather.cache.fetch.miss.ttl` metric on Grafana so we are removing the emission
[DISCO-3008]: https://mozilla-hub.atlassian.net/browse/DISCO-3008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3008] remove unused accuweather metric emission

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1545](https://mozilla-hub.atlassian.net/browse/MC-1545)
[Slack thread](https://mozilla.slack.com/archives/CF94YGE03/p1727462074174769?thread_ts=1727457879.892819&cid=CF94YGE03) in #ask-experimenter, where I asked about the optin- prefix
Allow team members to force enroll in the region-specific ranking experiment, by accepting an 'optin-' prefix for the experiment name.
```
about:studies?optin_slug=new-tab-region-specific-content-expansion&optin_branch=treatment&optin_collection=nimbus-preview
```
[MC-1545]: https://mozilla-hub.atlassian.net/browse/MC-1545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1545] fix: allow optin- prefix before experiment name

- merino/configs/default.toml
- merino/configs/testing.toml
- merino/providers/amo/provider.py
- tests/integration/api/v1/suggest/test_suggest_amo.py
- tests/load/locustfiles/locustfile.py
- tests/unit/providers/test_init_providers.py
JIRA: [DISCO-2886](https://mozilla-hub.atlassian.net/browse/DISCO-2886)
We are disabling this provider (`amo`) since online users are not using it. Disabling this would also minimize Sentry errors.
[DISCO-2886]: https://mozilla-hub.atlassian.net/browse/DISCO-2886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2886] disable AMO provider

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1522
- Update placeholder "need to know" titles to the final copy: sentence-case "In the news".
- Update tests.
> [MC-1522] Provide localized titles for the Big Rectangle

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/errors.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-3023](https://mozilla-hub.atlassian.net/browse/DISCO-3023)
Refactoring out the accuweather backend error strings into a separate module for clarity, maintainability and flexibility.
[DISCO-3023]: https://mozilla-hub.atlassian.net/browse/DISCO-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3023] Refactor out and centralize accuweather error strings

- merino/curated_recommendations/provider.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1522
A very small update to capitalize the word "News" for the German copy of the "Big Rectangle" heading.
> [MC-1522] Update 'In the news' copy for German New Tab surface

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-226](https://mozilla-hub.atlassian.net/browse/HNT-226)
The client should not get more recommendations back than it requests.
[HNT-226]: https://mozilla-hub.atlassian.net/browse/HNT-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-266] Fix curated recommendation count

- merino/curated_recommendations/__init__.py
JIRA: [MC-1567](https://mozilla-hub.atlassian.net/browse/MC-1567)
Fix GcsEngagement failing to initialize because the wrong config is used:
> Failed to initialize GCS Engagement Backend: "'DynaBox' object has no attribute 'gcp_project'"
[MC-1567]: https://mozilla-hub.atlassian.net/browse/MC-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1567] Fix initialization of GcsEngagement

- merino/configs/default.toml
JIRA: [MC-1516](https://mozilla-hub.atlassian.net/browse/MC-1516)
Fix unhandled exception during starting, causing deployment to fail:
> dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'corpus_api'"
[MC-1516]: https://mozilla-hub.atlassian.net/browse/MC-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1568] fix config error for curated_recommendations

- merino/config.py
JIRA: [HNT-228](https://mozilla-hub.atlassian.net/browse/HNT-228)
Validate that required curated recommendations configs exist. This would have caught https://github.com/mozilla-services/merino-py/pull/656.
[HNT-228]: https://mozilla-hub.atlassian.net/browse/HNT-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-228] Validate curated recommendations configs

- docs/testing/load-tests.md
- tests/load/locustfiles/locustfile.py
JIRA: [DISCO-3010](https://mozilla-hub.atlassian.net/browse/DISCO-3010)
- update network traffic end point distribution from 50% suggest and 50% recommendations to 65% suggest and 35% recommendations
- add corrections and clarifications to documentation
For the latest load test results, please see the [Merino Load Test Spreadsheet](https://docs.google.com/spreadsheets/d/1SAO3QYIrbxDRxzmYIab-ebZXA1dF06W1lT4I1h2R3a8/edit?gid=0#gid=0)
In the end, no additional load was necessary, since scaling is still achieved with the configured load
The current load distribution between endpoints has proven to be slightly different than the original 50/50 estimate. So adjustments have been made as follows:
49.7% --> 64.2% weatherSuggestions
42.1% --> 29.8% curatedRecommendationsLocale
7.4% --> 5.2% …
> [DISCO-3010] Calibrate smoke and average tests for n2-highcpu-8 machine change and real-world network traffic data [load test: warn]

- merino/configs/default.toml
- merino/jobs/amo_rs_uploader/__init__.py
- merino/jobs/cli.py
- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/chunked_rs_uploader.py
- merino/jobs/geonames_uploader/__init__.py
- merino/jobs/geonames_uploader/downloader.py
- merino/jobs/geonames_uploader/tempzipfile.py
- merino/jobs/relevancy_uploader/__init__.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- merino/jobs/utils/chunked_rs_uploader.py
- tests/unit/jobs/amo_rs_uploader/test_amo_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/test_csv_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/utils.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
- tests/unit/jobs/geonames_uploader/test_geonames_uploader.py
- tests/unit/jobs/relevancy_uploader/test_chunked_relevancy_rs_uploader.py
- tests/unit/jobs/relevancy_uploader/utils.py
- tests/unit/jobs/utils/test_chunked_rs_uploader.py
Add a `geonames_uploader` job that downloads data from GeoNames, selects a set of geonames based on the config (like population size), and uploads the selected geonames to remote settings. This supports city-based weather queries on the client and lets the client recognize city and state names.
GeoNames is an open-source geographical database of place names worldwide, including cities, regions, and countries [1]. Technical documentation at [2].
This commit sets the population threshold to 50,000. That results in 1,013 geonames (U.S. cities and states) in the output, which results in 6 records when using the usual 200-items-per-attachment count. That seems reasonable.
[1] https://www.geonames.org/
[2] https://download.geonames.org/export/dump/readme.txt
JIRA: …
> feat: add geonames uploader SNG-1848

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1569](https://mozilla-hub.atlassian.net/browse/MC-1569)
When Data Science sized the regional ranking experiment, it was decided that we need separate experiments for small and large countries, to allow us to set a different enrollment %. This PR adds the experiment for smaller countries.
[MC-1569]: https://mozilla-hub.atlassian.net/browse/MC-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1569] fix regional ranking experiment names

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- merino/curated_recommendations/corpus_backends/protocol.py
- tests/integration/api/v1/curated_recommendations/conftest.py
- tests/integration/api/v1/curated_recommendations/corpus_backends/fixtures.py
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/integration/conftest.py
JIRA: [HNT-205](https://mozilla-hub.atlassian.net/browse/HNT-205)
Allow fetching of corpus items that were scheduled on previous days.
[HNT-205]: https://mozilla-hub.atlassian.net/browse/HNT-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-205] Allow content to be fetched by scheduled date

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1571](https://mozilla-hub.atlassian.net/browse/MC-1571)
waiting on final string...
Adds another UI string for the Fakespot feed - this one to denote the name displayed when all categories are shown (which is the default state).
[MC-1571]: https://mozilla-hub.atlassian.net/browse/MC-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1571] add defaultCategoryName to Fakespot feed

- merino/jobs/geonames_uploader/downloader.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
The suggest client expects geoname IDs to be ints, not strings. They are in fact ints in the GeoNames dataset.
> fix: make geoname IDs ints

- Makefile
- pyproject.toml
JIRA: N/A
Noticed the `source` of `tool.coverage.run` was mis-configured (although it will always be overridden if `--cov=merino` is specified w/ pytest). Fixing it to avoid confusion. Also moved `--cov=merino` to `tool.pytest.ini_options` so that folks can do `MERINO_ENV=testing pytest tests/unit or integration` w/o those CLI options.
> chore: Update configs for pytest-cov

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-242](https://mozilla-hub.atlassian.net/browse/HNT-242)
Return mock data for section feeds, to unblock front-end developers from starting to integrate the API. I don't know what content we'll actually launch with exactly, so I roughly based this work on [the Figma design](https://www.figma.com/design/VdghooQZTLiXYO8hF5pAuS/Feed?node-id=5358-17426&node-type=canvas&t=PWBqFJ8XsRE8ifQT-0).
We have some API details to iron out, but the high-level concept is that we'll return sections as feeds.
[HNT-242]: https://mozilla-hub.atlassian.net/browse/HNT-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-242] Mock section feeds

- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_prior.py
- tests/integration/api/v1/curated_recommendations/fakespot_backend/test_fakespot_backend.py
JIRA: N/A
Noticed those tests took quite a bit to run (by waiting). Dropped & tuned the excessive sleeping to speed them up by ~ 35% for the entire integration tests.
> chore(test): Speed up various integration tests

- merino/jobs/geonames_uploader/downloader.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
- tests/unit/jobs/geonames_uploader/test_geonames_uploader.py
JIRA: https://mozilla-hub.atlassian.net/browse/SNG-1901
Coordinates are stored as strings in remote settings, which seems safer than parsing and storing them as floats.
> feat: add coordinates to geonames uploader SNG-1901

- merino/configs/default.toml
- merino/jobs/geonames_uploader/__init__.py
- merino/jobs/geonames_uploader/downloader.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
- tests/unit/jobs/geonames_uploader/test_geonames_uploader.py
JIRA: https://mozilla-hub.atlassian.net/browse/SNG-1902
In the GeoNames data, U.S. states have verbose alternate names like "State of
California" that people are unlikely to type and that interfere with prefix
matching. The Merino uploader job should filter them out.
> fix: exclude verbose region names in geonames uploader SNG-1902

- merino/configs/default.toml
- merino/jobs/geonames_uploader/__init__.py
- merino/jobs/geonames_uploader/downloader.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
- tests/unit/jobs/geonames_uploader/test_geonames_uploader.py
JIRA: https://mozilla-hub.atlassian.net/browse/SNG-1904
There are only 116 Canadian cities above our population threshold of 50k.
Currently the final geonames record in RS only contains 13 items, so including
the CA cities doesn't even add another record to our dataset. Since there are
many Canadian Mozillians and there's little cost to including these cities, I'd
like to do that.
> feat: include Canadian cities in geonames uploader SNG-1904

- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py
- tests/unit/middleware/test_featureflags.py
- tests/unit/providers/adm/test_provider.py
- tests/unit/providers/amo/test_provider.py
- tests/unit/providers/top_picks/test_provider.py
- tests/unit/test_featureflags.py
JIRA: [DISCO-3049](https://mozilla-hub.atlassian.net/browse/DISCO-3049)
- ~add pytest-xdist in order to run unit tests in parallel~
- fix isolation issue in `test_favicon_downloader_handles_exception` by setting the logging level
- fix isolation issues in `test_normalize_query` by fixing parameterize syntax
- fix isolation issues in feature flag tests by resetting `session_id_context` between tests
[DISCO-3049]: https://mozilla-hub.atlassian.net/browse/DISCO-3049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3049] Fix isolation issues in unit tests

- merino/jobs/geonames_uploader/__init__.py
- merino/jobs/geonames_uploader/downloader.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
- tests/unit/jobs/geonames_uploader/test_geonames_uploader.py
[bug 1929167](https://bugzilla.mozilla.org/show_bug.cgi?id=1929167)
The Rust change in bug 1928544 (vendored today in bug 1929082) expects `alternate_names_2` to be present in each geoname object in the remote settings data. We need to modify the uploader to include it.
> feat: add alternate_names_2 to geonames uploader

- merino/jobs/geonames_uploader/downloader.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
[Bug 1929362 - Convert Canadian province admin1_code values to postal abbreviations in the Merino geonames uploader job](https://bugzilla.mozilla.org/show_bug.cgi?id=1929362)
> feat: replace Canadian admin1_codes - bug 1929362

- merino/utils/synced_gcs_blob.py
JIRA: [MC-1506](https://mozilla-hub.atlassian.net/browse/MC-1506)
[Slack thread](https://mozilla.slack.com/archives/G01M6ALKVL4/p1730747515881179)
Sentry errors get emitted in the staging environment, because there's no engagement data there. This is actually expected because bigquery-etl doesn't have a staging environment, and therefore only writes to production.
[MC-1506]: https://mozilla-hub.atlassian.net/browse/MC-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1506] don't error when blob is missing in staging

- .circleci/config.yml
- PULL_REQUEST_TEMPLATE.md
- docs/dev/release-process.md
- docs/testing/load-tests.md
**Follow-up to https://github.com/mozilla-services/merino-py/pull/681**
JIRA: [DISCO-3054](https://mozilla-hub.atlassian.net/browse/DISCO-3054)
- update the CircleCI config to trigger load tests by default and support load test opt-out
- update documentation accordingly
I tested this logic by encapsulating it in the following script and executing the following test cases:
./test_stage_docker_tag.sh
```
#!/bin/bash
CIRCLE_SHA1="dummysha123456"
COMMIT_MESSAGE=$1
LOAD_TEST_ACTION=$(echo "$COMMIT_MESSAGE" | sed -n 's/.*\[load test: \([^]]*\)\].*/\1/p')
if [ "$LOAD_TEST_ACTION" = "abort" ]; then
STAGE_DOCKER_TAG="stage-loadtest-abort-${CIRCLE_SHA1}"
elif [ "$LOAD_TEST_ACTION" = "skip" ]; then
STAGE_DOCKER_TAG="stage-${CIRCLE_SHA1}"
else
STAGE_DOCKER_TAG="stage-loadtest-warn-${CIRCLE_SHA1}"
fi …
```
> [DISCO-3054] Update CI load test strategy to opt-out

- .circleci/config.yml
JIRA: N/A
- fix the main CI, so that `docker-image-build` is pre-requisite to `docker-image-publish`
> fix(ci): make docker-image-build pre-requisite to docker-image-publish

- .circleci/config.yml
JIRA: [DISCO-3062](https://mozilla-hub.atlassian.net/browse/DISCO-3062)
- update the `docker-image-publish-locust` job to skip only if the `[load test: skip]` substring is provided in the latest commit message
I tested this by modifying the PR build, adding the `docker-image-publish-locust` job temporarily:
Case 1: No Skip --> [CI](https://app.circleci.com/pipelines/github/mozilla-services/merino-py/3695/workflows/1bc8431c-b0a3-4d3d-a5ba-5fa967d78ba0) & [Dockerhub](https://hub.docker.com/r/mozilla/merino-py/tags)
Case 2: Skip --> [CI](https://app.circleci.com/pipelines/github/mozilla-services/merino-py/3696/workflows/80716e02-271a-4167-a785-f79f247b1930)
[DISCO-3062]: https://mozilla-hub.atlassian.net/browse/DISCO-3062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
> [DISCO-3062] Fix merino-locust docker image isn't publishing when load tests are triggered by default

- merino/curated_recommendations/protocol.py
JIRA: [HNT-249](https://mozilla-hub.atlassian.net/browse/HNT-249)
Set the slug to the one chosen in the [Nimbus experiment](https://experimenter.services.mozilla.com/nimbus/new-tab-extend-content-duration/summary): `new-tab-extend-content-duration`.
[HNT-249]: https://mozilla-hub.atlassian.net/browse/HNT-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-249] fix content duration Nimbus slug

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/pathfinder.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- tests/integration/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-3005](https://mozilla-hub.atlassian.net/browse/DISCO-3005)
Passed along the language header to weather report logic to be able to retrieve, current conditions and forecast in different languages.
[DISCO-3005]: https://mozilla-hub.atlassian.net/browse/DISCO-3005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3005] Pass Language to weather report logic

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/relevancy_uploader/__init__.py
- merino/jobs/utils/domain_category_mapping.py
JIRA: [DISCO-3036](https://mozilla-hub.atlassian.net/browse/DISCO-3036)
Since we have the mapping file in merino already, there's no need to have the job ask for a category mapping file. It also simplifies the logic as well.
[DISCO-3036]: https://mozilla-hub.atlassian.net/browse/DISCO-3036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3036] refactor: r2d2 job to use domain mapping file

- merino/curated_recommendations/layouts.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- JIRA: [HNT-251](https://mozilla-hub.atlassian.net/browse/HNT-251)
- [API spec](https://mozilla-hub.atlassian.net/wiki/spaces/FPS/pages/1078231077/Sections+Phase+1+-+API+Technical+Specification)
- [the Figma designs](https://www.figma.com/design/VdghooQZTLiXYO8hF5pAuS/Feed?node-id=5358-17426&node-type=canvas&t=PWBqFJ8XsRE8ifQT-0)
Unblock front-end development by sending layout data for sections. Sections is under active development, so layouts and layout names are likely to change.
[HNT-251]: https://mozilla-hub.atlassian.net/browse/HNT-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-251] add layouts to sections

- merino/curated_recommendations/layouts.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
JIRA: [HNT-258](https://mozilla-hub.atlassian.net/browse/HNT-258)
Update the layouts to match the first 3 layouts from [the latest design](https://www.figma.com/design/VdghooQZTLiXYO8hF5pAuS/Feed?node-id=6259-53439&node-type=canvas&t=c3sqxcbdFWLfnN6B-0).
Additional changes:
- add validation on `hasAd`, `hasExcerpt`, `position`, and `columnCount`
- change the minimum number of recommendations to be 1 more than the number of tiles
[HNT-258]: https://mozilla-hub.atlassian.net/browse/HNT-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-258] fix: layouts match design

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/utils.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/integration/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-3069](https://mozilla-hub.atlassian.net/browse/DISCO-3069)
- This PR adds region code to the weather suggestion response
[DISCO-3069]: https://mozilla-hub.atlassian.net/browse/DISCO-3069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3069] add region code to weather response

- merino/utils/synced_gcs_blob.py
- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
JIRA: [MC-1506](https://mozilla-hub.atlassian.net/browse/MC-1506)
Previous attempt: https://github.com/mozilla-services/merino-py/pull/692
Don't log an error if engagement data does not exist on staging. In the Kubernetes console, I confirmed that the [environment string is "stage"](https://console.cloud.google.com/kubernetes/configmap/us-west1/merino-nonprod-v1/stagepy-merino/merinopy-stagepy-merino-app-1/details?project=moz-fx-merino-nonprod-ee93) as opposed to "staging".
[MC-1506]: https://mozilla-hub.atlassian.net/browse/MC-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1506] fix: don't log missing blob error on stage

- merino/providers/weather/backends/accuweather/backend.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-3072](https://mozilla-hub.atlassian.net/browse/DISCO-3072)
The structure of the accuweather cached data was updated in https://github.com/mozilla-services/merino-py/pull/708 to add a new field for the region code (`administrative_area_id`). This caused [validation errors](https://mozilla.sentry.io/issues/6065590782/?project=6622434&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0) on sentry because the cache key version was not updated. This PR bumps the version so this should hopefully clear the error.
[DISCO-3072]: https://mozilla-hub.atlassian.net/browse/DISCO-3072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3072] bump accuweather cache key version

- pyproject.toml
JIRA: [DISCO-3080](https://mozilla-hub.atlassian.net/browse/DISCO-3080)
When [refactoring](https://github.com/mozilla-services/merino-py/pull/702), I forgot to update the paths in `pyproject.toml`
[DISCO-3080]: https://mozilla-hub.atlassian.net/browse/DISCO-3080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3080] fix: update domain mapping file path for bandit exclusion

- merino/providers/weather/backends/accuweather/pathfinder.py
- tests/unit/providers/weather/backends/test_pathfinder.py
JIRA: [DISCO-3090](https://mozilla-hub.atlassian.net/browse/DISCO-3090)
Some city names that maxminddb returns aren't spelled/formatted how accuweather expects it. With these corrections, those cities should not be creating warning logs anymore.
[DISCO-3090]: https://mozilla-hub.atlassian.net/browse/DISCO-3090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3090] weather: added city name correction mapping

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- merino/curated_recommendations/corpus_backends/protocol.py
- tests/data/scheduled_surface.json
- tests/data/scheduled_surface_short.json
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_provider.py
- tests/unit/curated_recommendations/test_rankers.py
JIRA: [HNT-273](https://mozilla-hub.atlassian.net/browse/HNT-273)
The curated-recommendations endpoint responds with the `corpusItemId`, such that Firefox New Tab can emit this identifier with engagement telemetry.
I have left making `scheduledCorpusItemId` nullable out-of-scope for this PR, because it's a breaking change that all clients should sign-off on, even though they're not directly impacted by the experiment.
[HNT-273]: https://mozilla-hub.atlassian.net/browse/HNT-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-273] response includes corpusItemId

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/pathfinder.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/backends/test_pathfinder.py
JIRA: [DISCO-3086](https://mozilla-hub.atlassian.net/browse/DISCO-3086)
There are cities that accuweather does not provide weather for. Instead of constantly requesting them, we should skip them. Cities are from taken from logs.
[DISCO-3086]: https://mozilla-hub.atlassian.net/browse/DISCO-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3086] weather: add city skip list

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/pathfinder.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-3088](https://mozilla-hub.atlassian.net/browse/DISCO-3088)
I pulled the logs after #718 was merged. Added some more countries to our pathfinder. 
This isn't reflective of all the countries/cities found in the logs, but I think it's a start. As a result with this though, if there is a city within those countries that don't follow the same region convention (like London). It'll fail and appear in the logs...
11 countries.... out of 195? 😅 Alternatively we could have another "wonder" file with the mapping, but I think that's too much.
[DISCO-3088]: https://mozilla-hub.atlassian.net/browse/DISCO-3088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3088] weather: add more rules to country,city,region pathfinder

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/pathfinder.py
- merino/providers/weather/backends/accuweather/utils.py
- merino/providers/weather/backends/protocol.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/backends/test_pathfinder.py
- tests/unit/providers/weather/backends/test_utils.py
JIRA: [DISCO-3091](https://mozilla-hub.atlassian.net/browse/DISCO-3091)
For cases where we request location keys with just country and city and the response returns more than one location, we can use lat long to calculate the closer one. 
In the event of cases like North Park, ON and accuweather only returns North Park, SK and North Park, BC, I decided to have a distance threshold so that we don't accidentally pick the wrong location
[DISCO-3091]: https://mozilla-hub.atlassian.net/browse/DISCO-3091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3091] weather: Add lat/long distance logic

- merino/providers/weather/backends/accuweather/pathfinder.py
- tests/unit/providers/weather/backends/test_pathfinder.py
JIRA: [DISCO-3098](https://mozilla-hub.atlassian.net/browse/DISCO-3098)
Since we're using WeatherContext to get city downstream, we need to set it to the corrected string, which was missed when I did #722 
[DISCO-3098]: https://mozilla-hub.atlassian.net/browse/DISCO-3098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3098] fix: set corrected city name into WeatherContext

- merino/curated_recommendations/corpus_backends/protocol.py
- merino/curated_recommendations/localization.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-260
Created a `LOCALIZED_TOPIC_SECTION_TITLES` dictionary in `corpus_backends/protocol` to hold the localized topic section titles for `new_tab_en_us` & `new_tab_de_de`.
EN-US strings: https://searchfox.org/mozilla-central/source/browser/locales/en-US/browser/newtab/newtab.ftl#392
DE-DE strings: https://github.com/mozilla-l10n/firefox-l10n/blob/main/de/browser/browser/newtab/newtab.ftl#L407
> HNT-260: Hardcode localized topic section titles for US & Germany

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/curated_recommendations/rankers.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
[Experiment brief](https://docs.google.com/document/d/1u1_wwi2Da44yKW7JRp0oW4EwC9Hkc0E5CgKYWXJWGRE/edit?usp=sharing)
[JIRA](https://mozilla-hub.atlassian.net/browse/GENAI-467)
In the above experiment, we intend to reduce the exploration period for items in the new tab content feed.  This is accomplished by scaling the $\alpha$ and $\beta$ parameters that determine the CTR prior for Thompson sampling.
We decided to keep this experiment separate from the region-based ranking experiment which has region-specific priors.
> [GENAI-467] support for reduced exploration prior experiment

- merino/jobs/geonames_uploader/downloader.py
- tests/unit/jobs/geonames_uploader/test_downloader.py
[Bug 1934766 - In the geonames uploader, include names with punctuation removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1934766)
> feat: geonames uploader - include names with punctuation stripped - Bug 1934766

- merino/curated_recommendations/corpus_backends/protocol.py
- merino/curated_recommendations/layouts.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- pyproject.toml
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_localization.py
JIRA: [HNT-281](https://mozilla-hub.atlassian.net/browse/HNT-281)
Change topic section identifiers to match their corresponding topic identifier.
[HNT-281]: https://mozilla-hub.atlassian.net/browse/HNT-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-281] Topic section ids match the topic id

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/curated_recommendations/rankers.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_rankers.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-278
Boost followed sections to the very top. `top_stories_section` should always be at the very top (`receivedFeedRank==0`), followed by followed sections + unfollowed sections.
Client can send a new request param `sections`:
```
"sections": [
{
"sectionId": "food",
"isFollowed": true,
"isBlocked": false
},
{
"sectionId": "arts",
"isFollowed": false,
"isBlocked": true
},
{
"sectionId": "education",
"isFollowed": true,
"isBlocked": false
}
]
```
`isFollowed` & `isBlocked` is set to `False` by default, unless specified by the client. For now, `isBlocked` is ignored on the server, blocking action is handled on the client-side. 
`boost_followed_sections` in `rankers.py`:
* updates `isBlocked` on a section, does nothing with this.
* updates …
> HNT-278: Boost followed sections

- merino/providers/weather/backends/accuweather/pathfinder.py
We originally normalized strings due to some cities in hawaii where accuweather expected the normalized string name. I think it's time to figure out whether normalizing strings is more beneficial or detrimental. 
> chore: correct city mapping addition for Querétaro

- Dockerfile
JIRA: [DISCO-3126](https://mozilla-hub.atlassian.net/browse/DISCO-3126)
With the release of [Poetry 2.0.0](https://github.com/python-poetry/poetry/releases/tag/2.0.0), the command [export](https://github.com/python-poetry/poetry/pull/5980) is no longer included by default, we'll need to add the plugin.
[DISCO-3126]: https://mozilla-hub.atlassian.net/browse/DISCO-3126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3126] chore: poetry update removes 'export', need to add plugin

- merino/middleware/geolocation.py
- merino/providers/weather/backends/accuweather/pathfinder.py
- tests/unit/middleware/test_geolocation.py
- tests/unit/providers/weather/backends/test_pathfinder.py
JIRA: [DISCO-3125](https://mozilla-hub.atlassian.net/browse/DISCO-3125)
Normalization city names seems to cause more harm than good from a global perspective.
Removing it and adding the CA and US cities that need normalization to the mapping list
[DISCO-3125]: https://mozilla-hub.atlassian.net/browse/DISCO-3125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3125] Remove city name normalization

- merino/providers/weather/backends/accuweather/pathfinder.py
minor fix, realized since we don't normalize strings anymore, some changes in the correction mapping needed to be made. and i fixed the sorting 🙈 
> chore: city pathfinder correction minor fix

- merino/jobs/csv_rs_uploader/fakespot.py
- tests/unit/jobs/csv_rs_uploader/test_fakespot.py
Fakespot will be adding a category field to their CSV uploads, this commit makes us ready to start using it when they do. In the meantime, devs won't be able to use the script with the current Fakespot CSV format.  I checked in with them and this is okay.
> [DISCO-3129] Fakespot category field

- merino/jobs/wikipedia_indexer/filemanager.py
- tests/integration/jobs/wikipedia_indexer/test_filemanager.py
JIRA: [DISCO-2808](https://mozilla-hub.atlassian.net/browse/DISCO-2808)
The wikipedia airflow job sometimes fails in the process of streaming the dump to GCS. This leaves behind an incomplete file which has to be manually removed by SRE before re-run. This PR adds a fix by deleting the partial upload file on failure.
[DISCO-2808]: https://mozilla-hub.atlassian.net/browse/DISCO-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2808] delete partial wiki upload on stream failure

- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/pathfinder.py
- merino/providers/weather/provider.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-3096](https://mozilla-hub.atlassian.net/browse/DISCO-3096)
We currently flood the logs with the cities where weather isn't provided. This isn't really helpful as no new info is provided. To ensure we still have this info, I think it's probs better to periodically log this instead. This will also save the number of requests we make to retrieve weather
[DISCO-3096]: https://mozilla-hub.atlassian.net/browse/DISCO-3096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3096] Add cities to skip list when no weather is provided

- docs/data.md
- merino/web/api_v1.py
- tests/integration/api/v1/test_manifest.py
JIRA: [DISCO-3109](https://mozilla-hub.atlassian.net/browse/DISCO-3109)
Adding the following metrics to the `/manifest` endpoint:
```
- `manifest.request.get` - A counter for how many requests against the `/manifest` endpoint where made.
- `manifest.request.timing` - A timer how long it took the endpoint to fulfill the request.
- `manifest.gcs.fetch_time` - A timer for how long it took to download the latest manifest file from the Google Cloud bucket.
- `manifest.request.no_manifest` - A counter to measure how many times we didn't find the latest manifest file.
- `manifest.request.error` - A counter to measure how many times we could not provide a valid JSON manifest file.
```
[DISCO-3109]: https://mozilla-hub.atlassian.net/browse/DISCO-3109?atlOrigin=e …
> DISCO-3109 - Adding metrics to manifest endpoint

- merino/web/api_v1.py
- tests/integration/api/v1/test_manifest.py
JIRA: [DISCO-3109](https://mozilla-hub.atlassian.net/browse/DISCO-3109)
Some minor adjustments, adding metric for size of the manifest file.
[DISCO-3109]: https://mozilla-hub.atlassian.net/browse/DISCO-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3109 - fix some metrics

- merino/curated_recommendations/layouts.py
- merino/curated_recommendations/localization.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-306](https://mozilla-hub.atlassian.net/browse/HNT-306)
Tweaks and fixes for the topic section experiment.
Fixes:
- Section `receivedFeedRank` is numbered correctly in case sections are removed because we don't have enough recommendations.
- Recommendation `receivedRank` is numbered correctly for `top_stories_section`.
Changed product requirements:
- For 4 medium card layout, move the Ad to the last slot, as long as this doesn’t break the layout when we shrink the viewport
- Remove In the News
- Update Popular Today layout (which will now now be at the top) to Large, 2 small, medium (i.e. what we’re using for In the News now)
[HNT-306]: https://mozilla-hub.atlassian.net/browse/HNT-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> [HNT-306] Topic sections tweaks and rank fixes

- merino/providers/suggest/weather/backends/accuweather/utils.py
JIRA: [DISCO-3136](https://mozilla-hub.atlassian.net/browse/DISCO-3136)
Noticing there are more calculation failures than success, adding temp logs to help find out which cities are unsuccesful
[DISCO-3136]: https://mozilla-hub.atlassian.net/browse/DISCO-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3136] - add temp logs to debug distance calculations

- merino/providers/suggest/weather/backends/accuweather/utils.py
- tests/unit/providers/suggest/weather/backends/test_utils.py
JIRA: [DISCO-3168](https://mozilla-hub.atlassian.net/browse/DISCO-3168)
Metrics were inaccurate as we were including cases where accuweather did not provide locations and we considered that as a distance calculation fail.
[DISCO-3168]: https://mozilla-hub.atlassian.net/browse/DISCO-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3168] Don't record dist calc metric when no locations

- merino/curated_recommendations/rankers.py
- tests/integration/api/v1/test_manifest.py
- tests/unit/providers/suggest/weather/backends/test_accuweather.py
JIRA: [DISCO-3130](https://mozilla-hub.atlassian.net/browse/DISCO-3130)
Most of the warnings in this patch are either using deprecated code or code errors by us.
@Trinaa I am more leaning towards treating test warnings as errors now :)
[DISCO-3130]: https://mozilla-hub.atlassian.net/browse/DISCO-3130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix all the warnings in tests

- docs/data.md
- merino/providers/suggest/weather/provider.py
- tests/unit/providers/suggest/weather/test_provider.py
JIRA: [DISCO-3173](https://mozilla-hub.atlassian.net/browse/DISCO-3173)
As we expand weather globally, it will be good to know the number of weather queries we have, in contrast with the number of skips, processing errors etc.
[DISCO-3173]: https://mozilla-hub.atlassian.net/browse/DISCO-3173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3173] Add metric to count number of weather report queries

- docs/operations/jobs/navigational_suggestions.md
- merino/jobs/utils/__init__.py
- merino/jobs/utils/domain_tester.py
- pyproject.toml
JIRA: [DISCO-3175](https://mozilla-hub.atlassian.net/browse/DISCO-3175)
We may want to iterate over the functionality of fetching favicons from websites locally. I added a script to run the extractor:
```bash
$ poetry run probe-images mozilla.org wikipedia.org
```
[DISCO-3175]: https://mozilla-hub.atlassian.net/browse/DISCO-3175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3175 - script for running domain_metadata_extractor separately

- merino/configs/__init__.py
- merino/configs/default.toml
- merino/configs/production.toml
- merino/configs/stage.toml
- merino/configs/testing.toml
- merino/providers/manifest/backends/manifest.py
- merino/providers/suggest/top_picks/backends/top_picks.py
- tests/unit/providers/suggest/top_picks/backends/test_filemanager.py
JIRA: [DISCO-3183](https://mozilla-hub.atlassian.net/browse/DISCO-3183)
TopPicks and Manifest are using the same bucket and the same file.
[DISCO-3183]: https://mozilla-hub.atlassian.net/browse/DISCO-3183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3183 Consolidate manifest configs

- merino/providers/manifest/backends/filemanager.py
- merino/providers/manifest/backends/manifest.py
JIRA: [DISCO-3185](https://mozilla-hub.atlassian.net/browse/DISCO-3185)
Adding two metrics for the `manifest` provider:
- `manifest.domains.count`
- `manifest.size`
[DISCO-3185]: https://mozilla-hub.atlassian.net/browse/DISCO-3185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3185 Add metrics for manifest

- merino/providers/suggest/top_picks/backends/filemanager.py
- merino/providers/suggest/top_picks/backends/top_picks.py
- tests/unit/providers/manifest/backends/test_filemanager.py
- tests/unit/providers/suggest/top_picks/backends/test_filemanager.py
- tests/unit/providers/suggest/top_picks/backends/test_top_picks.py
- tests/unit/providers/suggest/top_picks/conftest.py
JIRA: [DISCO-3180](https://mozilla-hub.atlassian.net/browse/DISCO-3180)
Instead of using `google.cloud.storage.Client` directly, we use our own `GcsUploader` module. This PR switches the `top_picks` provider over to `GcsUploader` as well.
[DISCO-3180]: https://mozilla-hub.atlassian.net/browse/DISCO-3180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3180 Use GcsUploader for top_picks provider

- merino/providers/suggest/top_picks/backends/filemanager.py
- tests/unit/providers/manifest/backends/test_filemanager.py
- tests/unit/providers/manifest/backends/test_manifest.py
- tests/unit/providers/suggest/top_picks/backends/test_filemanager.py
- tests/unit/providers/suggest/top_picks/backends/test_top_picks.py
- tests/unit/providers/suggest/top_picks/conftest.py
JIRA: [DISCO-3182](https://mozilla-hub.atlassian.net/browse/DISCO-3182)
Remove duplicated test fixtures.
[DISCO-3182]: https://mozilla-hub.atlassian.net/browse/DISCO-3182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3182 Remove duplicated fixtures

- merino/providers/suggest/wikipedia/provider.py
JIRA: [DISCO-3196](https://mozilla-hub.atlassian.net/browse/DISCO-3196)
Now that there is Merino hosted Wikipedia icon, let's use that to replace the hardcoded one.
[DISCO-3196]: https://mozilla-hub.atlassian.net/browse/DISCO-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Use the remote icon for dynamic wikipedia

- dev/top_picks.json
- docs/manifest.md
- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/utils.py
- tests/integration/api/v1/manifest/test_manifest.py
- tests/unit/conftest.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py
JIRA: [DISCO-3197](https://mozilla-hub.atlassian.net/browse/DISCO-3197)
Drop those hardcoded TippyTop image URIs from Top Picks, those domains will fall back to the generic globe icon until better image replacements are provisioned in the future.
[DISCO-3197]: https://mozilla-hub.atlassian.net/browse/DISCO-3197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Remove hardcoded chrome image URIs from top picks

- merino/configs/default.toml
JIRA: [DISCO-3192](https://mozilla-hub.atlassian.net/browse/DISCO-3192)
New locales that need to be added for weather expansion
[DISCO-3192]: https://mozilla-hub.atlassian.net/browse/DISCO-3192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3192] add new locales for weather expansion

- merino/curated_recommendations/__init__.py
- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- merino/curated_recommendations/corpus_backends/protocol.py
- merino/providers/manifest/provider.py
- tests/integration/api/conftest.py
- tests/integration/api/v1/curated_recommendations/corpus_backends/fixtures.py
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/integration/api/v1/manifest/test_manifest.py
- tests/unit/conftest.py
- tests/unit/curated_recommendations/test_provider.py
- tests/unit/curated_recommendations/test_rankers.py
- tests/unit/providers/manifest/conftest.py
- tests/unit/providers/manifest/test_get_url.py
- tests/unit/providers/manifest/test_init_provider.py
- tests/unit/providers/manifest/test_provider.py
JIRA: 
- [DISCO-3204](https://mozilla-hub.atlassian.net/browse/DISCO-3204)
- [DISCO-3204](https://mozilla-hub.atlassian.net/browse/DISCO-3203)
- [DISCO-3204](https://mozilla-hub.atlassian.net/browse/DISCO-3205)
Enriching the `/curated-recommendations` endpoint with a `iconUrl` field for each article recommendation. The `iconUrl` is a `HttpUrl`, taken from the `Manifest` provider, and if the favicon for the domain is available, we attach it to a recommendation. Otherwise, we return an empty string. 
In the background, the `Manifest` is updated once a week, and therefore the icons will be updated in this interval. Which means newly added domains to the `Manifest` will be available to this endpoint at that time.
[DISCO-3204]: …
> DISCO-3202 - Enrich the curated-recommendations endpoint with icon-urls

- docs/intro.md
JIRA: [DISCO-3207](https://mozilla-hub.atlassian.net/browse/3207)
Update the architecture diagram with the two new endpoints
View the updated diagram [here](https://www.mermaidchart.com/raw/5b675b26-d0c1-4e1c-92ec-e6ab92ce23f8?theme=light&version=v0.1&format=svg).
[DISCO-3207]: https://mozilla-hub.atlassian.net/browse/DISCO-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3207] Update merino architecture diagram

- tests/integration/api/conftest.py
- tests/integration/api/v1/manifest/test_manifest.py
JIRA: [DISCO-3226](https://mozilla-hub.atlassian.net/browse/DISCO-3226)
Leaking unexpected logs could cause flaky tests in Merino.
[DISCO-3226]: https://mozilla-hub.atlassian.net/browse/DISCO-3226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix the log leakages in integration tests

- tests/unit/providers/suggest/amo/backends/test_dynamic.py
JIRA: [DISCO-3226](https://mozilla-hub.atlassian.net/browse/DISCO-3226)
Found another flaky unit test that was failing on captured log output assertions. [This test](https://app.circleci.com/pipelines/github/mozilla-services/merino-py/4174/workflows/fc69668d-769a-448a-a545-e8283229f176/jobs/29034) was failing because it was encountering an extra / leaked log output (WARN level) from other place. 
I couldn't trace that extra leaky log output but I was able to set the level of logs we want to capture for this set.
[DISCO-3226]: https://mozilla-hub.atlassian.net/browse/DISCO-3226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3226] Fix flaky amo backend unit test

- merino/curated_recommendations/interest_picker.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_interest_picker.py
- JIRA: [HNT-374](https://mozilla-hub.atlassian.net/browse/HNT-374)
- [Interest picker API spec](https://mozilla-hub.atlassian.net/wiki/spaces/FPS/pages/1287553025/Inline+Interest+Picker+-+API+Specification)
- [Product plan](https://docs.google.com/document/d/1dTHDMNhxRre0ubsjBDWQJ7Z_X-J9EBiP9noRyLla7EI/edit?tab=t.0)
Return an 'Interest Picker' from the curated recommendation endpoint, to allow clients to follow sections.
[HNT-374]: https://mozilla-hub.atlassian.net/browse/HNT-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-374] Add interest picker

- docs/intro.md
JIRA: [DISCO-3207](https://mozilla-hub.atlassian.net/browse/DISCO-3207)
Architecture diagram on Github Pages is broken possibly due to the addition of config values. Removing those for it to render correctly.
[DISCO-3207]: https://mozilla-hub.atlassian.net/browse/DISCO-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3207] [load test: skip] Remove mermaid architeture diagram config values

- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
- tests/unit/providers/suggest/weather/backends/test_pathfinder.py
JIRA: [DISCO-3240](https://mozilla-hub.atlassian.net/browse/DISCO-3240)
Cities that require correction weren't used
[DISCO-3240]: https://mozilla-hub.atlassian.net/browse/DISCO-3240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3240] fix: merino weather to use corrected cities

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: [HNT-405](https://mozilla-hub.atlassian.net/browse/HNT-405)
If a user blocks a section using the Follow/Block feature (e.g. Food, Politics), we remove recommendations with those topics from sections, including 'Popular Today'.
[HNT-405]: https://mozilla-hub.atlassian.net/browse/HNT-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-405] Remove blocked topics from sections

- tests/unit/providers/suggest/amo/backends/test_dynamic.py
JIRA: [DISCO-3251](https://mozilla-hub.atlassian.net/browse/DISCO-3251)
Follow up to this PR https://github.com/mozilla-services/merino-py/pull/789, adding filtering to a flaky test. this is a temporary fix till we can figure out why the tests are flaky.
[DISCO-3251]: https://mozilla-hub.atlassian.net/browse/DISCO-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3251] fix flaky amo test

- merino/providers/suggest/weather/backends/accuweather/backend.py
- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
- merino/providers/suggest/weather/backends/protocol.py
- tests/unit/providers/suggest/weather/backends/test_pathfinder.py
JIRA: [DISCO-3246](https://mozilla-hub.atlassian.net/browse/DISCO-3246)
We were saving the manipulated/normalized city name in `geolocation.city` so it changes when we try to fetch from cache, when we try to call the api, we're left with the manipulated/normalized city name with no reference to the original
[DISCO-3246]: https://mozilla-hub.atlassian.net/browse/DISCO-3246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3246] fix: Weather to save normalized city in selected_city field

- merino/curated_recommendations/engagement_backends/gcs_engagement.py
- merino/curated_recommendations/engagement_backends/protocol.py
- merino/curated_recommendations/rankers.py
- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-402](https://mozilla-hub.atlassian.net/browse/HNT-402)
We updated Thompson sampling to rank on the `corpus_item_id` in anticipation of the section-based layout for new tab using `corpus_item_id` as the item identifier.  Engagement data will have both `corpus_item_id` and `scheduled_item_id` for now but ranking will be based on the `corpus_item_id` for Thompson sampling within individual sections.
[HNT-402]: https://mozilla-hub.atlassian.net/browse/HNT-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-402] updating item identifier in engagement backend

- .circleci/config.yml
- Makefile
JIRA: [DISCO-3134](https://mozilla-hub.atlassian.net/browse/DISCO-3134)
* add executors to circleci config to address schema validation errors
* Example:
* rename unit and integration test artifact files to comply with ETE pipeline specifications
* add upload test artifact job to main-workflow
* remove circleci artifact storage to reduce costs
* remove coverage-combined command, since file is unused
[DISCO-3134]: https://mozilla-hub.atlassian.net/browse/DISCO-3134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3134] Add Steps to CircleCI Workflow Test Jobs For Pushing Test Artifacts to the ETE GCP Cloud Storage

- merino/providers/suggest/weather/backends/accuweather/backend.py
- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
- tests/unit/providers/suggest/weather/backends/test_accuweather.py
- tests/unit/providers/suggest/weather/backends/test_pathfinder.py
JIRA: [DISCO-3247](https://mozilla-hub.atlassian.net/browse/DISCO-3247)
We tried to be fancy and it sort of bit us. We can't iterate over a map twice, so I swapped the two for loops. so we can keep map. In theory there's only a small number of edge cases where the first iteration is not successful and we would have more iterations then if the for loop order was swapped
[DISCO-3247]: https://mozilla-hub.atlassian.net/browse/DISCO-3247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3247] fix: weather pathfinder to use region when None

- .circleci/config.yml
- Makefile
JIRA: [DISCO-3134](https://mozilla-hub.atlassian.net/browse/DISCO-3134)
Uploading test artifacts using the 'upload-test-artifacts' job will not work should one of its dependent test jobs fail. This fix uses a step with the directive to run 'when: always' to assure artifact upload.
[DISCO-3134]: https://mozilla-hub.atlassian.net/browse/DISCO-3134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3134] Fix Test Artifacts Upload to GCS on Failure

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- tests/data/scheduled_surface.json
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [DISCO-3228](https://mozilla-hub.atlassian.net/browse/DISCO-3228)
Add metrics and logging for curated recommendations favicons hits and misses. This will allow us to better understand the success percentage and be able to add the missing icon urls manually for the urls that had a miss.
[DISCO-3228]: https://mozilla-hub.atlassian.net/browse/DISCO-3228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3228] Add metrics and logging for curated recommendations favicons

- .circleci/config.yml
- .github/workflows/main-workflow.yaml
- .github/workflows/pr-workflow.yaml
JIRA: [DISCO-3148](https://mozilla-hub.atlassian.net/browse/DISCO-3148)
- Added two workflow files. One that runs on every PR, and one that runs when we push to main. the main workflow does the additional job of publishing the docs. This follows the current setup in circleci
[DISCO-3148]: https://mozilla-hub.atlassian.net/browse/DISCO-3148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3148] add GH Action workflows for docs build & publish pages jobs

- .github/workflows/main-workflow.yaml
JIRA: [DISCO-3148](https://mozilla-hub.atlassian.net/browse/DISCO-3148)
[DISCO-3148]: https://mozilla-hub.atlassian.net/browse/DISCO-3148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3148] Download artifact before disabling jekyll [load test: skip]

- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
- tests/unit/providers/suggest/weather/backends/test_pathfinder.py
JIRA: [DISCO-3294](https://mozilla-hub.atlassian.net/browse/DISCO-3294)
Because we're cycling through city names, normalized city name, city name without locality suffix times # of regions for that city, we're making a lot of requests we don't need to. I've split `REGION_MAPPING_EXCLUSIONS` into two sets instead and added the countries that we know. In addition added the cities in those countries that require the city to be None.
[DISCO-3294]: https://mozilla-hub.atlassian.net/browse/DISCO-3294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3294] chore: update more cities for weather

- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
There seems to be some mismatch admin codes for IN, so i removed it from our `KNOWN_SPECIFIC_REGION_COUNTRIES` list, so we can try querying without admin codes until this is resolved.
> chore: city updates

- merino/middleware/metrics.py
- tests/integration/api/v1/suggest/test_suggest.py
JIRA: [DISCO-3209](https://mozilla-hub.atlassian.net/browse/DISCO-3209)
Adding tags to metrics so that we can separate by user agent
[DISCO-3209]: https://mozilla-hub.atlassian.net/browse/DISCO-3209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3209] metrics to include user agent tags

- merino/providers/suggest/manager.py
- merino/utils/icon_processor.py
- tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py
- tests/load/locustfiles/locustfile.py
- tests/unit/utils/test_icon_processor.py
JIRA: [DISCO-3330](https://mozilla-hub.atlassian.net/browse/DISCO-3330)
[DISCO-3330]: https://mozilla-hub.atlassian.net/browse/DISCO-3330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3330 Add shared http client to IconProcessor

- .circleci/config.yml
- .github/workflows/checks.yaml
- .github/workflows/docs-build.yaml
- .github/workflows/docs-publish-github-pages.yaml
- .github/workflows/main-workflow.yaml
- .github/workflows/pr-workflow.yaml
- .github/workflows/tests.yaml
- .github/workflows/upload-test-artifacts-to-gcs.yaml
- Makefile
- docs/testing/index.md
JIRA: [DISCO-3256](https://mozilla-hub.atlassian.net/browse/DISCO-3256)
* add a reusable workflow 'upload-test-artifacts-to-gcs' to GitHub actions
* incorporate 'upload-test-artifacts-to-gcs' in main-workflow GitHub action
* fix 'tests' workflow to upload test artifacts even when tests fail
* update Make to use github environment variables instead of CircleCI variables
* remove uploading test artifacts from CircleCI workflows
* update documentation
In order to make sure the new action will behave as expected, the following tests were conducted:
1. Tests Pass, Uploads in main-workflow only (Base Case) - [PASS](https://github.com/mozilla-services/merino-py/actions/runs/13907790191)
2. Tests Pass, Upload result and coverage artifacts with filters to GCS - …
> [DISCO-3256] chore(ci): migrate the "upload-test-artifacts" and "upload-coverage-artifacts" steps from CircleCI to GH Actions

- merino/curated_recommendations/layouts.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- JIRA: [HNT-455](https://mozilla-hub.atlassian.net/browse/HNT-455)
- [Figma spec](https://www.figma.com/design/VdghooQZTLiXYO8hF5pAuS/Feed?node-id=10976-209386&t=5TeGb0b5ClpQl8zA-0)
Changes the layout of the second section two be 2 rows with 3 ads, to make the number of ads the same between the sections experiment, and whats shown in the control branch.
The new layout is only shown behind a Nimbus experiment, which our team can enroll in to QA the new layout before it's shown to users.
[HNT-455]: https://mozilla-hub.atlassian.net/browse/HNT-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HNT-455: Sections layout update

- merino/configs/__init__.py
- merino/configs/default.toml
- merino/configs/production.toml
- merino/configs/stage.toml
- merino/utils/gcs/gcs_uploader.py
JIRA: [DISCO-3227](https://mozilla-hub.atlassian.net/browse/DISCO-3227)
Fix logic branch to set default auth credentials in staging environment too.
[DISCO-3227]: https://mozilla-hub.atlassian.net/browse/DISCO-3227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3227] Fix gcp client auth error in staging

- pyproject.toml
- uv.lock
JIRA: [DISCO-3392](https://mozilla-hub.atlassian.net/browse/DISCO-3392)
While the `regex` extension is fast, it comes with a large memory footprint (~150MB). The `re2` extension can't be built by uv (nor could be built locally), so we will have to fall back to the builtin resolver for now.
[DISCO-3392]: https://mozilla-hub.atlassian.net/browse/DISCO-3392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3392] chore: Drop the regex resolver to reduce memory footprint

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- JIRA: [HNT-472](https://mozilla-hub.atlassian.net/browse/HNT-472)
- [QA Slack thread](https://mozilla.slack.com/archives/C058SAB9F0Q/p1742339555276329)
- [Figma](https://www.figma.com/design/VdghooQZTLiXYO8hF5pAuS/Feed?node-id=6259-53439&p=f&t=RfS6kHqg3izXJ29e-0)
The new double row layout with 3 ads has successfully been QA'ed by FE, design, and PM. This PR rolls it out to all users who receive sections.
[HNT-472]: https://mozilla-hub.atlassian.net/browse/HNT-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HNT-472: Roll out double row layout to sections experiment

- merino/providers/manifest/backends/filemanager.py
- merino/providers/manifest/backends/manifest.py
- merino/providers/manifest/backends/protocol.py
- merino/providers/manifest/provider.py
- tests/unit/providers/manifest/backends/test_filemanager.py
- tests/unit/providers/manifest/backends/test_manifest.py
- tests/unit/providers/manifest/conftest.py
- tests/unit/providers/manifest/test_provider.py
JIRA: [DISCO-3210](https://mozilla-hub.atlassian.net/browse/DISCO-3210)
Implement the async gcs client. Opened in lieu of: https://github.com/mozilla-services/merino-py/pull/793 
[DISCO-3210]: https://mozilla-hub.atlassian.net/browse/DISCO-3210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3210]: Async GCS client

- dev/docker-compose.yaml
- merino/cache/redis.py
- pyproject.toml
- uv.lock
JIRA: [DISCO-3409](https://mozilla-hub.atlassian.net/browse/DISCO-3409)
Bump Redis to 7.2 to sync with the infra change. Also upgraded the client to the latest.
[DISCO-3409]: https://mozilla-hub.atlassian.net/browse/DISCO-3409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Bump redis to the 7.2 and the client with hiredis

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
JIRA: [DISCO-3410](https://mozilla-hub.atlassian.net/browse/DISCO-3410)
[DISCO-3410]: https://mozilla-hub.atlassian.net/browse/DISCO-3410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3410 Improve fixing the urls of favicons with no proper url

- merino/curated_recommendations/interest_picker.py
- merino/curated_recommendations/protocol.py
- tests/unit/curated_recommendations/test_interest_picker.py
JIRA: [HNT-474](https://mozilla-hub.atlassian.net/browse/HNT-474)
Update the Interest Picker title & subtitle:
- Change the headline: “Follow topics to fine-tune your feed”
- Removing the subtitle
[HNT-474]: https://mozilla-hub.atlassian.net/browse/HNT-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HNT-474: Change interest picker title & subtitle

- dev/docker-compose.yaml
- merino/cache/none.py
- merino/cache/protocol.py
- merino/cache/redis.py
- merino/configs/default.toml
- merino/providers/suggest/manager.py
- merino/providers/suggest/weather/backends/accuweather/backend.py
- tests/unit/providers/suggest/weather/backends/test_accuweather.py
- tests/unit/utils/test_cache_redis.py
JIRA: [DISCO-3405](https://mozilla-hub.atlassian.net/browse/DISCO-3405)
This allows Merino to connect to the replica endpoint of our Redis server to handle all the read workloads so that the primary node only needs to handle write workloads and replication related tasks.
This requires a new envvar for Merino for the replica endpoint. PR filed [here](https://github.com/mozilla-services/cloudops-infra/pull/6338). 
[DISCO-3405]: https://mozilla-hub.atlassian.net/browse/DISCO-3405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3405] feat: Support replicas for the redis adapter

- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
JIRA: [DISCO-3393](https://mozilla-hub.atlassian.net/browse/DISCO-3393)
When weather doesn't return any suggestions, we want to return a 204 instead
[DISCO-3393]: https://mozilla-hub.atlassian.net/browse/DISCO-3393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3393] Suggest: return 204 for no weather

- docs/operations/jobs/navigational_suggestions.md
- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- merino/jobs/utils/domain_tester.py
- tests/unit/jobs/navigational_suggestions/conftest.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor_improved.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_init.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py
JIRA: [DISCO-3411](https://mozilla-hub.atlassian.net/browse/DISCO-3411)
This PR re-writes how the Navigational Suggestion job works. We recently started adding more custom domains to the already existing domains we query each week inside BigQuery. The custom domains (https://github.com/mozilla-services/merino-py/blob/main/merino/jobs/navigational_suggestions/custom_domains.py) grew to over 1.5k entries.
This caused the job to error out on Airflow, most likely due to increased resource consumption. The old way was to query all domains for all possible favicons, download and compare the quality of these favicons for each side, and at the end of the run, upload them and create the `top-picks.json` file and upload it to a Google Cloud bucket.
We then introduced an async version of this job …
> DISCO-3411 Save resources on parsing favicons in the nav-suggestion job

- merino/providers/suggest/top_picks/backends/top_picks.py
- tests/unit/jobs/navigational_suggestions/test_init.py
- tests/unit/providers/suggest/top_picks/backends/test_top_picks.py
Process records also if the `source` field does not exist inside the Top Picks provider. The current manifest doesn't contain the `source` field yet. This is a backwards compatible fix, which can be removed after the next successful navigational suggestion job run.
> fix: process records in top picks if source field is not available

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- merino/jobs/navigational_suggestions/utils.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py
Reduce the amount of logs we accumulate to not to overload the Kubernetes pod.
> fix: reduce logs for nav-suggestions job

- merino/configs/testing.toml
- merino/providers/suggest/weather/backends/accuweather/backend.py
- merino/providers/suggest/weather/backends/accuweather/errors.py
- merino/providers/suggest/weather/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/suggest/weather/backends/test_accuweather.py
- tests/unit/providers/suggest/weather/test_provider.py
JIRA: [DISCO-3393](https://mozilla-hub.atlassian.net/browse/DISCO-3393)
When no weather report isn't returned in the event that we don't get anything from accuweather we want to return 204.
If no weather report is returned due to a BackendError we want to return 200. 
This way, there's a way to differentiate diff scenarios so that clients can retry for the latter case.
[DISCO-3393]: https://mozilla-hub.atlassian.net/browse/DISCO-3393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3393] Suggest: Weather 204 when there's no weather for location

- .gitignore
- dev/docker-compose.yaml
- dev/start-local-gcs-emulator.sh
- docs/operations/jobs/navigational_suggestions.md
- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/local_mode.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor_edge_cases.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader_error.py
- tests/unit/jobs/navigational_suggestions/test_get_serp_categories.py
- tests/unit/jobs/navigational_suggestions/test_init.py
- tests/unit/jobs/navigational_suggestions/test_local_mode.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py
JIRA: [DISCO-3416](https://mozilla-hub.atlassian.net/browse/DISCO-3416)
We want to be able to run the Navigational Suggestions job run locally. To this, we have to abstract two things:
- The Google Cloud services endpoint
- The domains from BigQuery
This PR introduces a `_run_local_mode` and `_run_normal_mode` for the CLI. The `local_mode` is dependent on a `fake-gcs` Docker container (`./dev/start-local-gcs-emulator.sh`). And it just takes the domains from the `custom_domains.py` list.
You can run the job locally via:
```bash
uv run merino-jobs navigational-suggestions prepare-domain-metadata --local --sample-size=20
```
The sample size goes up to the amount of domains available in the `custom_domains.py`.
[DISCO-3416]: …
> DISCO-3416 Run Navigational Suggestions job locally

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/utils/domain_tester.py
- pyproject.toml
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- uv.lock
JIRA: [DISCO-3178](https://mozilla-hub.atlassian.net/browse/DISCO-3178)
Replacing the older, unsupported `robobrowser` package in lieu of more actively maintained `mechanicalsoup` package.
[DISCO-3178]: https://mozilla-hub.atlassian.net/browse/DISCO-3178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3178] Replace robobrowser with mechanicalsoup

- merino/providers/manifest/provider.py
- tests/unit/conftest.py
- tests/unit/providers/manifest/backends/test_filemanager.py
- tests/unit/providers/manifest/backends/test_manifest.py
- tests/unit/providers/manifest/test_get_icon_url.py
JIRA: [MC-1702](https://mozilla-hub.atlassian.net/browse/MC-1702)
Yesterday there was a brief outage on the curated-recommendations endpoint. I accidentally removed a truthy check on `get_icon_url`, which introduced HttpUrl validation errors when it returns empty strings. This PR changes `get_icon_url` to return a valid URL or None.
[MC-1702]: https://mozilla-hub.atlassian.net/browse/MC-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MC-1702: get_icon_url returns valid urls or None

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/utils/domain_tester.py
- tests/integration/jobs/navigational_suggestions/conftest.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/conftest.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
JIRA: [DISCO-3440](https://mozilla-hub.atlassian.net/browse/DISCO-3440)
We were facing race conditions in the `top-picks` file creation. When getting the title from the scraper in each batch, the one domain which was processed last was overwriting the previous domains. So each batch just hat one `title` - the one from the last domain processed in that batch.
This didn't happen for all the batches though.
This PR is:
- removing the global scraper inside `_process_domains`
- creating a local `Scraper()` for each `_process_single_domain` task
- Is reducing the batch size from`50` to `25` to be able to clean up resources more often and keep the RAM down
The maximum RAM used (locally) is around 650MB. 
[DISCO-3440]: …
> DISCO-3440 Fix wrong title in manifest production

- merino/configs/production.toml
The `top-picks.json` is producing domain titles again. We can re-enable the provider again.
> fix: enable top-picks in production [load test: skip]

- merino/cache/redis.py
- merino/configs/default.toml
- merino/configs/testing.toml
- merino/governance/__init__.py
- merino/governance/circuitbreakers.py
- merino/providers/suggest/base.py
- merino/providers/suggest/manager.py
- merino/providers/suggest/weather/backends/accuweather/backend.py
- merino/providers/suggest/weather/backends/accuweather/errors.py
- merino/providers/suggest/weather/provider.py
- merino/web/api_v1.py
- pyproject.toml
- tests/integration/api/v1/suggest/test_suggest.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/integration/providers/suggest/weather/backends/test_accuweather.py
- tests/unit/providers/suggest/weather/backends/test_accuweather.py
- tests/unit/providers/suggest/weather/test_provider.py
- tests/unit/utils/test_cache_redis.py
- uv.lock
JIRA: [DISCO-2053](https://mozilla-hub.atlassian.net/browse/DISCO-2053)
This adds a circuit breaker to the AccuWeather provider which guards against two potential integration failures:
- Redis
- The AccuWeather endpoint
With this, should any of the above experiences interruptions (e.g. service downtime or high latency), the circuit breaker will help Merino to gracefully handle those without affecting the rest of the service. I've done some local benchmarks, the overhead is negligible. We will see how it performs in load tests and production.
Please see in-source documents for more implementation details. The patch was split into several smaller commits to facilitate the code review.
Will do a follow up to add metrics monitoring the circuit break status.     
_Put an `x` in the boxes that …
> [DISCO 2053] feat: Add a circuit breaker for the AccuWeather provider

- merino/providers/manifest/provider.py
- tests/unit/providers/manifest/test_get_icon_url.py
JIRA: [DISCO-3447](https://mozilla-hub.atlassian.net/browse/DISCO-3447)
Correctly return an icon_url for urls with subdomains, such as `https://edition.cnn.com/2025/04/09/entertainment/aimee-lou-wood-teeth-talk-intl-scli`.
[DISCO-3447]: https://mozilla-hub.atlassian.net/browse/DISCO-3447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3447] Fix: handle subdomains for icon_url

- merino/jobs/navigational_suggestions/__init__.py
- tests/integration/jobs/navigational_suggestions/test_init.py
JIRA: [DISCO-3441](https://mozilla-hub.atlassian.net/browse/DISCO-3441)
We don't want to store domains in the Manifest file when they:
- don't have a valid favicon url (we couldn't find one)
- AND are from the `custom_domains.py` file
We keep empty favicon url entries from the top-sites (BigQuery), because they are used for Search & Suggest.
[DISCO-3441]: https://mozilla-hub.atlassian.net/browse/DISCO-3441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3441 Filter out empty favicon entries from custom-domains

- merino/utils/api/query_params.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
JIRA: [DISCO-3507](https://mozilla-hub.atlassian.net/browse/DISCO-3507)
As a temp measure, we're going to ignore the region if the weather request is made with the parameters, country, city and region and the country is "GB".  Will remove, once we have the correct mapping for the UK region that accuweather expects.
This should not affect other ways that weather is requested
[DISCO-3507]: https://mozilla-hub.atlassian.net/browse/DISCO-3507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3507] temp fix ignore UK region when specified in weather request

- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [MC-1477](https://mozilla-hub.atlassian.net/browse/MC-1477)
[Recent Slack thread](https://mozilla.slack.com/archives/C058SAB9F0Q/p1743464155135359) confirming that translations are available
Re-enable topics on New Tab recommendations for all locales. We disabled topics for non-English locales in the past because the translations weren't ready yet, and re-enabling them well off our radar.
[MC-1477]: https://mozilla-hub.atlassian.net/browse/MC-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1477] Enable topics for non-English locales

- merino/curated_recommendations/protocol.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-503](https://mozilla-hub.atlassian.net/browse/HNT-503)
[BugZilla #1960999](https://bugzilla.mozilla.org/show_bug.cgi?id=1960999)
Add a `coarseOs` and `utcOffset` parameter to the request for New Tab recommendations. For now, these parameters will not be used by the backend. Eventually, they may allow us to deliver more relevant recommendations to users, in a privacy-preserving way.
[HNT-503]: https://mozilla-hub.atlassian.net/browse/HNT-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HNT-503: Add coarse OS and timezone request params

- merino/curated_recommendations/layouts.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/fixtures.py
- tests/unit/curated_recommendations/test_provider.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-429
Only display Ads in sections: 1,2,3,5,7,9 (`receivedFeedRank: {0,1,2,4,6,8}`) and then no more.
> HNT-429: Adjust ad display in sections

- docs/data.md
- docs/testing/integration-tests.md
- merino/configs/app_configs/config_logging.py
- merino/middleware/logging.py
- merino/utils/log_data_creators.py
- tests/integration/api/conftest.py
- tests/integration/api/test_error.py
- tests/integration/api/test_heartbeat.py
- tests/integration/api/test_version.py
- tests/integration/api/types.py
- tests/integration/api/v1/suggest/test_providers.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/integration/api/v1/test_unsupported.py
- tests/unit/utils/test_log_data_creator.py
JIRA: [DISCO-3512](https://mozilla-hub.atlassian.net/browse/DISCO-3512)
See more details in the ticket. Let's see if this could save Merino's logging cost.
[DISCO-3512]: https://mozilla-hub.atlassian.net/browse/DISCO-3512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO 3512] fix: Remove the "request.summary"  logs

- merino/curated_recommendations/__init__.py
- merino/utils/gcs/__init__.py
- merino/utils/gcs/gcs_uploader.py
- tests/unit/content_handler/test_gcp_uploader.py
JIRA: [DISCO-3253](https://mozilla-hub.atlassian.net/browse/DISCO-3253)
We were seeing errors about the gcs client initializing failing to find any credentials. We fixed this error in the `gcs_uploader.py` module. The reason this occurs is that it is looking for an explicit `credentials` argument but if none is passed, it tries to pull the ADC file from the google project. However, when running locally, we don't have an ADC file hence adding this check.
[DISCO-3253]: https://mozilla-hub.atlassian.net/browse/DISCO-3253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3253] Fix gcs client auth error for curated recommendations

- merino/configs/default.toml
- merino/jobs/wikipedia_indexer/__init__.py
- merino/jobs/wikipedia_indexer/filemanager.py
- merino/jobs/wikipedia_indexer/indexer.py
- merino/jobs/wikipedia_indexer/settings/v1.py
- tests/integration/jobs/wikipedia_indexer/test_filemanager.py
- tests/integration/jobs/wikipedia_indexer/test_indexer.py
- tests/unit/jobs/wikipedia_indexer/test_filemanager.py
JIRA: [DISCO-3482](https://mozilla-hub.atlassian.net/browse/DISCO-3482)
This PR adds the initial changes to support multi-language Wikipedia indexing, beginning with English (en) only. The goal is to ensure that the job can run successfully with a language-aware setup before expanding to additional languages (e.g., fr, de, it, pl).
Changes
* Updated the job CLI to iterate over a list of languages (["en"] for now)
* Modified the `FileManager` to accept a language argument and apply language-specific filename filtering
* Added validation to ensure only supported languages are accepted
* Added Elasticsearch index settings and mappings specific to English
* Extended the toml config to include a per-language alias (`en_es_alias`)
* Updated index creation logic to dynamically select …
> [DISCO-3482] Add Language Support to Wiki Indexer Job

- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_sections.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-656
Non-ML topic feeds need IAB metadata. 
Creating a mapping between non-ML topic feeds & IAB category codes (see [source for mapping](https://docs.google.com/spreadsheets/d/1R0wzDYgrFkLjo6sxTFvVYThJ4uKz-YVDkYMegbGK9XA/edit?gid=1439764175#gid=1439764175))
> HNT-656: Map IAB category codes to Section

- merino/main.py
- merino/providers/suggest/weather/provider.py
- merino/utils/api/query_params.py
- tests/integration/api/v1/suggest/test_suggest.py
- tests/unit/providers/suggest/weather/test_provider.py
- tests/unit/utils/api/test_query_params.py
JIRA: [DISCO-3528](https://mozilla-hub.atlassian.net/browse/DISCO-3528)
Log all HTTP 400 errors.
[DISCO-3528]: https://mozilla-hub.atlassian.net/browse/DISCO-3528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3528] fix: Add logs for http 400 errors

- docs/data.md
- merino/providers/manifest/provider.py
- tests/unit/providers/manifest/test_get_icon_url.py
JIRA: [DISCO-3527](https://mozilla-hub.atlassian.net/browse/DISCO-3527)
Remove the logging of failed url lookups from the manifest provider, and replaced it with metrics and a domain tag.
[DISCO-3527]: https://mozilla-hub.atlassian.net/browse/DISCO-3527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3527 Remove failed url logger from manifest provider, add metrics

- merino/configs/default.toml
- merino/providers/suggest/adm/backends/remotesettings.py
- tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py
- tests/unit/providers/suggest/adm/backends/test_remotesettings.py
JIRA: [DISCO-3479](https://mozilla-hub.atlassian.net/browse/DISCO-3479)
This should move merino to fetch records from the new collection and should keep existing functionality all the same. This would help us half way to getting merino to support multi country and form factor
[DISCO-3479]: https://mozilla-hub.atlassian.net/browse/DISCO-3479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3479] Switch Merino to use quicksuggest-amp collection

- merino/jobs/utils/domain_category_mapping.py
- merino/providers/suggest/adm/provider.py
- tests/unit/providers/suggest/adm/test_provider.py
JIRA: [DISCO-3524](https://mozilla-hub.atlassian.net/browse/DISCO-3524)
This categorizes AMP suggestions via SERP categories to prepare for the R2D2 experiment for AMP. To minimize the ingestion overhead, the suggestion categorization is done (and cached) at query time.
[DISCO-3524]: https://mozilla-hub.atlassian.net/browse/DISCO-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3524] feat: Categorize AMP suggestions via SERP categories

- merino/jobs/csv_rs_uploader/yelp.py
- tests/unit/jobs/csv_rs_uploader/test_yelp.py
JIRA: [SNG-2374](https://mozilla-hub.atlassian.net/browse/SNG-2374)
We need to show a prefix to the title of Yelp suggestion if the subject indicates a service.
To realize it, we want to register new data that are business subjects in Remote Settings.
[SNG-2374]: https://mozilla-hub.atlassian.net/browse/SNG-2374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Introduce business subjects for Yelp suggestion

- merino/jobs/geonames_uploader/__init__.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- merino/jobs/utils/chunked_rs_uploader.py
- merino/jobs/utils/rs_uploader.py
- tests/unit/jobs/geonames_uploader/test_geonames_uploader.py
- tests/unit/jobs/utils/test_rs_uploader.py
The main thing this does is factor out the core Kinto calls from `ChunkedRemoteSettingsUploader` into a new `RemoteSettingsUploader` class. For the geonames uploader changes I'm working on, I'm planning on not using chunking and instead just making one record per country.
Other changes:
Remove the staged-changes mechanism from `ChunkedRemoteSettingsUploader` and just upload/delete directly. It doesn't seem necessary?
Pass `dry_mode` to the Kinto API instead of managing that ourselves.
Use the Kinto `add_attachment()` API instead of making our own POST request.
Simplify `ChunkedRemoteSettingsRelevancyUploader` by subclassing `Chunk`.
Add some API to `Chunk` to make subclassing easier.
https://mozilla-hub.atlassian.net/browse/SNG-2523
┆Issue is …
> [SNG-2523] Improve the remote settings uploader classes

- merino/jobs/wikipedia_indexer/filemanager.py
- merino/jobs/wikipedia_indexer/settings/v1.py
- tests/unit/jobs/wikipedia_indexer/test_filemanager.py
JIRA: [DISCO-3482](https://mozilla-hub.atlassian.net/browse/DISCO-3482)
- This PR updates the `stream_latest_dump_to_gcs()` method to handle the scenario where the target file in the GCS bucket initially doesn't exist (i.e., no Wikipedia dump files are present yet). Previously, the method would raise a `RuntimeError` when no matching dump file was found in GCS, causing the first run of the `copy_export` job to fail.
- This Pr also updates the english index. The `en` suffix was missing from the english analyzers causing a mismatch with the mapping. 
[DISCO-3482]: https://mozilla-hub.atlassian.net/browse/DISCO-3482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira …
> [DISCO-3482] Fix failing wiki job - first run

- merino/configs/default.toml
- merino/curated_recommendations/__init__.py
- merino/curated_recommendations/ml_backends/__init__.py
- merino/curated_recommendations/ml_backends/fake_local_model.py
- merino/curated_recommendations/ml_backends/gcs_local_model.py
- merino/curated_recommendations/ml_backends/protocol.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_local_model.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/ml_backends/test_fake_local_model.py
- tests/unit/curated_recommendations/test_sections.py
JIRA: [HNT-574](https://mozilla-hub.atlassian.net/browse/HNT-574)
https://mozilla-hub.atlassian.net/wiki/spaces/FPS/pages/1575092266/Personalization+v1+-+Section+Personalization
Merino serves some model metadata as part of the content response. This metadata is considered a 'local model' for aggregating features of interactions and clicks on articles in a certain way.
Key changes:
• Interest vector is received from the firefox content request and parsed (but not acted upon yet)
• Model is served when a non-null interest vector is sent from the client
• Section and topic names are included in the 'features' section with the 's_' and 't_' prefix respectively.
- [x ] This PR conforms to the [Contribution …
> HNT-574 inferred personalization to merino

- merino/configs/default.toml
- merino/providers/suggest/wikipedia/backends/elastic.py
- merino/providers/suggest/wikipedia/backends/fake_backends.py
- merino/providers/suggest/wikipedia/backends/protocol.py
- merino/providers/suggest/wikipedia/backends/utils.py
- merino/providers/suggest/wikipedia/provider.py
- tests/unit/providers/suggest/wikipedia/backends/test_elastic.py
- tests/unit/providers/suggest/wikipedia/backends/test_utils.py
JIRA: [DISCO-3509](https://mozilla-hub.atlassian.net/browse/DISCO-3509)
This PR updates the wikipedia suggest provider to support multilingual queries by dynamically selecting the appropriate elasticsearch index and wikipedia domain based on the request’s `accept-language` header.
- Updated the Wikipedia provider to extract the language code from the request header and use it to determine the correct elasticsearch index alias (e.g., frwiki-v1, dewiki-v1) to query
- Updated `build_article()` to generate wikipedia URLs based on language
- URLs now point to `{language}.wikipedia.org/wiki/...` rather than always using english
- Added a utility function get_languag_code() that:
- Parses the languages from the header and normalizes locale values (e.g., fr-FR → fr)
- Defaults to english if …
> [DISCO-3509] Add language to wikipedia provider

- .gitignore
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
GENAI-1208 fix - section TS with region in args
JIRA: [GENAI-1208](https://mozilla-hub.atlassian.net/browse/GENAI-1208)
While analyzing the below experiment result we noticed that the treatment arm had lower CTR and the reason was due to the top section was getting different set of items as region was missed in the section ranker. 
This is to fix that behavior
Added test for region presence in args
How to test this 
```
COVERAGE_FILE="workspace/test-results"/.coverage.integration \                                                                     
MERINO_ENV=testing \
/Users/cgopal/.local/bin/uv run pytest \
tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py \
-k test_sections_pass_region_to_engagement_backend \ …
```
> GENAI-1208 fix - section TS with region 

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/custom_favicons.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/local_mode.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/integration/jobs/navigational_suggestions/test_local_mode.py
JIRA: [DISCO-3541](https://mozilla-hub.atlassian.net/browse/DISCO-3541)
Some domains block us from fetching favicons, and sometimes the Navigational Suggestion job doesn't provide the "right" favicon. 
We can certainly improve the job in the long term. But in the short term, we have the option to add hardcoded locations (URLs) for a domain. We prefer fetching from this hardcoded url rather than the one the Navigational Suggestions finds in the HTML.
For this to work, the domain also has to be in the `custom_domains.py` list. Reasons are two-fold:
- Every domain we want to fetch should be there (or in the BigQuery table)
- The custom favicon is just to tell the job, when the domain comes along, we already have a location for the favicon, so no reason to scrape the HTML.
The complexity …
> DISCO-3541 - Add custom favicons to icon fetching

- merino/curated_recommendations/provider.py
- merino/curated_recommendations/rankers.py
- merino/curated_recommendations/sections.py
- merino/web/api_v1.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_rankers.py
JIRA: [HNT-606](https://mozilla-hub.atlassian.net/browse/DISCO-606)
- [x ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [x ] The PR title starts with the JIRA issue reference, format example `[DISCO-####]`, and has the same title (if applicable)
- [skip ] `[load test: (abort|skip|warn)]` keywords are applied to the last commit message (if applicable)
- [x ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)
[HNT-606]: https://mozilla-hub.atlassian.net/browse/HNT-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [HNT-606] greedy ranking from inferred section interests

- merino/configs/default.toml
- merino/providers/suggest/finance/backends/polygon/backend.py
JIRA: [DISCO-3555](https://mozilla-hub.atlassian.net/browse/DISCO-3555)
There was a bug in the Polygon provider throwing on initialization due to the missing `api_key` required param.
```ValueError: Missing required parameters: Polygon API key ```
[DISCO-3555]: https://mozilla-hub.atlassian.net/browse/DISCO-3555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1740)
> Fix polygon provider throwing on initialization

- docs/operations/jobs/geonames-uploader.md
- merino/jobs/geonames_uploader/downloader.py
- merino/jobs/geonames_uploader/geonames.py
- merino/jobs/utils/__init__.py
- merino/jobs/utils/rs_client.py
- tests/unit/jobs/geonames_uploader/test_upload_geonames.py
- tests/unit/jobs/utils/test_utils.py
[Bug 1970276 - Make some small geonames uploader job improvements](https://bugzilla.mozilla.org/show_bug.cgi?id=1970276)
Now that I'm starting to use the newly updated geonames uploader job, I'd like to make a few small improvements:
* Require all desired filter-expression countries to be specified for a partition rather than being cumulative
* Log attachment file sizes when uploading them so it's easy to see if we're inadvertently creating huge geonames attachments
* Improve the doc a little
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1741)
> feat: improve geonames uploader job a little

- merino/providers/suggest/weather/backends/accuweather/backend.py
- merino/providers/suggest/weather/backends/accuweather/utils.py
- tests/integration/providers/suggest/weather/backends/test_accuweather.py
- tests/unit/providers/suggest/weather/backends/test_accuweather.py
JIRA: [DISCO-3567](https://mozilla-hub.atlassian.net/browse/DISCO-3567)
Since countries outside of the US and CA find it odd that locations are displayed as <City>, <Admin Code> rather than <City>, <Country>
Modifications are made such that depending on the city request for weather and the country of where the request is coming from. We change region_code to use either admin code or country name.
[DISCO-3567]: https://mozilla-hub.atlassian.net/browse/DISCO-3567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1747)
> [DISCO-3567] Weather: return admin code or country name based on request

- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_sections.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-780
In some cases, seeing the same layout for 4 consecutive sections
In particular, we want to avoid to avoid the first 2 sections from having the same layout. There have been examples of Popular Today and the 2nd section both using the large card layout. 
* Fix this by sorting ranked sections by `receievedFeedRank` & then apply layout cycling.
* Apply the 6 card layout to all sections before pruning, the ensure we only return sections that can accommodate the biggest layout.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1762)
> HNT-780: fix sections layout

- merino/curated_recommendations/__init__.py
- merino/curated_recommendations/ml_backends/fake_local_model.py
- merino/curated_recommendations/ml_backends/protocol.py
- tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_local_model.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/ml_backends/test_fake_local_model.py
JIRA: [GENAI-1370](https://mozilla-hub.atlassian.net/browse/GENAI-1370)
This switches the merino response to send down a personal interest model where the features are sections instead of topics.
[GENAI-1370]: https://mozilla-hub.atlassian.net/browse/GENAI-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1764)
> [GENAI-1370] added a new FakeLocalModel which is over sections instead of topics

- merino/configs/default.toml
JIRA: [DISCO-3571](https://mozilla-hub.atlassian.net/browse/DISCO-3571)
Temporarily disabling this provider. This is expected.
[DISCO-3571]: https://mozilla-hub.atlassian.net/browse/DISCO-3571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1769)
> [DISCO-3571] Disable Polygon provider temporarily after confirming api key setup

- .github/workflows/build-dockerhub-locust-image.yaml
- .github/workflows/main-workflow.yaml
- .github/workflows/pr-workflow.yaml
- .github/workflows/publish-dockerhub-locust-image.yaml
JIRA: [DISCO-3147](https://mozilla-hub.atlassian.net/browse/DISCO-3147)
This PR migrates the dockerhub build and publish workflow for the `merino-locust` image from CircleCI to GitHub Actions.
- Introduced two reusable workflows:
- `build-dockerhub-locust-image.yaml`:  builds the Locust image (`merino-locust`) from `./tests/load/Dockerfile` and uploads it as an artifact
- `publish-dockerhub-locust-image.yaml`:  downloads, loads, tags, and pushes the image to Docker Hub
- Preserved `[load test: skip]` directive to optionally skip the publish step
- Published tags include:
- `latest`
- `sha-<commit>`
[DISCO-3147]: https://mozilla-hub.atlassian.net/browse/DISCO-3147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> [DISCO-3147] migrate locust image build and publish jobs to gh actions

- docs/adr/0006-suggest-endpoint-split.md
JIRA: [DISCO-3557](https://mozilla-hub.atlassian.net/browse/DISCO-3557)
ADR for new providers integration and splitting from `/suggest` endpoint.
[DISCO-3557]: https://mozilla-hub.atlassian.net/browse/DISCO-3557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1774)
> [DISCO-3557] ADR for new suggest providers

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/custom_favicons.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/integration/jobs/navigational_suggestions/conftest.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_extractor.py
JIRA: [HNT-821](https://mozilla-hub.atlassian.net/browse/HNT-821)
Fix an issue where custom favicons were not applied for domains such as espn.com.
I believe the issue occurred because `ManifestBackend` keys icons on the domain without a suffix ('espn'), while `CUSTOM_FAVICONS` included the suffix ('espn.com'). This caused the custom favicon to be overwritten if the same publisher was added on a different TLD ('espn.in').
[HNT-821]: https://mozilla-hub.atlassian.net/browse/HNT-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1775)
> HNT-821: Fix favicons for domains with multiple TLD

- merino/curated_recommendations/ml_backends/fake_local_model.py
After the CTR model change, we didn’t update the thresholds for the coarse interest vector. They are too large and causing a confusing amount of zeros.
This PR updates the thresholds in the sections-CTR model. The logic of the values chosen:
0.002 is about the CTR of users who have clicked at least once
.0092 is ~99% not to be noise given laplace noise and 0.002 scale
.0184 is double the first edge
with these thresholds, the buckets are:
[probably never clicked, almost certainly clicked, clicked quite a bit]
- [ x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [x ] The PR title starts with the JIRA issue …
> [GENAI-1504] Updated threshold for local interest model

- merino/configs/default.toml
- tests/unit/providers/manifest/test_provider.py
JIRA: [DISCO-3608](https://mozilla-hub.atlassian.net/browse/DISCO-3608)
A short term solution. If we encouter a bug or want to ship an improvement for favicons, we shouldn't wait too long to bring it into production. We can manually trigger the Airflow job, but the Manifest provider should check at least once an hour if there is an updated top_picks.json available.
For the long term, I talked with @mmiermans and we thought an ADR might be helpful. Different endpoints and providers sync (or check for updates) differently, and it should be more standardized. 
For example, we have the [sync_gcs_blob.py](https://github.com/mozilla-services/merino-py/blob/main/merino/utils/synced_gcs_blob.py), which is able to check the timestamp every few minutes, and if there is an update, it can download th …
> DISCO-3608 Decrease the sync interval for the Manifest provider

- merino/curated_recommendations/layouts.py
- merino/curated_recommendations/sections.py
JIRA: [HNT-854](https://mozilla-hub.atlassian.net/browse/HNT-854)
Update the 2 row layout, to address an issue where the layout was not displaying correctly. The new layout has been [tested on New Tab](https://mozilla.slack.com/archives/C05EVRU1U1X/p1753478828840169).
**Before**
[HNT-854]: https://mozilla-hub.atlassian.net/browse/HNT-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1787)
> Fix: Update 2 row layout

- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-854](https://mozilla-hub.atlassian.net/browse/HNT-854)
Turn on the double row layout for the treatment branch of the [new-tab-ml-sections](https://experimenter.services.mozilla.com/nimbus/new-tab-ml-sections/summary) experiment.
[HNT-854]: https://mozilla-hub.atlassian.net/browse/HNT-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1790)
> HNT-854: Apply double row layout to subtopic treatment branch

- merino/configs/__init__.py
- merino/configs/default.toml
- merino/middleware/logging.py
- pyproject.toml
- tests/unit/middleware/test_logging.py
- uv.lock
JIRA: [DISCO-3622](https://mozilla-hub.atlassian.net/browse/DISCO-3622)
With this, we can leave the suggest request logging on for GCP V1 and toggle it off for V2.
[DISCO-3622]: https://mozilla-hub.atlassian.net/browse/DISCO-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1796)
> [DISCO 3622] - add a toggle for suggest request logging

- merino/curated_recommendations/engagement_backends/gcs_engagement.py
- merino/curated_recommendations/engagement_backends/protocol.py
- tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1793
With the release of the sections experiment, the ETL jobs are returning multiple items from a single content_id, because some have scheduled_surface_id and some do not.
We implement a temporary fix by adding them together, though the best long term fix is an ETL fix perhaps
- [ x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ x] The PR title starts with the JIRA issue reference, format example `[DISCO-####]`, and has the same title (if applicable)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1797)
> MC-1793 Fix item GCS Content Engagment data getting clobbered with lower values 

- merino/providers/suggest/finance/backends/polygon/backend.py
- merino/providers/suggest/finance/backends/polygon/filemanager.py
- merino/providers/suggest/finance/backends/protocol.py
- merino/providers/suggest/finance/provider.py
- tests/unit/providers/suggest/finance/backends/test_filemanager.py
- tests/unit/providers/suggest/finance/backends/test_polygon.py
- tests/unit/providers/suggest/finance/test_provider.py
JIRA: [DISCO-3624](https://mozilla-hub.atlassian.net/browse/DISCO-3624)
This PR improves the polygon provider's resync logic by introducing accurate tracking of the last successful manifest upload time using the GCS timestamp. This prevents unnecessary manifest uploads during provider restarts or redeployments by using the actual last modified time of the manifest in GCS, ensuring we only re-upload after the resync_interval has passed.
Changes:
- Updated the `PolygonFilemanager.get_file()` method to return the Blob.updated timestamp.
- Used the GCS blob's `updated` metadata field as the source of truth for `last_upload_at`.
- `last_upload_at` is now initialized during ` _fetch_manifest()` using the fetched manifest’s blob timestamp.
- Upload jobs still update `last_upload_at` based on …
> [DISCO-3624] Optimize upload job to run based on timestamp

- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: https://mozilla-hub.atlassian.net/browse/GENAI-1645
Prior to https://mozilla-hub.atlassian.net/browse/HNT-540 patch, layout_4_largewas observed to be the 2nd section. (It wasn’t listed as 2nd section, but due to sorting quirks it was) 
Restore this to the 2nd section (one after Top Stories) and observer any behavior changes.
- [x ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ x] The PR title starts with the JIRA issue reference, format example `[DISCO-####]`, and has the same title (if applicable)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1805)
> GENAI-1645 Restore layout for sections temporarily to troubleshoot data anomaly 

- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- merino/jobs/utils/domain_tester.py
- merino/providers/suggest/finance/backends/polygon/backend.py
- merino/utils/gcs/gcs_uploader.py
- merino/utils/gcs/models.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/content_handler/test_gcp_uploader.py
- tests/unit/utils/test_gcs_models.py
JIRA: [DISCO-3627](https://mozilla-hub.atlassian.net/browse/DISCO-3627)
This PR fixes a bug where `get_latest_file_for_diff()` incorrectly returns unrelated JSON files (e.g., `polygon_latest.json`) as the “most recent” top picks file, due to overly broad matching logic.
What Changed:
- Updated `get_most_recent_file` to support an optional match_string parameter that restricts results to files containing a given substring in the filename.
- Updated `get_latest_file_for_diff` to pass "top_picks" as the match string.
- Ensured that `top_picks_latest.json` is still explicitly excluded from diffing logic.
- Added filtering to guarantee only .json files are returned.
[DISCO-3627]: https://mozilla-hub.atlassian.net/browse/DISCO-3627?atlOrigin=eyJpIjoiNWRkNTljN …
> [DISCO-3627] fix: update get_most_recent_file matching logic

- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: https://mozilla-hub.atlassian.net/browse/GENAI-1645
This reverts all changes in https://github.com/mozilla-services/merino-py/pull/1011
Bryan would like certain treatments to remain unchanged, but this is not possible as some of those branches aren't sent in the merino request.
We may craft a new update in the future.
- [ x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [x ] The PR title starts with the JIRA issue reference, format example `[DISCO-####]`, and has the same title (if applicable)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1809)
> GENAI-1645 revert

- merino/curated_recommendations/prior_backends/experiment_rescaler.py
- merino/curated_recommendations/prior_backends/protocol.py
- merino/curated_recommendations/rankers.py
JIRA: https://mozilla-hub.atlassian.net/browse/GENAI-1657
Writeup here
Currently we’ve added approximately 10 new subtopic sections as an experiment branch for the subtopics experiment. Unlike the legacy topics, these topics are refreshed twice during the day. In contrast, the primary sections are refreshed daily at approximately 1AM EDT. 
https://mozilla-hub.atlassian.net/wiki/spaces/FAAMT/pages/1727725665/Thompson+Sampling+of+Subtopic+Sections
We divide the prior alpha by 4 for unseen subtopic items, and leave the priors for scheduled items the same. This keeps most of the unseen items just below the popular items.
I should add that there is a bug fix here. We added priors * n for the priors without checking that there are that many items. This could have resulted in 4 and 5 sections …
> GENAI-1657 Adjust priors Thompson sampling for subtopic items 

- docs/operations/jobs/navigational_suggestions.md
- merino/jobs/navigational_suggestions/domain_data_downloader.py
- tests/integration/jobs/navigational_suggestions/test_init.py
- tests/unit/jobs/navigational_suggestions/test_domain_data_downloader.py
JIRA: [HNT-871](https://mozilla-hub.atlassian.net/browse/HNT-871)
Download data for subdomains, instead of removing the subdomains during normalization.
For example, this will allow us to download the correct favicon for abcnews.go.com.
[HNT-871]: https://mozilla-hub.atlassian.net/browse/HNT-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1816)
> HNT-892: Fix DomainDataDownloader subdomain handling

- merino/jobs/cli.py
JIRA: [DISCO-3633](https://mozilla-hub.atlassian.net/browse/DISCO-3633)
We previously added a new airflow job for polygon image ingestion but forgot to register the command in `cli.py`
[DISCO-3633]: https://mozilla-hub.atlassian.net/browse/DISCO-3633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1819)
> [DISCO-3633] fix: register the polygon ingestion cli command

- merino/providers/suggest/finance/backends/polygon/filemanager.py
- tests/unit/providers/suggest/finance/backends/test_filemanager.py
JIRA: [DISCO-3633](https://mozilla-hub.atlassian.net/browse/DISCO-3633)
This PR updates the `PolygonFilemanager` class to defer creation of the `gcloud.aio.storage.Storage` client and `Bucket` until they are actually needed. This fixes the polygon ingestion airflow failure
Why:
Previously, the `Storage()` client was instantiated within the filemanager’s constructor, which caused failures when used in the airflow job because the job was instantiating the filemanager through the polygon provider backend and `Storage()` creates an underlying `aiohttp.TCPConnector` that immediately tries to bind to an async event loop at instantiation time. Specifically, [the job failed](https://workflow.telemetry.mozilla.org/log?dag_id=merino_jobs&task_id=polygon_ingestion_prod&execution_date=2025-08-05T05%3A …
> [DISCO-3633] fix: lazily instantiate gcs storage object

- merino/jobs/cli.py
- merino/jobs/polygon/__init__.py
- merino/jobs/polygon/polygon_ingestion.py
- merino/providers/suggest/finance/backends/polygon/backend.py
- merino/providers/suggest/manager.py
- tests/unit/providers/suggest/finance/backends/test_polygon.py
JIRA: [DISCO-3659](https://mozilla-hub.atlassian.net/browse/DISCO-3659)
- Undoes changes from this [PR](https://github.com/mozilla-services/merino-py/pull/1028).
- Fixes this issue properly which we hoped to do in this [PR](https://github.com/mozilla-services/merino-py/pull/1027).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1823)
> [DISCO-3659] Fix typer cli object exposing local variables on exceptions

- merino/configs/default.toml
- tests/unit/providers/suggest/finance/test_provider.py
JIRA: [DISCO-3635](https://mozilla-hub.atlassian.net/browse/DISCO-3635)
Update the resync interval for the manifest fetch job from weekly to daily
[DISCO-3635]: https://mozilla-hub.atlassian.net/browse/DISCO-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1831)
> [DISCO-3635] update resync interval for polygon fetch job

- merino/curated_recommendations/interest_picker.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_interest_picker.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-629
- Change max position of inline picker to the 3rd section
- Change title to “Follow topics to fine-tune your experience”
- Show more sections once interest picker is enabled
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1833)
> HNT-629: updating interest picker

- merino/jobs/wikipedia_indexer/__init__.py
- merino/jobs/wikipedia_indexer/filemanager.py
- tests/integration/jobs/wikipedia_indexer/test_filemanager.py
- tests/unit/jobs/wikipedia_indexer/test_filemanager.py
JIRA: [DISCO-3667](https://mozilla-hub.atlassian.net/browse/DISCO-3667)
Our Wikipedia indexer jobs rely on fetching [CirrusSearch dumps](https://dumps.wikimedia.org/other/cirrussearch/) from the Wikimedia dumps service. Normally, each language (e.g. `enwiki`, `plwiki`, etc.) has its own `*-cirrussearch-content.json.gz` dump available in the `current/` directory, which our `FileManager` retrieves and copies into GCS for downstream indexing.
Recently, jobs for some languages (e.g. `plwiki`) began failing with:
```
No matching dump files found for pattern: (?:.*/|^)plwiki-(\d+)-cirrussearch-content.json.gz
AttributeError: 'NoneType' object has no attribute 'name'
```
Investigation showed that:
* The `current/` directory at `https://dumps.wikimedia.org/other/cirrussearch/current/` now only …
> [DISCO-3667] Add temp fix for failing wiki job

- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_sections.py
JIRA: [HNT-976](https://mozilla-hub.atlassian.net/browse/HNT-976)
Handle the case where the crawl experiment has an `optin-` prefix, which happens when we opt-in to the experiment.
```shell
curl --location 'http://localhost:8000/api/v1/curated-recommendations' \
--header 'Content-Type: application/json' \
--data '{
"locale": "en-US",
"feeds": ["sections"],
"experimentName":"optin-new-ranking-for-legacy-topics-in-new-tab-v1",
"experimentBranch":"treatment-crawl"
}'
```
[HNT-976]: https://mozilla-hub.atlassian.net/browse/HNT-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1847)
> HNT-976: support opt-in crawl experiment enrollment

- merino/providers/suggest/finance/backends/polygon/backend.py
- merino/providers/suggest/finance/provider.py
- metrics.yaml
- tests/unit/providers/suggest/finance/backends/test_polygon.py
JIRA: [DISCO-3594](https://mozilla-hub.atlassian.net/browse/DISCO-3594])
Adding request latency (`timeit`) and count (`increment`) metrics for Polygon requests.
[DISCO-3594]: https://mozilla-hub.atlassian.net/browse/DISCO-3594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1841)
> [DISCO-3594] Add metrics for Polygon

- merino/configs/app_configs/config_sentry.py
- merino/configs/default.toml
- merino/providers/suggest/base.py
- merino/providers/suggest/custom_details.py
- merino/providers/suggest/google_suggest/__init__.py
- merino/providers/suggest/google_suggest/backends/__init__.py
- merino/providers/suggest/google_suggest/backends/google_suggest.py
- merino/providers/suggest/google_suggest/backends/protocol.py
- merino/providers/suggest/google_suggest/provider.py
- merino/providers/suggest/manager.py
- merino/web/api_v1.py
- metrics.yaml
- tests/unit/providers/suggest/google_suggest/__init__.py
- tests/unit/providers/suggest/google_suggest/backends/__init__.py
- tests/unit/providers/suggest/google_suggest/backends/test_google_suggest.py
- tests/unit/providers/suggest/google_suggest/conftest.py
- tests/unit/providers/suggest/google_suggest/test_provider.py
- tests/unit/test_config_sentry.py
JIRA: [DISCO-TODO](https://mozilla-hub.atlassian.net/browse/DISCO-3669)
This integrates Google Suggest/Search Complete API into Merino. Note that:
- We decided to add it as a provider for the suggest endpoint rather than adding a new endpoint to minimize the engineering lift for both Merino and Firefox.
- It's a dead simple suggestion provider connecting directly to Google's API endpoint w/o caching nor location handling.
- The API spec can be found in [DISCO-3669](https://mozilla-hub.atlassian.net/browse/DISCO-3669).
- This integration does not require an API token to Google, therefore it's subject to Google's rate limiting. Will attach a circuit-breaker to it as a follow-up to mitigate that.
- Also updated the sentry filtering to ignore the new query params that might contain user's …
> [Disco-3669] Add a suggest provider for google suggest

- merino/curated_recommendations/prior_backends/experiment_rescaler.py
- merino/curated_recommendations/prior_backends/protocol.py
- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_sections.py
- tests/unit/prior_backends/test_experiment_rescaler.py
JIRA: https://mozilla-hub.atlassian.net/browse/GENAI-1839
As we expand the content experiments we occasionally have experiments that have content that is shared among different experiments. If the impression distribution have dramatically different scales, the content will be ranked in an uneven way. Specifically, content that is only in a small (i.e. 3% experiment) will always show at the top when mixed with other content.
We are tracking these issues here and using them to create the appropriate experiment rescaler.
https://mozilla-hub.atlassian.net/wiki/spaces/FAAMT/pages/1795457076/HNT+Content+Experiment+Tracking
- [ x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ x] …
> GENAI-1839 Handle priors and rescaling for crawler topic experiments

- merino/configs/default.toml
- merino/configs/testing.toml
- merino/governance/circuitbreakers.py
- merino/providers/suggest/google_suggest/provider.py
- tests/unit/providers/suggest/google_suggest/test_provider.py
JIRA: [DISCO-3698](https://mozilla-hub.atlassian.net/browse/DISCO-3698)
This CB is made specifically due to Google's rate limiter on their search suggest endpoint. We might need to tweak the CB parameters once the experiment is live.
[DISCO-3698]: https://mozilla-hub.atlassian.net/browse/DISCO-3698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1859)
> [DISCO-3698]: Add a circuit breaker for google suggest

- merino/curated_recommendations/ml_backends/fake_local_model.py
JIRA: https://mozilla-hub.atlassian.net/browse/GENAI-1895
Insert final p/q privacy values for differential privacy that were approved by our privacy lead. Values add randomness to prevent user identification for inferred with requests sent over the OHTTP protocol. Details in the ticket.
Also fixed a threshold bug for the Sports section
- [x ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [x ] The PR title starts with the JIRA issue reference, format example `[DISCO-####]`, and has the same title (if applicable)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1864)
> GENAI-1895 final pivacy constants, bug fix for thresholds for sports

- merino/providers/suggest/google_suggest/provider.py
- tests/unit/providers/suggest/google_suggest/test_provider.py
JIRA: [DISCO-3731](https://mozilla-hub.atlassian.net/browse/DISCO-3731)
Google Trending requests do not specify the `q` query param.
[DISCO-3731]: https://mozilla-hub.atlassian.net/browse/DISCO-3731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1870)
> [DISCO-3731] fix: Allow empty queries for google suggest

- merino/configs/default.toml
- merino/providers/suggest/google_suggest/backends/google_suggest.py
- merino/providers/suggest/manager.py
- merino/utils/http_client.py
- metrics.yaml
- tests/unit/providers/suggest/google_suggest/backends/test_google_suggest.py
JIRA: [DISCO-3730](https://mozilla-hub.atlassian.net/browse/DISCO-3730)
This allows Merino to send Google Suggest requests through a proxy to circumvent rate limiting. 
This proxy will be set up separately and we will specify the proxy URL via an envvar.
[DISCO-3730]: https://mozilla-hub.atlassian.net/browse/DISCO-3730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3730] feat: Proxy requests for google suggest

- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
JIRA: [DISCO-3734](https://mozilla-hub.atlassian.net/browse/DISCO-3734)
Some more city corrections, for the EU widget expansion
[DISCO-3734]: https://mozilla-hub.atlassian.net/browse/DISCO-3734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1875)
> [DISCO-3734] chore: EU city corrections for weather

- merino/curated_recommendations/prior_backends/experiment_rescaler.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_sections.py
- tests/unit/prior_backends/test_experiment_rescaler.py
JIRA: [HNT-1063](https://mozilla-hub.atlassian.net/browse/HNT-1063)
Experimenter: [new-tab-crawling-v2](https://experimenter.services.mozilla.com/nimbus/new-tab-crawling-v2/update_overview/)
[Slack thread](https://mozilla.slack.com/archives/C08BYJWUC2E/p1758737132929059)
Start an another crawling experiment as a way to increase the audience for Thompson Sampling for the treatment branch.
[HNT-1063]: https://mozilla-hub.atlassian.net/browse/HNT-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1884)
> HNT-1063: Support new-tab-crawling-v2 experiment

- merino/configs/default.toml
- merino/configs/testing.toml
- merino/providers/suggest/custom_details.py
- merino/providers/suggest/flightaware/backends/flightaware.py
- merino/providers/suggest/flightaware/backends/protocol.py
- merino/providers/suggest/flightaware/backends/utils.py
- merino/providers/suggest/flightaware/provider.py
- merino/providers/suggest/manager.py
- tests/unit/providers/suggest/flightaware/__init__.py
- tests/unit/providers/suggest/flightaware/backend/__init__.py
- tests/unit/providers/suggest/flightaware/backend/test_flightaware.py
- tests/unit/providers/suggest/flightaware/backend/test_utils.py
- tests/unit/providers/suggest/flightaware/test_provider.py
JIRA: [DISCO-3733](https://mozilla-hub.atlassian.net/browse/DISCO-3733)
This PR implements the logic for querying aeroAPI to return flight suggestions through merino's suggest endpoint.
* **Fetch live flight info from AeroAPI**:
* Regex-based query validation to match valid flight numbers.
* Queries are checked against a temp hardcoded cache of flight numbers before calling AeroAPI. We are using this temp cache until [DISCO-3716](https://mozilla-hub.atlassian.net/browse/DISCO-3716) is completed. That work is currently blocked, pending Data-Eng’s help to configure the Flightaware secret in Airflow.
* **Partial response fields**:
* Certain fields (e.g. `status`) are commented out for now. The work of calculating flight status based on timestamps (`scheduled_out`, `actual_off`, etc.) will be …
> [DISCO-3733] Query AeroAPI for live flight info

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-1115
Enable 1-row for Popular Today for the following contextual ad experiments:
"new-tab-ad-updates-nightly"
"new-tab-contextual-ad-updates-v2-nightly"
"new-tab-contextual-ad-updates-beta"
"new-tab-contextual-ad-updates-v2-beta"
"new-tab-contextual-ad-updates-release"
"new-tab-contextual-ad-updates-v2-release"
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1894)
> HNT-1115: enable 1 row for popular today for contextual experiments

- merino/configs/default.toml
- merino/configs/production.toml
- merino/configs/testing.toml
- merino/jobs/polygon/polygon_ingestion.py
- merino/providers/suggest/finance/backends/polygon/backend.py
- merino/providers/suggest/finance/backends/polygon/utils.py
- merino/providers/suggest/manager.py
- tests/integration/providers/suggest/finance/backends/test_polygon.py
- tests/unit/providers/suggest/finance/backends/test_polygon.py
JIRA: [DISCO-3691](https://mozilla-hub.atlassian.net/browse/DISCO-3691)
**This PR adds the initial cache setup to support ticker snapshots in Redis. Included changes:**
- Added a Redis Lua script for bulk fetching ticker snapshots with their TTLs.
- Implemented cache key generation helper for ticker symbols.
- Added method to write snapshots into the cache with TTL.
- Added method to get snapshots with TTL and parse results back from cache.
- Added initial integration testcontainers tests for redis caching
**Notes:**
- The request-handling logic is not yet hooked up to the cache.
- Added TODOs in the code for error handling, metrics, and improved TTL warming strategy.
**Next steps:**
- Wire the cache logic into the main request flow.
- Address the TODOs for retries, metrics, and TTL …
> [DISCO-3691] Add caching for ticker snapshots

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/relevancy_uploader/__init__.py
- merino/jobs/utils/domain_tester.py
- merino/providers/suggest/adm/provider.py
- merino/providers/suggest/base.py
- merino/utils/domain_categories/__init__.py
- merino/utils/domain_categories/domain_category_mapping.py
- merino/utils/domain_categories/models.py
- pyproject.toml
- tests/integration/api/v1/suggest/test_suggest_top_picks.py
- tests/integration/jobs/navigational_suggestions/conftest.py
- tests/integration/jobs/navigational_suggestions/test_init.py
- tests/unit/jobs/navigational_suggestions/test_get_serp_categories.py
- tests/unit/jobs/navigational_suggestions/test_init.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py
- tests/unit/providers/suggest/adm/test_provider.py
- tests/unit/providers/suggest/top_picks/test_provider.py
- tests/unit/providers/suggest/wikipedia/test_provider.py
JIRA: [DISCO-3756](https://mozilla-hub.atlassian.net/browse/DISCO-3756)
This fixes a tricky circular import in Merino. Note this branch is created off #1101 . 
[DISCO-3756]: https://mozilla-hub.atlassian.net/browse/DISCO-3756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1897)
> DISCO 3756 - Fix a circular import issue in domain_category_mapping
