mozilla-services/merino-py

- merino/providers/adm.py
- merino/remotesettings.py
- merino/web/api_v1.py
- merino/web/models_v1.py
- tests/web/test_api_v1.py
- tests/web/util.py
This fixes https://mozilla-hub.atlassian.net/browse/CONSVC-1892.
> feat: Add models for suggest endpoint

- Makefile
- merino/config.py
- merino/main.py
- merino/middleware/logging.py
- merino/web/api_v1.py
- merino/web/dockerflow.py
- merino/web/models_v1.py
- poetry.lock
- pyproject.toml
- tests/web/test_dockerflow.py
- version.json
This closes [CONSVC-1849](https://mozilla-hub.atlassian.net/browse/CONSVC-1849).
> feat: Add dockerflow and MozLog

- .flake8
- merino/main.py
- merino/providers/__init__.py
- merino/providers/adm.py
- merino/providers/base.py
- merino/remotesettings.py
- poetry.lock
- pyproject.toml
- tests/web/util.py
* Moved provider initialization out of the class __init__ method and
into an abstract class method called `initialize`
* Added `httpx` as an async `requests` alternative
> CONSVC-1901 Add async apis to remote settings client

- merino/config_logging.py
- merino/middleware/logging.py
- tests/web/test_api_v1.py
Tried to mimick merino logs as best as I can for merino-py. What's still currently missing from the logs compared to the rust version of merino:
- os_family
- accepts_english
- form_factor
- browser
> [CONSVC-1941] feat: separate suggest log

- merino/cron.py
- merino/providers/adm.py
- merino/providers/cron.py
- poetry.lock
- pyproject.toml
- tests/providers/test_cron.py
- tests/test_cron.py
This is work in progress. 🚧
The goal of this pull request is to demonstrate how composition and protocols can help us increase testability. I've added a unit test for the new cron job to show how we can test async functions.
This change increases test coverage for `merino/providers/adm.py` from 33% to 38%. The new `merino/providers/cron.py` file has 100% test coverage. 📈
> refactor: improve testability of business logic

- test-engineering/contract-tests/client/README.md
- test-engineering/contract-tests/client/tests/kinto.py
- test-engineering/contract-tests/client/tests/test_merino.py
- test-engineering/contract-tests/volumes/client/scenarios.yml
* add teardown fixture in merino contract tests
* add delete records function to kinto module
* increase delay in contract test scenarios to assure remote settings resync in merino
* update README
[CONSVC-1840](https://mozilla-hub.atlassian.net/browse/CONSVC-1840)
> [CONSVC-1840] test: clear records between scenario executions in merino contract tests

- test-engineering/contract-tests/volumes/client/scenarios.yml
* `remote_settings__refresh` is not passing consistently. Mute the test while investigating.
[CONSVC-1970](https://mozilla-hub.atlassian.net/browse/CONSVC-1970)
> [CONSVC-1970] test: mute remote_settings__refresh

- .circleci/config.yml
Fixed a few minor issues with ci configurations.
> fix: fix gh-page by pinning to version 3.0

- docs/SUMMARY.md
- docs/dev/middlewares.md
- merino/middleware/featureflags.py
- merino/middleware/geolocation.py
- merino/middleware/logging.py
- merino/middleware/metrics.py
- merino/middleware/user_agent.py
Rewrite middlewares as pure ASGI middlewares to address the performance overheads with Starlette-based middlewares.
This is the first part for:
- geolocation
- user agent
- logging
Will convert the remainder (metrics and feature flags) in follow-ups. 
This closes [CONSVC-1982](https://mozilla-hub.atlassian.net/browse/CONSVC-1982).
> [CONSVC-1982] refactor: rewrite Merino middleware as pure ASGI middleware

- docs/dev/release-process.md
- docs/firefox.md
Fixed various dated things in the docs.
> docs: update various docs to date

- .circleci/config.yml
Fixed a copy&paste error inherited from Merino 😅.
> chore: fix circlci config for do-not-deploy [do not deploy]

- .dockerignore
- .gitignore
- .pre-commit-config.yaml
- Makefile
- docs/SUMMARY.md
- docs/dev/profiling.md
- docs/intro.md
- merino/main.py
- poetry.lock
- pyproject.toml
Play around profiling using [Scalene](https://github.com/plasma-umass/scalene).
> feat: add scalene for profiling

- merino/middleware/__init__.py
- merino/middleware/geolocation.py
- merino/middleware/logging.py
- merino/middleware/user_agent.py
- merino/providers/accuweather.py
- merino/providers/adm.py
- merino/providers/base.py
- merino/providers/wiki_fruit.py
- merino/web/api_v1.py
- tests/unit/middleware/test_geolocation.py
- tests/unit/providers/test_accuweather.py
- tests/unit/providers/test_adm.py
- tests/unit/web/util.py
> feat: prefer scope for data produced by middlewares

- merino/configs/default.toml
- merino/providers/accuweather.py
- tests/unit/providers/test_accuweather.py
> feat: add current conditions to accuweather response

- merino/config.py
> fix: config validator typo

- Makefile
- docs/SUMMARY.md
- docs/dev/feature_flags.md
- merino/featureflags.py
- merino/metrics.py
- merino/middleware/__init__.py
- merino/middleware/featureflags.py
- merino/middleware/metrics.py
- merino/web/api_v1.py
- poetry.lock
- pyproject.toml
- tests/unit/middleware/test_featureflags.py
- tests/unit/test_metrics.py
- tests/unit/web/test_metrics.py
This pull request integrates feature flags with StatsD metrics. 📈
Feature flag decisions are now automatically recorded and added as tags to emitted metrics.
[CONSVC-1603](https://mozilla-hub.atlassian.net/browse/CONSVC-1603)
> [CONSVC-1603]: add feature flags as tags to metrics

- docs/data.md
> doc: Update the metrics doc for timeouts [do not deploy]

- merino/middleware/geolocation.py
This fixes [CONSVC-2122](https://mozilla-hub.atlassian.net/browse/CONSVC-2122)
> [CONSVC-2122] fix: handle empty subdivisions in geolocation parsing

- docs/ops.md
- merino/config.py
- merino/configs/default.toml
- merino/configs/testing.toml
- merino/providers/__init__.py
- merino/web/api_v1.py
- tests/integration/api/v1/fake_providers.py
- tests/integration/api/v1/suggest/test_timeout_handling.py
- tests/unit/providers/test_init_providers.py
This is a follow-up for #137, in which I missed @hackebrot's review comments.
> refactor: simplify timeout handling for providers

- .circleci/config.yml
> Reference the correct tar for stage and prod publish

- docs/ops.md
Oops, forgot to delete `<<<<<<< HEAD` from the last rebase.
> doc: fix various typos in ops.md [do not deploy]

- merino/jobs/wikipedia_indexer/filemanager.py
- merino/jobs/wikipedia_indexer/indexer.py
- merino/jobs/wikipedia_indexer/util.py
- tests/unit/jobs/wikipedia_indexer/test_utils.py
Airflow killed the job because it thought it was halted. Hopefully this should fix that issue in airflow.
> fix: Fixes progress reporting for copy export.

- docs/adr/0001-locust-vs-k6-merino-py-performance-test-framework.md
* add an ADR Locust vs k6; Merino-py Performance Test Framework
* 🤦🏻‍♀️ The branch name has a typo, sorry for the confusion
[DISCO-2045](https://mozilla-hub.atlassian.net/browse/DISCO-2045)
[DISCO-2045]: https://mozilla-hub.atlassian.net/browse/DISCO-2046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2045] Investigate K6 load testing in merino-py CD

- merino/jobs/wikipedia_indexer/filemanager.py
After noticing the progress reporting was way off, I read through the BlobWriter code and found that it was returning the the total bytes written to an internal buffer rather than the number of bytes written per call to `write`. Also set the read chunk to the same size as the default blob chunk size (40mb)
> fix progress reporting by not incrementing `completed`

- Makefile
- scripts/quic.sh
Can be used for post-deploy health checks.
Initially wrote this for myself and I named it `quic.sh` as a mnemonic of quick-check, lol.
> chore: Add a script for quick health check [do not deploy]

- docs/data.md
- merino/providers/manager.py
- merino/providers/weather/provider.py
- tests/conftest.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/test_provider.py
- tests/unit/test_metrics.py
This commit adds:
* Timings for reading from and writing to Redis.
* Counters for cache hits, misses, and errors.
> [DISCO-2029] Collect weather provider cache metrics

- merino/configs/default.toml
- merino/jobs/wikipedia_indexer/__init__.py
- merino/jobs/wikipedia_indexer/filemanager.py
- merino/jobs/wikipedia_indexer/indexer.py
- merino/jobs/wikipedia_indexer/util.py
- tests/data/blocklist.csv
- tests/integration/jobs/wikipedia_indexer/test_indexer.py
- tests/unit/jobs/wikipedia_indexer/test_utils.py
We want to filter out all the articles in certain categories. The categories list currently live in GitHub.
> Add category content filtering to Wikipedia Indexing

- tests/load/README.md
JIRA: [DISCO-2172](https://mozilla-hub.atlassian.net/browse/DISCO-2172)
GitHub: N/A
The intention with this PR is to test the flow with a load test keywords
[DISCO-2172]: https://mozilla-hub.atlassian.net/browse/DISCO-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2172] Testing the load test keywords [load test: warn]

- tests/load/README.md
JIRA: [DISCO-2172](https://mozilla-hub.atlassian.net/browse/DISCO-2172)
GitHub: N/A
The intention with this PR is to test the flow with a load test keywords
[DISCO-2172]: https://mozilla-hub.atlassian.net/browse/DISCO-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2172] Testing the load test keywords [load test: abort]

- tests/load/README.md
JIRA: [DISCO-2172](https://mozilla-hub.atlassian.net/browse/DISCO-2172)
GitHub: N/A
Cleanup change from testing CD.
[DISCO-2172]: https://mozilla-hub.atlassian.net/browse/DISCO-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2172] Cleanup from testing the load test keywords [do not deploy]

- README.md
JIRA: N/A
GitHub: N/A
- Upon request from @jdragojevic add the CircleCI badge to the Merino-py README to promote CI pipeline status visibility.
- CircleCI Docs: [Adding Status Badges](https://circleci.com/docs/status-badges/)
> Add CircleCI Badge to README [do not deploy]

- tests/contract/README.md
JIRA: N/A
GitHub: N/A
An inconsequential change to test the CD pipeline.
> Fix line lengths in contract test README

- merino/providers/wikipedia/backends/elastic.py
- tests/unit/providers/wikipedia/backends/test_elastic.py
This adds "Wikipedia -" to the title and return the matching keyword (rather than the whole title) so that it looks like the clientside version of Wikipedia suggestions.
This is how the version on the client looks like: 
This is how this it looks with the changes:
> Fix the display for Dynamic Wikipedia

- dev/top_picks.json
JIRA:
GitHub:
Imported from https://merino-images.services.mozilla.com/1683016105000.0_top_picks.json which is generated automatically by navigational suggestions airflow job in prod stage.
> Update top_picks.json file

- docs/adr/0002-merino-general-response.md
Opening up this ADR for comments on content (decision has not been made yet). 
This ADR proposes a new format for the Suggest API Endpoint to manage provider specific data.
> Add ADR for Merino Suggest API Response

- merino/jobs/navigational_suggestions/domain_data_downloader.py
JIRA: [DENG-848](https://mozilla-hub.atlassian.net/browse/DENG-848)
Updates to use the latest partition of the domain metadata table which does not include `yandex`
* Update domain metadata query to use the correct partition.
* Update domain category query to use the v2 version of the table
[DENG-848]: https://mozilla-hub.atlassian.net/browse/DENG-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DENG-848] Updates to domain queries

- merino/providers/amo/provider.py
- merino/providers/custom_details.py
- tests/integration/api/v1/suggest/test_suggest_amo.py
- tests/unit/providers/amo/test_provider.py
@linabutler caught an error in my previous PR. This is the fix for it. 
ref: https://github.com/mozilla-services/merino-py/pull/283#discussion_r1185340367
> Actually fix the amo and addons name change for CustomDetails

- dev/top_picks.json
JIRA: 
GitHub:
Contains fix for:
1. https://bugzilla.mozilla.org/show_bug.cgi?id=1830328
2. https://mozilla-hub.atlassian.net/browse/DENG-848
The file is imported from https://merino-images.services.mozilla.com/1683624813000.0_top_picks.json
**Please note that the no. of entries in the latest top picks file have now reduced to 826. It was 1000 before.**
> Update top picks file for navigational suggestions

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
Fixes https://mozilla-hub.atlassian.net/browse/DENG-879
JIRA: https://mozilla-hub.atlassian.net/browse/DENG-879
GitHub:
- Add unit test case
> [DENG-879] Add "megapersonals" in blocked domain list

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
JIRA: https://mozilla-hub.atlassian.net/browse/DENG-1038
GitHub:
Fixes https://mozilla-hub.atlassian.net/browse/DENG-1038
> [DENG-1038] Add more title strings in blocked title list

- docs/dev/release-process.md
JIRA: N/A
GitHub: N/A
Add some docs on locating problematic commits using "git bisect". 
> doc: Add instructions to locate problematic commit

- CONTRIBUTING.md
- docs/SUMMARY.md
- docs/dev/release-process.md
- docs/dev/testing.md
JIRA: [DISCO-2373](https://mozilla-hub.atlassian.net/browse/DISCO-2373)
GitHub: #276 
- Format & update CONTRIBUTING.md to include testing guidelines and best practices
- Format & update release-process.md to include guidelines for test failures during deployment
[DISCO-2373]: https://mozilla-hub.atlassian.net/browse/DISCO-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2373] Add Test Contribution Guidelines for Merino-py

- dev/top_picks.json
JIRA: [DENG-1055, DENG-1053, DENG-1054]
Updates the top picks file to remove the flagged domains. Tooling to manually update and apply the blocklist coming in a follow up to this.
> [DENG-1055, DENG-1053, DENG-1054] Update top picks file

- .circleci/config.yml
- Makefile
- tests/contract/docker-compose.yml
JIRA: [DISCO-2391](https://mozilla-hub.atlassian.net/browse/DISCO-2391)
GitHub: #606 
- report contract test results to CircleCI to take advantage of insights 
- remove `check-for-deployment` job in the CircleCI config (job empty/no actions)
[DISCO-2391]: https://mozilla-hub.atlassian.net/browse/DISCO-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2391] Upload Contract Test Results to CircleCI Test Insights

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2473](https://mozilla-hub.atlassian.net/browse/DISCO-2473)
GitHub: N/A
Profiled Merino via Scalene and the result suggested the `AsyncClient` creation in the AccuWeather backend really requires a lot of CPU cycles and Merino created an AsyncClient for each request!
The benchmark results show a 5-6x boost in throughput and latency with the patch.
**Before: 225 QPS / 522 ms (p95 latency)
After: 1160 QPS / 115 ms (p95 latency)** 
[DISCO-2473]: https://mozilla-hub.atlassian.net/browse/DISCO-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2473] refactor: Reuse HTTP client for accuweather backend

- tests/load/locust_tests/locustfile.py
JIRA: N/A
GitHub: N/A
- Change load test request allocation to better reflect the merino production environment
> test: adjust request allocation in load tests [load test: warn]

- merino/config_logging.py
JIRA: [DISCO-2475](https://mozilla-hub.atlassian.net/browse/DISCO-2475)
Currently it's overwriting the `Severity` level. Trying this out to see if we can get it to categorize correctly with `severity` instead. The nesting of the records is a bit opaque to me, so I hope this works...
Some evidence that `severity` is a special keyword for the structured log: https://cloud.google.com/logging/docs/structured-logging#special-payload-fields
[DISCO-2475]: https://mozilla-hub.atlassian.net/browse/DISCO-2475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Write the GCP severity levels to `severity`

- docs/operations/configs.md
JIRA: N/A
GitHub: N/A
- Remove Wiki Fruit!!!!
> chore: remove cursed wiki fruit

- docs/operations/jobs.md
Clarify and expand on some things and fix some typos.
> docs: improve CSV RS uploader docs

- dev/top_picks.json
JIRA: [DISCO-2607](https://mozilla-hub.atlassian.net/browse/DISCO-2607)
The Top Picks suggestion provider has not had suggestions updated from the Airflow DAG merino_jobs since June. Update the Top Picks suggestions.
[DISCO-2607]: https://mozilla-hub.atlassian.net/browse/DISCO-2607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2607] update top_picks.json from most recent airflow job

- dev/top_picks.json
JIRA: NA
Update Top Picks 03-10-2023
> chore: update top picks file 03-10-2023

- merino/utils/blocklists.py
> add to blocklist

- merino/utils/blocklists.py
JIRA: N/A
https://bugzilla.mozilla.org/show_bug.cgi?id=1865283
Add to blocklist
> [DISCO-chore] add to blocklist

- tests/load/locustfiles/locustfile.py
updated locustfile with tuple unpack for status code and data
Fix for stage load tests in unpacking top picks data
> [DISCO] updated locustfile with tuple unpack for status code and data [load test: abort]

- catalog-info.yaml
This includes some metadata information that we might want to catalog in Backstage.
> Add a catalog-info.yaml for service catalog

- merino/main.py
[FastAPI docs on lifespan events](https://fastapi.tiangolo.com/advanced/events/)
[ASGI Lifespan Protocol](https://asgi.readthedocs.io/en/latest/specs/lifespan.html)
JIRA: [DISCO-2702](https://mozilla-hub.atlassian.net/browse/DISCO-2702)
The following deprecation warnings presented with recent update: 
```bash
merino/main.py:39
../merino-py/merino/main.py:39: DeprecationWarning:
on_event is deprecated, use lifespan event handlers instead.
Read more about it in the
[FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
@app.on_event("startup")
merino/main.py:46
../merino-py/merino/main.py:46: DeprecationWarning:
on_event is deprecated, use lifespan event handlers instead.
Read more about it in the
[FastAPI docs for Lifespan …
```
> [DISCO-2702] Update deprecated startup and shutdown events to lifespan

- docs/operations/jobs/csv-remote-settings.md
- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/base.py
- merino/jobs/csv_rs_uploader/mdn.py
- merino/jobs/csv_rs_uploader/pocket.py
- merino/jobs/csv_rs_uploader/row_major_base.py
- merino/jobs/csv_rs_uploader/yelp.py
- tests/unit/jobs/csv_rs_uploader/model.py
- tests/unit/jobs/csv_rs_uploader/test_yelp.py
JIRA: [SNG-928](https://mozilla-hub.atlassian.net/browse/SNG-928)
We are planning to support Yelp suggestions. This pull request adds an uploader for its dataset.
[SNG-928]: https://mozilla-hub.atlassian.net/browse/SNG-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add Yelp suggestions uploader

- merino/providers/adm/backends/protocol.py
- merino/providers/adm/backends/remotesettings.py
- merino/providers/adm/provider.py
- tests/unit/providers/adm/conftest.py
> fix(adm): Support string values for icon ids

- merino/configs/default.toml
- merino/jobs/amo_rs_uploader/__init__.py
- merino/jobs/cli.py
- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/relevancy_uploader/__init__.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- merino/jobs/utils/chunked_rs_uploader.py
- tests/unit/jobs/amo_rs_uploader/test_amo_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/utils.py
- tests/unit/jobs/relevancy_uploader/test_chunked_relevancy_rs_uploader.py
- tests/unit/jobs/relevancy_uploader/test_relevancy_csv_uploader.py
- tests/unit/jobs/relevancy_uploader/test_relevancy_data.csv
- tests/unit/jobs/relevancy_uploader/utils.py
- tests/unit/jobs/utils/test_chunked_rs_uploader.py
- top_picks_domains.csv
JIRA: [DISCO-2777](https://mozilla-hub.atlassian.net/browse/DISCO-2777)
[DISCO-2777]: https://mozilla-hub.atlassian.net/browse/DISCO-2777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2777] Add merino job to upload relevancy data to RS

- merino/cache/protocol.py
- merino/configs/default.toml
- merino/providers/custom_details.py
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
> [DISCO-2781] set http cache-control header for weather response

- merino/cache/protocol.py
- merino/configs/default.toml
- merino/providers/custom_details.py
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
- tests/unit/providers/weather/backends/test_accuweather.py
- tests/unit/providers/weather/test_provider.py
Reverts mozilla-services/merino-py#505
> Revert "[DISCO-2781] set http cache-control header for weather response"

- merino/configs/default.toml
- merino/configs/production.toml
- merino/providers/manager.py
- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather_city.py
- tests/unit/providers/weather/test_provider.py
> [DISCO-2809] - Use city to fetch weather suggestions

- merino/cache/protocol.py
- merino/middleware/geolocation.py
- merino/providers/weather/backends/accuweather.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- tests/unit/providers/weather/backends/test_accuweather_city.py
JIRA: [DISCO-2791](https://mozilla-hub.atlassian.net/browse/DISCO-2791)
[DISCO-2791]: https://mozilla-hub.atlassian.net/browse/DISCO-2791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2791] Handle requests with weather location key

- merino/configs/default.toml
- tests/unit/providers/weather/backends/test_accuweather_city.py
JIRA: [DISCO-2832](https://mozilla-hub.atlassian.net/browse/DISCO-2832)
- [ x ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ x ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ x ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)
[DISCO-2832]: https://mozilla-hub.atlassian.net/browse/DISCO-2832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2832] fix: Switch to the city completion endpoint

- merino/providers/weather/backends/accuweather.py
JIRA: [DISCO-TODO](https://mozilla-hub.atlassian.net/browse/DISCO-2842)
Removing weather request cache miss warning logs. These cache misses are expected and usual and we don't want to pollute our logs.
> [DISCO-2842] Refactor to remove cache miss warning logs

- docs/testing/load-tests.md
JIRA: N/A
Noticed a few dated instructions while copying load test results out of the locust cluster.
> fix(doc): Update load testing doc

- merino/jobs/csv_rs_uploader/fakespot.py
> fix(lint): Fix a linting issue in main

- merino/providers/weather/backends/accuweather.py
JIRA: [DISCO-2849](https://mozilla-hub.atlassian.net/browse/DISCO-2849)
[DISCO-2849]: https://mozilla-hub.atlassian.net/browse/DISCO-2849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2849] fix: Wrap the awaitable into the task group

- .circleci/config.yml
JIRA: [DISCO-2855](https://mozilla-hub.atlassian.net/browse/DISCO-2855)
[DISCO-2855]: https://mozilla-hub.atlassian.net/browse/DISCO-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2855] Store unit/coverage reports as artifacts

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- merino/curated_recommendations/corpus_backends/protocol.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_corpus_api_backend.py
JIRA: [MC-1269](https://mozilla-hub.atlassian.net/browse/MC-1269)
Update the topic mapping for curated recommendations based on recent changes to the [topics for phase 1](https://docs.google.com/document/d/1ICCHi1haxR-jIi_uZ3xQfPmphZm39MOmwQh0BRTXLHA/edit#heading=h.84si2bpbj78x).
[MC-1269]: https://mozilla-hub.atlassian.net/browse/MC-1269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MC-1269] fix: update curated recommendation topics

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2857](https://mozilla-hub.atlassian.net/browse/DISCO-2857)
Further refinement
[DISCO-2857]: https://mozilla-hub.atlassian.net/browse/DISCO-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2857] Enhance accuweather logs and error message

- merino/providers/weather/backends/accuweather.py
With the issues already defined, I think we can remove this, as all it does it create noise at this point. We might want to re add this once issues are addressed so that we can pinpoint specific locations of interest that we want to address.
> chore: remove location request logging

- merino/providers/weather/backends/accuweather.py
> chore: metric typo

- docs/testing/contract-tests/kinto-setup.md
JIRA: N/A
Fix a broken link in the contract test documentation
> [load test: warn] docs(contract-tests): fix broken link 

- Dockerfile
JIRA: N/A
Came across various warnings while building the Merino docker image locally.
> chore: Fix warnings in dockerfile

- tests/load/locustfiles/locustfile.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1316
Run a load test against the /api/v1/curated-recommendations endpoint with random topics query param.
> [load test: warn]MC-1316: curated-recommendations load test with random topics

- merino/middleware/geolocation.py
- merino/providers/weather/backends/accuweather.py
- tests/integration/providers/weather/backends/test_accuweather.py
- tests/unit/utils/test_log_data_creator.py
JIRA: [DISCO-2909](https://mozilla-hub.atlassian.net/browse/DISCO-2909)
Notice this while refactoring.
[DISCO-2909]: https://mozilla-hub.atlassian.net/browse/DISCO-2909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Drop alternative_regions from the Location model

- merino/providers/weather/backends/accuweather.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-2945](https://mozilla-hub.atlassian.net/browse/DISCO-2945)
We are seeing SSLErrors, EndOfStream and other errors for location endpoints for Accuweather. These errors are recent and unexpected. I've also reinforced the `current conditions` and `forecast` try-excepts too. These two aren't erroring out for now but I've added them as a precaution.
Following the existing pattern, I've added these excepts in the individual functions instead of the root `get_request` function. The `get_request` function would simply throw them up and the accuweather provider will catch them as `BackendError`s
[DISCO-2945]: https://mozilla-hub.atlassian.net/browse/DISCO-2945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> [DISCO-2945]: Handle get location by geolocation exceptions

- poetry.lock
- pyproject.toml
JIRA: [DISCO-2956](https://mozilla-hub.atlassian.net/browse/DISCO-2956)
This resolves the three security vulnerability reports.
- [ x ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ x ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
[DISCO-2956]: https://mozilla-hub.atlassian.net/browse/DISCO-2956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2956] fix(deps): Update various dependencies for security

- merino/providers/base.py
- merino/providers/wikipedia/provider.py
- tests/integration/api/v1/suggest/test_suggest_wikipedia.py
- tests/unit/providers/wikipedia/test_provider.py
JIRA: [DISCO-2935](https://mozilla-hub.atlassian.net/browse/DISCO-2935)
[DISCO-2935]: https://mozilla-hub.atlassian.net/browse/DISCO-2935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2935] Add categories field to Suggestion response

- docs/SUMMARY.md
> doc: add adr-0003 to the index

- docs/SUMMARY.md
- docs/data.md
- docs/social-contract.md
- docs/working agreement.md
JIRA: [DISCO-2982](https://mozilla-hub.atlassian.net/browse/DISCO-2982)
- Adding the social contract doc
- Updating the `data.md`
[DISCO-2982]: https://mozilla-hub.atlassian.net/browse/DISCO-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2982] Add social contract doc

- merino/providers/weather/backends/accuweather/backend.py
JIRA: [DISCO-2991](https://mozilla-hub.atlassian.net/browse/DISCO-2991)
We only record failures for requests that doesn’t use region, which isn't correct.
To simplify things, we are going to increment the metric for every failed region. 
So if maxmindb returns 2 regions and one failed but the other was successful, we would increment the metric by 1.
[DISCO-2991]: https://mozilla-hub.atlassian.net/browse/DISCO-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2991] fix: weather location processing error to inc with every failed region

- merino/configs/default.toml
- merino/web/api_v1.py
- tests/unit/web/test_api_v1.py
JIRA: [DISCO-3003](https://mozilla-hub.atlassian.net/browse/DISCO-3003)
Suggest endpoint to parse the Accept-Language header and filter out languages to only the ones it support
[DISCO-3003]: https://mozilla-hub.atlassian.net/browse/DISCO-3003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3003] Add Accept-Language header

- merino/providers/base.py
- merino/providers/weather/backends/accuweather/backend.py
- merino/providers/weather/backends/accuweather/utils.py
- merino/providers/weather/backends/protocol.py
- merino/providers/weather/provider.py
- merino/web/api_v1.py
- tests/unit/providers/weather/backends/test_accuweather.py
JIRA: [DISCO-3004](https://mozilla-hub.atlassian.net/browse/DISCO-3004)
Weather location auto complete to use accept language and select the first accepted language that is in the default language list
[DISCO-3004]: https://mozilla-hub.atlassian.net/browse/DISCO-3004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3004] weather location auto complete to use accept language

- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
JIRA: [DISCO-3031](https://mozilla-hub.atlassian.net/browse/DISCO-3031)
[DISCO-3031]: https://mozilla-hub.atlassian.net/browse/DISCO-3031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3031 fix: Top picks force upload latest json job

- merino/configs/production.toml
JIRA: [DISCO-3032](https://mozilla-hub.atlassian.net/browse/DISCO-3032)
[DISCO-3032]: https://mozilla-hub.atlassian.net/browse/DISCO-3032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3032] fix switch over to remote domain source for top picks

- poetry.lock
- pyproject.toml
- tests/load/poetry.lock
- tests/load/pyproject.toml
JIRA: N/A
See more [here](https://github.com/mozilla-services/merino-py/security/dependabot).
> chore: Update FastAPI for security fixes

- merino/curated_recommendations/protocol.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1574
Updating the Fakespot cta url to a new value
> MC-1574: update Fakespot CTA URL

- merino/utils/blocklists.py
JIRA: [DISCO-3053](https://mozilla-hub.atlassian.net/browse/DISCO-3053)
Requested to add rt to blocklist
[DISCO-3053]: https://mozilla-hub.atlassian.net/browse/DISCO-3053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3053] add new domain to nav suggest blocklist

- merino/curated_recommendations/fakespot_backend/protocol.py
JIRA: https://mozilla-hub.atlassian.net/browse/MC-1577
Updating the CTA copy, intro, footer for Fakespot integration.
> MC-1577: Final copy updates to Fakespot integration

- docs/adr/0004-default-load-tests.md
- docs/testing/load-tests.md
- tests/load/locustfiles/smoke_load.py
JIRA: [DISCO-3034](https://mozilla-hub.atlassian.net/browse/DISCO-3034)
- add ADR: Assure Endpoint Functionality and Load Test Suite Integrity with Default Load Tests
- modify smoke load test in-line with ADR, maximally reducing load test time and third party API demands
[DISCO-3034]: https://mozilla-hub.atlassian.net/browse/DISCO-3034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3034] ADR; Assure Endpoint Functionality and Load Test Suite Integrity with Default Load Tests

- merino/jobs/csv_rs_uploader/__init__.py
- merino/jobs/csv_rs_uploader/chunked_rs_uploader.py
- merino/jobs/geonames_uploader/__init__.py
- merino/jobs/relevancy_uploader/chunked_rs_uploader.py
- merino/jobs/utils/chunked_rs_uploader.py
- tests/unit/jobs/csv_rs_uploader/utils.py
- tests/unit/jobs/geonames_uploader/test_geonames_uploader.py
- tests/unit/jobs/utils/test_chunked_rs_uploader.py
JIRA: [DISCO-3068](https://mozilla-hub.atlassian.net/browse/DISCO-3068)
[DISCO-3068]: https://mozilla-hub.atlassian.net/browse/DISCO-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3068] Remove deletion safeguard check

- merino/providers/weather/backends/accuweather/pathfinder.py
- merino/providers/weather/provider.py
- tests/unit/providers/weather/test_provider.py
JIRA: [DISCO-3087](https://mozilla-hub.atlassian.net/browse/DISCO-3087)
This will allow us to see successful regions found by the path finder. A log will be emitting every 6 hours, so 4 logs/day.
[DISCO-3087]: https://mozilla-hub.atlassian.net/browse/DISCO-3087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3087] weather: log successful_region_mapping

- merino/providers/weather/backends/accuweather/pathfinder.py
> chore: some manual cities

- merino/curated_recommendations/localization.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: [HNT-261](https://mozilla-hub.atlassian.net/browse/HNT-261)
[Figma design](https://www.figma.com/design/VdghooQZTLiXYO8hF5pAuS/Feed?node-id=6259-53439&node-type=canvas&t=uhZasDBRX5BCq3hI-0)
[Slack thread to clarify requirements](https://mozilla.slack.com/archives/C058SAB9F0Q/p1734023002339339)
Add a news section to the sections experiment containing time-sensitive items.
[HNT-261]: https://mozilla-hub.atlassian.net/browse/HNT-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HNT-261] Add News section

- merino/utils/gcs/gcp_uploader.py
- merino/web/api_v1.py
- merino/web/models_v1.py
- tests/integration/api/v1/test_manifest.py
> DISCO-3108: Add manifest endpoint

- merino/web/api_v1.py
Fix: Use proper size from file.
> fix: adjust measurement for manifest file

- merino/providers/suggest/weather/backends/accuweather/utils.py
JIRA: [DISCO-3174](https://mozilla-hub.atlassian.net/browse/DISCO-3174)
Remove temp logs used to learn more about lat/long distance calculations
[DISCO-3174]: https://mozilla-hub.atlassian.net/browse/DISCO-3174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3174] Remove weather distance calc logs, increase radius distance threshold

- merino/configs/production.toml
- merino/configs/stage.toml
JIRA: [DISCO-3187](https://mozilla-hub.atlassian.net/browse/DISCO-3187)
Rewording comments in the `config/{ENV}.toml` files.
[DISCO-3187]: https://mozilla-hub.atlassian.net/browse/DISCO-3187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3187 Cleanup TOML comments

- docs/SUMMARY.md
- docs/adr/0005-asynchronous-gcs-client.md
JIRA: [DISCO-3067](https://mozilla-hub.atlassian.net/browse/DISCO-3067)
ADR for async gcs client
[DISCO-3067]: https://mozilla-hub.atlassian.net/browse/DISCO-3067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3067]: ADR for async gcs client

- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
> chore: weather city corrections

- merino/curated_recommendations/corpus_backends/corpus_api_backend.py
- tests/data/scheduled_surface.json
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_corpus_api_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
Reverts mozilla-services/merino-py#804
> Revert "[DISCO-3228] Add metrics and logging for curated recommendations favicons"

- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
JIRA: [DISCO-3294](https://mozilla-hub.atlassian.net/browse/DISCO-3294)
[DISCO-3294]: https://mozilla-hub.atlassian.net/browse/DISCO-3294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3294] chore: weather city updates

- .github/workflows/main-workflow.yaml
JIRA: [DISCO-3148](https://mozilla-hub.atlassian.net/browse/DISCO-3148)
[DISCO-3148]: https://mozilla-hub.atlassian.net/browse/DISCO-3148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3148] use github's official action for deploying pages

- merino/configs/__init__.py
- merino/configs/default.toml
- merino/configs/production.toml
- merino/configs/testing.toml
- merino/providers/suggest/manager.py
- merino/utils/icon_processor.py
- tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py
- tests/load/locustfiles/locustfile.py
- tests/unit/utils/test_icon_processor.py
JIRA: [DISCO-3309](https://mozilla-hub.atlassian.net/browse/DISCO-3309)
[DISCO-3309]: https://mozilla-hub.atlassian.net/browse/DISCO-3309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3309: Fix CDN hostname creation

- .github/workflows/pr-workflow.yaml
> fix: update GH actions PR workflow

- .github/workflows/main-workflow.yaml
JIRA: [DISCO-3256](https://mozilla-hub.atlassian.net/browse/DISCO-3256)
- Related to prerequisite to task
* fix typo in main-workflow
[DISCO-3256]: https://mozilla-hub.atlassian.net/browse/DISCO-3256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3256] fix(ci): typo run- in main-workflow.yaml

- merino/providers/suggest/adm/backends/remotesettings.py
- tests/unit/utils/test_icon_processor.py
JIRA: [DISCO-3310](https://mozilla-hub.atlassian.net/browse/DISCO-3310)
[DISCO-3310]: https://mozilla-hub.atlassian.net/browse/DISCO-3310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3310 parallel process icons in adm provider

- merino/utils/icon_processor.py
JIRA: [DISCO-3308](https://mozilla-hub.atlassian.net/browse/DISCO-3308)
[DISCO-3308]: https://mozilla-hub.atlassian.net/browse/DISCO-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3308: Add metrics to icon processor and batch processing inside remote settings

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- merino/jobs/navigational_suggestions/partner_favicons.py
- merino/providers/manifest/backends/protocol.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py
JIRA: [DISCO-3250](https://mozilla-hub.atlassian.net/browse/DISCO-3250)
[DISCO-3250]: https://mozilla-hub.atlassian.net/browse/DISCO-3250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3250] Upload partner images to GCS

- merino/providers/suggest/weather/backends/accuweather/utils.py
Additional temp logs to determine how useful is our weather distance calculations are.
> chore: temp logs to monitor weather distance calculations

- merino/utils/gcs/gcs_uploader.py
JIRA: [DISCO-3361](https://mozilla-hub.atlassian.net/browse/DISCO-3361)
Fix gcloud auth error when initializing gcp client locally
[DISCO-3361]: https://mozilla-hub.atlassian.net/browse/DISCO-3361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: fix gcloud auth error when initializing gcp client locally

- Dockerfile
- tests/load/Dockerfile
JIRA: [DISCO-3363](https://mozilla-hub.atlassian.net/browse/DISCO-3363)
See ticket
[DISCO-3363]: https://mozilla-hub.atlassian.net/browse/DISCO-3363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: fix uv run command for docker builds

- merino/jobs/navigational_suggestions/__init__.py
- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/domain_metadata_uploader.py
- merino/jobs/navigational_suggestions/utils.py
- merino/jobs/utils/domain_tester.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/conftest.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py
- tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py
JIRA: [DISCO-3360](https://mozilla-hub.atlassian.net/browse/DISCO-3360)
[DISCO-3360]: https://mozilla-hub.atlassian.net/browse/DISCO-3360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3360 Parallelize favicon processing for the nav-suggestions job

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
JIRA: [DISCO-3401](https://mozilla-hub.atlassian.net/browse/DISCO-3401)
[DISCO-3401]: https://mozilla-hub.atlassian.net/browse/DISCO-3401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3401 Fix bug in parsing json for nav suggestion job

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/navigational_suggestions/utils.py
JIRA: [DISCO-3404](https://mozilla-hub.atlassian.net/browse/DISCO-3404)
[DISCO-3404]: https://mozilla-hub.atlassian.net/browse/DISCO-3404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DISCO-3404 Resource optimization for airflow job

- merino/web/api_v1.py
- tests/integration/api/v1/suggest/test_suggest_weather.py
This reverts commit e9ee5992dbc5ba615117e0c4d48bb2f6f8c6cf97.
revert
> Revert "[DISCO-3393] Suggest: return 204 for no weather (#854)"

- Dockerfile
- pyproject.toml
- uv.lock
Adding `psutil` to the dependencies.
> fix: add psutil to dependencies

- merino/main.py
JIRA: [DISCO-3444](https://mozilla-hub.atlassian.net/browse/DISCO-3444)
[DISCO-3444]: https://mozilla-hub.atlassian.net/browse/DISCO-3444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO 3444] fix: make profile

- .gitignore
- CONTRIBUTING.md
- Makefile
- docs/operations/jobs/csv-remote-settings.md
- docs/testing/load-tests.md
- merino/jobs/__init__.py
JIRA: [DISCO-3390](https://mozilla-hub.atlassian.net/browse/DISCO-3390)
Remove left over 'poetry' mentions and update some docs and strings.
[DISCO-3390]: https://mozilla-hub.atlassian.net/browse/DISCO-3390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3390] Remove remaining poetry references

- .dockerignore
- .gitignore
- docs/dev/dependencies.md
JIRA: N/A.
Update dev docs to reflect the latest.
> doc: Update dev docs [load test: skip]

- merino/configs/production.toml
JIRA: [DISCO-3453](https://mozilla-hub.atlassian.net/browse/DISCO-3453)
[DISCO-3453]: https://mozilla-hub.atlassian.net/browse/DISCO-3453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO 3453] fix: Disable TopPicks [load test: skip]

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- merino/jobs/utils/domain_tester.py
- tests/integration/jobs/navigational_suggestions/conftest.py
- tests/unit/jobs/navigational_suggestions/conftest.py
- tests/unit/jobs/navigational_suggestions/test_domain_metadata_extractor.py
> fix: Use a regular context manager for the Scraper

- docs/data.md
- merino/configs/default.toml
- merino/governance/__init__.py
- merino/main.py
- tests/unit/governance/test_service_governing.py
JIRA: [DISCO-3457](https://mozilla-hub.atlassian.net/browse/DISCO-3457)
[DISCO-3457]: https://mozilla-hub.atlassian.net/browse/DISCO-3457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3457]: feat: Add metrics for circuit breakers

- merino/providers/suggest/weather/backends/accuweather/pathfinder.py
Some city corrections found while working on geo weather expansion
> chore: city corrections

- merino/curated_recommendations/corpus_backends/protocol.py
- merino/curated_recommendations/corpus_backends/sections_backend.py
- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/sections.py
- tests/data/sections.json
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_sections_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-581
Adding `iab` metadata to ML sections.
> HNT-581: adding IAB metadata to ML sections

- merino/curated_recommendations/protocol.py
- merino/curated_recommendations/provider.py
- merino/curated_recommendations/sections.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/test_sections.py
JIRA: [HNT-520](https://mozilla-hub.atlassian.net/browse/HNT-520)
[API spec](https://docs.google.com/document/d/1INE77wOJ2nAk_G-D6d64_fAsTCL36MQ18f77JVwvyQU/edit?tab=t.0)
Send basic content features along with recommendations to allow for personalization.
[HNT-520]: https://mozilla-hub.atlassian.net/browse/HNT-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HNT-520: Add recommendation features

- merino/utils/api/query_params.py
> fix: log invalid query params conditionally

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
- tests/integration/jobs/navigational_suggestions/test_domain_metadata_extractor.py
JIRA: [DISCO-3543](https://mozilla-hub.atlassian.net/browse/DISCO-3543)
We are running into issues inside the Airflow job when uploading favicons. Since we are calling it inside an async runtime now when we have a custom favicon we want to upload right away.
That's the error message from Airflow:
```
Failed to upload custom favicon for reuters.com: asyncio.run() cannot be called from a running event loop"}
```
The fix in this PR is to "manually" do what the `upload_favicon()` function does. But we don't do `asyncio.run(`, since we are already in an async context. 
That's the smallest change I can find, and I think it's fine. It's not perfect, and we come so close to the point where we have to refactor this thing. Closed https://github.com/mozilla-services/merino-py/pull/942 for this …
> DISCO-3543: Fix async issues on Airflow

- merino/curated_recommendations/sections.py
- tests/unit/curated_recommendations/test_sections.py
JIRA: https://mozilla-hub.atlassian.net/browse/HNT-538
Cycle through layouts for ML sections instead of assigning a 4 medium card layout.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1739)
> HNT-538: Cycle layouts for ML sections

- merino/jobs/utils/rs_client.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1744)
> feat: log RS client delete calls

- merino/curated_recommendations/provider.py
- merino/curated_recommendations/sections.py
- tests/data/sections.json
- tests/integration/api/v1/curated_recommendations/corpus_backends/test_sections_backend.py
- tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
- tests/unit/curated_recommendations/fixtures.py
- tests/unit/curated_recommendations/test_sections.py
Reverts mozilla-services/merino-py#954
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1748)
> Revert "HNT-540: Pull ML sections only when building sections feed"

- merino/jobs/wikipedia_offline_uploader/upload-data.sh
Small update to wiki offline upload scripts to include mobile locales, which hopefully will be rewritten soon 😬 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1751)
> chore: update wiki uploader include mobile locales

- .github/workflows/main-workflow.yaml
JIRA: [DISCO-3242](https://mozilla-hub.atlassian.net/browse/DISCO-3242)
- Set environment to build for docker publish job
- add tags to image
- updated image tags
[DISCO-3242]: https://mozilla-hub.atlassian.net/browse/DISCO-3242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1757)
> [DISCO-3242] Set environment to build for docker publish job

- merino/jobs/navigational_suggestions/domain_metadata_extractor.py
JIRA: [DISCO-3592](https://mozilla-hub.atlassian.net/browse/DISCO-3592)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1771)
[DISCO-3592]: https://mozilla-hub.atlassian.net/browse/DISCO-3592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3592]: add a new invalid title for navigational suggestions

- merino/providers/suggest/finance/backends/polygon/backend.py
- merino/providers/suggest/finance/backends/polygon/utils.py
- merino/providers/suggest/finance/provider.py
- tests/unit/providers/suggest/finance/backends/test_polygon.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1800)
> [DISCO-3573] Fix error message in logging

- merino/configs/default.toml
- merino/providers/suggest/finance/backends/polygon/utils.py
- merino/providers/suggest/finance/provider.py
JIRA: [DISCO-3623](https://mozilla-hub.atlassian.net/browse/DISCO-3623)
- Add `normalize_query()` method to the provider. 
- Use trade price instead of quote price.
- Enable provider by default.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1799)
[DISCO-3623]: https://mozilla-hub.atlassian.net/browse/DISCO-3623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-3623] Add provider normalize query method and tweaks

- merino/jobs/polygon/polygon_ingestion.py
- merino/providers/suggest/finance/backends/polygon/backend.py
- merino/providers/suggest/manager.py
- tests/unit/providers/suggest/finance/backends/test_polygon.py
JIRA: [DISCO-3659](https://mozilla-hub.atlassian.net/browse/DISCO-3659)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1822)
> [DISCO-3659] fix: pass in api key directly for polygon

- merino/jobs/polygon/__init__.py
- merino/providers/suggest/finance/backends/polygon/filemanager.py
- tests/unit/providers/suggest/finance/backends/test_filemanager.py
JIRA: [DISCO-3659](https://mozilla-hub.atlassian.net/browse/DISCO-3659)
Final change after https://github.com/mozilla-services/merino-py/pull/1029 gets merged and verified.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1824)
> [DISCO-3659] Stop re-raising exception for polygon airflow job

- merino/configs/default.toml
- merino/providers/suggest/manager.py
- merino/providers/suggest/yelp/__init__.py
- merino/providers/suggest/yelp/backends/protocol.py
- merino/providers/suggest/yelp/backends/yelp.py
- merino/providers/suggest/yelp/provider.py
JIRA: [DISCO-3656](https://mozilla-hub.atlassian.net/browse/DISCO-3656)
- Adding skeleton in preparation for yelp provider integration
- Added provider and backend classes
- Added some config values to start with
[DISCO-3656]: https://mozilla-hub.atlassian.net/browse/DISCO-3656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1830)
> [DISCO-3656] Add skeleton for Yelp provider

- merino/configs/default.toml
- merino/providers/suggest/custom_details.py
- merino/providers/suggest/manager.py
- merino/providers/suggest/yelp/backends/protocol.py
- merino/providers/suggest/yelp/backends/yelp.py
- merino/providers/suggest/yelp/provider.py
- tests/unit/providers/yelp/__init__.py
- tests/unit/providers/yelp/backends/__init__.py
- tests/unit/providers/yelp/backends/test_yelp.py
- tests/unit/providers/yelp/test_provider.py
JIRA: [DISCO-3658](https://mozilla-hub.atlassian.net/browse/DISCO-3658)
First attempt with integrating yelp with the API.
There are of course still pending items like keyword matching, caching/latency etc.
Curious if anyone has thoughts and opinions specifically the api response 
It would look like 
```
{
"suggestions": [
{
"title": "Yelp Suggestion",
"url": "https://www.yelp.com/biz/sheetz-milton?adjust_creative=7Id9NaRN3J5-xV_ReKfgiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=7Id9NaRN3J5-xV_ReKfgiw",
"provider": "yelp",
"is_sponsored": false,
"score": 2,
"custom_details": {
"yelp": {
"name": "Sheetz",
"address": "1304 Johns Creek Rd",
"price": "$$",
"rating": 4.6,
"review_count": 10,
"business_hours": [
{
"open": [
{
"is_overnight": true,
"start": "0000", …
```
> [DISCO-3658] Yelp intergration and response structure

- merino/providers/suggest/manager.py
- merino/providers/suggest/yelp/backends/yelp.py
- merino/providers/suggest/yelp/provider.py
- metrics.yaml
- tests/unit/providers/yelp/backends/test_yelp.py
JIRA: [DISCO-3661](https://mozilla-hub.atlassian.net/browse/DISCO-3661)
Adding basic metrics collection.
[DISCO-3661]: https://mozilla-hub.atlassian.net/browse/DISCO-3661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1851)
> DISCO-3661 Adding Yardstick metrics to Yelp

- merino/providers/suggest/custom_details.py
- tests/unit/providers/suggest/yelp/test_provider.py
Typing change to `business_hours` in Yelp Details and explicitly set them in tests to avoid future bugs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1857)
> bug: Yelp Details business hours changes

- merino/configs/default.toml
- merino/providers/suggest/flightaware/__init__.py
- merino/providers/suggest/flightaware/backends/flightaware.py
- merino/providers/suggest/flightaware/backends/protocol.py
- merino/providers/suggest/flightaware/provider.py
- merino/providers/suggest/manager.py
JIRA: [DISCO-3640](https://mozilla-hub.atlassian.net/browse/DISCO-3640)
This PR adds a skeleton/framework for the upcoming flight aware integration.
[DISCO-3640]: https://mozilla-hub.atlassian.net/browse/DISCO-3640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1867)
> [DISCO-3640] Add skeleton for Flight Aware provider

- merino/jobs/wikipedia_offline_uploader/top_n_by_frequency.py
JIRA: [DISCO-3696](https://mozilla-hub.atlassian.net/browse/DISCO-3696)
[DISCO-3696]: https://mozilla-hub.atlassian.net/browse/DISCO-3696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1869)
> [DISCO-3696] fix slow wiki job test

- docs/intro.md
JIRA: [DISCO-3684](https://mozilla-hub.atlassian.net/browse/DISCO-3684)
Added Merino Rust Extension and the Polygon
not sure if this is the right/best way to represent the merino rust extension
[DISCO-3684]: https://mozilla-hub.atlassian.net/browse/DISCO-3684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1883)
> [DISCO-3684] Mermaid diagram update

- merino/configs/default.toml
- merino/configs/testing.toml
JIRA: N/A.
Online Suggest is and will be US only for some time, let's spare some memory for other things.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MC-1895)
> chore: Exclude non-US regions for adm
